/**
 * WeRead insights + actions + sync history tab.
 *
 * The action kanban and sync history read/write through the host
 * `WereadTaskRepository` (loadActions / saveAction / loadSyncHistory / flush).
 */

import { memo, useEffect, useMemo, useRef, useState } from 'react';
import * as echarts from 'echarts/core';
import { BarChart, GraphChart } from 'echarts/charts';
import { GridComponent, TooltipComponent } from 'echarts/components';
import { CanvasRenderer } from 'echarts/renderers';
import type { EChartsCoreOption, EChartsType } from 'echarts/core';
import { useWereadAdapter } from './context';
import type { WereadAction, WereadSyncSummary } from '../core/types';
import type { AnalyticsBook, ThemePalette } from './WereadAnalytics';

echarts.use([BarChart, GraphChart, GridComponent, TooltipComponent, CanvasRenderer]);
type JsonObject = Record<string, unknown>;
type InsightNote = { id: string; bookId: string; book: string; text: string; words: string[]; kind: 'question' | 'action' | 'opinion' };
const STOP = new Set(['一个', '这个', '那个', '我们', '自己', '什么', '为什么', '怎么', '可以', '不是', '没有', '就是', '因为', '所以', '但是', '如果', '已经', '需要', '应该', '作者']);
function wordsOf(text: string): string[] { const Segmenter = (Intl as unknown as { Segmenter?: new (locale: string, options: { granularity: 'word' }) => { segment: (value: string) => Iterable<{ segment: string; isWordLike?: boolean }> } }).Segmenter; const normalized = text.toLocaleLowerCase(); const raw = Segmenter ? [...new Segmenter('zh-CN', { granularity: 'word' }).segment(normalized)].filter((item) => item.isWordLike).map((item) => item.segment) : normalized.match(/[a-z][a-z0-9]{2,}|[\u4e00-\u9fff]{2,6}/g) || []; return [...new Set(raw.filter((word) => word.length >= 2 && word.length <= 16 && !STOP.has(word)))]; }
function reviewOf(item: JsonObject): JsonObject { return item.review && typeof item.review === 'object' ? item.review as JsonObject : item; }
function noteKind(text: string): InsightNote['kind'] { if (/[?？]|为什么|如何|怎么|是否/.test(text)) return 'question'; if (/计划|尝试|行动|以后|下一步|需要做到|开始做/.test(text)) return 'action'; return 'opinion'; }
function Chart({ option, height = 420, onClick }: { option: EChartsCoreOption; height?: number; onClick?: (params: unknown) => void }) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!ref.current) return; const chart: EChartsType = echarts.init(ref.current, undefined, { renderer: 'canvas' }); chart.setOption(option); if (onClick) chart.on('click', onClick); const observer = new ResizeObserver(() => chart.resize()); observer.observe(ref.current); return () => { observer.disconnect(); chart.dispose(); }; }, [onClick, option]); return <div ref={ref} style={{ height }} />; }

export const WereadInsightsActions = memo(function WereadInsightsActions({ books, theme, onSelectBook }: { books: AnalyticsBook[]; theme: ThemePalette; onSelectBook: (bookId: string) => void }) {
  const { tasks } = useWereadAdapter();
  const [view, setView] = useState<'insights' | 'actions' | 'sync'>('insights'); const [actions, setActions] = useState<WereadAction[]>([]); const [history, setHistory] = useState<WereadSyncSummary[]>([]); const [storageError, setStorageError] = useState('');
  useEffect(() => { try { setActions(tasks.loadActions()); setHistory(tasks.loadSyncHistory()); } catch { setStorageError('数据表尚未初始化，请完全退出应用后重新启动。'); } }, [tasks]);
  const data = useMemo(() => {
    const notes: InsightNote[] = []; const wordBooks = new Map<string, Set<string>>();
    for (const book of books) for (const [index, item] of book.reviews.entries()) { const review = reviewOf(item); const text = String(review.content || '').trim(); if (!text) continue; const words = wordsOf(`${String(review.abstract || '')} ${text}`); const id = String(review.reviewId || `${book.bookId}:${index}`); notes.push({ id, bookId: book.bookId, book: book.title, text, words, kind: noteKind(text) }); words.forEach((word) => { const ids = wordBooks.get(word) || new Set<string>(); ids.add(book.bookId); wordBooks.set(word, ids); }); }
    const questions = notes.filter((note) => note.kind === 'question'); const candidates = notes.filter((note) => note.kind === 'action');
    const graphNodes: Array<{ name: string; category: number; symbolSize: number; bookId?: string }> = []; const graphLinks: Array<{ source: string; target: string }> = [];
    questions.slice(0, 25).forEach((note, index) => { const question = `问题${index + 1}`; graphNodes.push({ name: question, category: 0, symbolSize: 20, bookId: note.bookId }); for (const word of note.words.slice(0, 4)) { const concept = `概念：${word}`; if (!graphNodes.some((node) => node.name === concept)) graphNodes.push({ name: concept, category: 1, symbolSize: 14 }); graphLinks.push({ source: question, target: concept }); } });
    const maxNotes = Math.max(1, ...books.map((book) => book.noteCount + book.reviewCount)); const crossWords = new Set([...wordBooks.entries()].filter(([, ids]) => ids.size >= 2).map(([word]) => word));
    const values = books.map((book) => { const reviews = notes.filter((note) => note.bookId === book.bookId); const connectivity = new Set(reviews.flatMap((note) => note.words.filter((word) => crossWords.has(word)))).size; const actionsCount = reviews.filter((note) => note.kind === 'action').length; const reflection = Math.min(1, book.reviewCount / Math.max(1, book.noteCount)); const score = Math.round(((book.noteCount + book.reviewCount) / maxNotes * 0.35 + reflection * 0.3 + Math.min(1, connectivity / 12) * 0.2 + Math.min(1, actionsCount / 5) * 0.15) * 100); return { book, score, connectivity, actionsCount }; }).sort((a, b) => b.score - a.score).slice(0, 15);
    const gaps = [...wordBooks.entries()].filter(([, ids]) => ids.size === 1).map(([word, ids]) => ({ word, bookId: [...ids][0] })).slice(0, 20);
    const unresolved = questions.filter((question) => !notes.some((note) => note.id !== question.id && note.words.filter((word) => question.words.includes(word)).length >= 2 && note.kind !== 'question')).slice(0, 12);
    return { notes, questions, candidates, graphNodes, graphLinks, values, gaps, unresolved };
  }, [books]);
  const base = { color: theme.colors, textStyle: { color: theme.text } }; const axis = { axisLabel: { color: theme.muted }, axisLine: { lineStyle: { color: theme.border } }, splitLine: { lineStyle: { color: theme.border } } };
  const valueOption: EChartsCoreOption = { ...base, tooltip: { trigger: 'axis' }, grid: { left: 115, right: 35, top: 15, bottom: 30 }, yAxis: { ...axis, type: 'category', inverse: true, data: data.values.map(({ book }) => book.title), axisLabel: { color: theme.muted, width: 100, overflow: 'truncate' } }, xAxis: { ...axis, type: 'value', max: 100 }, series: [{ type: 'bar', data: data.values.map(({ book, score }) => ({ value: score, bookId: book.bookId })), label: { show: true, position: 'right', color: theme.muted }, itemStyle: { color: theme.colors[0], borderRadius: [0, 4, 4, 0] } }] };
  const opinionOption: EChartsCoreOption = { ...base, tooltip: { trigger: 'item' }, series: [{ type: 'graph', layout: 'force', roam: true, data: data.graphNodes, links: data.graphLinks, categories: [{ name: '未解决问题' }, { name: '相关概念' }], label: { show: true, color: theme.text, formatter: (params: unknown) => { const name = String((params as { name?: string }).name || ''); return name.startsWith('问题') ? name : name.replace('概念：', ''); } }, lineStyle: { color: 'source', opacity: 0.4 }, emphasis: { focus: 'adjacency' }, force: { repulsion: 180, edgeLength: [65, 130] } }] };
  async function saveAction(note: InsightNote) { const existing = actions.find((item) => item.sourceNoteId === note.id); if (existing) return; const now = Date.now(); const action: WereadAction = { id: `action-${note.id}`, bookId: note.bookId, sourceNoteId: note.id, content: note.text, status: 'todo', createdAt: now, updatedAt: now }; try { tasks.saveAction(action); setActions((current) => [action, ...current]); await tasks.flush(); } catch { setStorageError('行动表尚未初始化，请完全退出应用后重新启动。'); } }
  async function setStatus(action: WereadAction, status: WereadAction['status']) { const next = { ...action, status, updatedAt: Date.now() }; tasks.saveAction(next); setActions((current) => current.map((item) => item.id === action.id ? next : item)); await tasks.flush(); }
  const tabs = [['insights', '洞察诊断'], ['actions', '阅读行动'], ['sync', '同步历史']] as const;
  return <div className="space-y-4"><div className="flex items-center gap-2"><div className="mr-auto"><h2 className="text-lg font-semibold">洞察与行动</h2><p className="mt-1 text-sm text-muted-foreground">把阅读分析转化为问题、价值判断和实际行动。</p></div>{tabs.map(([id, label]) => <button key={id} onClick={() => setView(id)} className={`rounded px-3 py-1.5 text-sm ${view === id ? 'bg-primary text-primary-foreground' : 'border hover:bg-accent'}`}>{label}</button>)}</div>{storageError && <p className="rounded border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{storageError}</p>}
    {view === 'insights' && <><section className="rounded-lg border bg-card p-3"><h3 className="px-2 text-sm font-medium">阅读价值综合评分</h3><p className="px-2 pt-1 text-xs text-muted-foreground">综合笔记量、思考率、跨书连接和行动启发。</p><Chart option={valueOption} height={Math.max(380, data.values.length * 28)} onClick={(params) => { const id = String((params as { data?: { bookId?: string } }).data?.bookId || ''); if (id) onSelectBook(id); }} /></section><div className="grid gap-4 xl:grid-cols-2"><section className="rounded-lg border bg-card p-3"><h3 className="px-2 text-sm font-medium">问题—概念网络</h3><Chart option={opinionOption} height={500} /></section><section className="rounded-lg border bg-card p-4"><h3 className="text-sm font-medium">尚未解决的问题</h3><div className="mt-3 space-y-2">{data.unresolved.map((note) => <button key={note.id} onClick={() => onSelectBook(note.bookId)} className="block w-full rounded border bg-background p-3 text-left hover:bg-accent"><p className="text-xs text-muted-foreground">{note.book}</p><p className="mt-1 line-clamp-2 text-sm">{note.text}</p></button>)}{!data.unresolved.length && <p className="py-8 text-center text-sm text-muted-foreground">暂无明显未解决问题</p>}</div></section></div><section className="rounded-lg border bg-card p-4"><h3 className="text-sm font-medium">知识缺口诊断</h3><p className="mt-1 text-xs text-muted-foreground">目前只有单一书籍来源支撑的概念，建议引入更多来源交叉验证。</p><div className="mt-3 flex flex-wrap gap-2">{data.gaps.map((gap) => <button key={`${gap.word}:${gap.bookId}`} onClick={() => onSelectBook(gap.bookId)} className="rounded-full border bg-background px-3 py-1 text-xs hover:bg-accent">{gap.word}</button>)}</div></section></>}
    {view === 'actions' && <><section className="rounded-lg border bg-card p-4"><h3 className="text-sm font-medium">从笔记识别的行动候选</h3><div className="mt-3 grid gap-2 md:grid-cols-2">{data.candidates.slice(0, 20).map((note) => { const added = actions.some((item) => item.sourceNoteId === note.id); return <div key={note.id} className="rounded border bg-background p-3"><p className="text-xs text-muted-foreground">{note.book}</p><p className="mt-1 line-clamp-3 text-sm">{note.text}</p><button disabled={added} onClick={() => void saveAction(note)} className="mt-2 rounded border px-2 py-1 text-xs hover:bg-accent disabled:opacity-50">{added ? '已加入行动' : '加入行动'}</button></div>; })}</div></section><section className="rounded-lg border bg-card p-4"><h3 className="text-sm font-medium">行动看板</h3><div className="mt-3 grid gap-3 lg:grid-cols-3">{(['todo', 'doing', 'done'] as const).map((status) => <div key={status} className="rounded border bg-background p-3"><h4 className="text-sm font-medium">{{ todo: '待办', doing: '进行中', done: '已完成' }[status]} · {actions.filter((item) => item.status === status).length}</h4><div className="mt-2 space-y-2">{actions.filter((item) => item.status === status).map((action) => <div key={action.id} className="rounded bg-muted/50 p-2"><p className="text-xs leading-5">{action.content}</p><div className="mt-2 flex gap-1">{(['todo', 'doing', 'done'] as const).filter((next) => next !== status).map((next) => <button key={next} onClick={() => void setStatus(action, next)} className="rounded border bg-background px-1.5 py-0.5 text-[11px]">移至{{ todo: '待办', doing: '进行中', done: '完成' }[next]}</button>)}</div></div>)}</div></div>)}</div></section></>}
    {view === 'sync' && <section className="rounded-lg border bg-card p-4"><h3 className="text-sm font-medium">笔记同步历史</h3><p className="mt-1 text-xs text-muted-foreground">每次完整同步会自动记录新增、修改和删除差异。</p><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-muted-foreground"><tr className="border-b"><th className="p-2">同步时间</th><th className="p-2">新增书籍</th><th className="p-2">更新书籍</th><th className="p-2">删除书籍</th><th className="p-2">新增笔记</th><th className="p-2">删除笔记</th><th className="p-2">缓存总量</th></tr></thead><tbody>{history.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-2">{new Date(item.syncedAt).toLocaleString('zh-CN')}</td><td className="p-2 text-success">+{item.addedBooks}</td><td className="p-2">{item.updatedBooks}</td><td className="p-2 text-destructive">-{item.deletedBooks}</td><td className="p-2 text-success">+{item.addedNotes}</td><td className="p-2 text-destructive">-{item.deletedNotes}</td><td className="p-2">{item.totalBooks} 本 / {item.totalNotes} 条</td></tr>)}</tbody></table>{!history.length && <p className="py-10 text-center text-sm text-muted-foreground">完成下一次笔记同步后开始记录历史</p>}</div></section>}
  </div>;
});
