import React, { useEffect, useMemo, useRef, useState } from 'react';
import * as echarts from 'echarts/core';
import { BarChart, GraphChart, HeatmapChart, SankeyChart } from 'echarts/charts';
import { GridComponent, LegendComponent, TooltipComponent, VisualMapComponent } from 'echarts/components';
import { CanvasRenderer } from 'echarts/renderers';
import type { EChartsCoreOption, EChartsType } from 'echarts/core';
import type { AnalyticsBook, ThemePalette } from './WereadAnalytics';

echarts.use([BarChart, GraphChart, HeatmapChart, SankeyChart, GridComponent, LegendComponent, TooltipComponent, VisualMapComponent, CanvasRenderer]);
type JsonObject = Record<string, unknown>;
type NetworkNote = { id: string; bookId: string; book: string; author: string; chapter: string; text: string; words: string[] };
const STOP_WORDS = new Set(['一个', '一些', '这个', '那个', '这些', '我们', '自己', '什么', '为什么', '怎么', '可以', '不是', '没有', '就是', '因为', '所以', '但是', '如果', '已经', '还是', '以及', '对于', '通过', '进行', '这种', '一种', '可能', '需要', '应该', '非常', '作者', '书中']);

function wordsOf(text: string): string[] {
  const Segmenter = (Intl as unknown as { Segmenter?: new (locale: string, options: { granularity: 'word' }) => { segment: (value: string) => Iterable<{ segment: string; isWordLike?: boolean }> } }).Segmenter;
  const normalized = text.toLocaleLowerCase();
  const words = Segmenter ? [...new Segmenter('zh-CN', { granularity: 'word' }).segment(normalized)].filter((part) => part.isWordLike).map((part) => part.segment) : normalized.match(/[a-z][a-z0-9]{2,}|[\u4e00-\u9fff]{2,6}/g) || [];
  return [...new Set(words.map((word) => word.trim()).filter((word) => word.length >= 2 && word.length <= 16 && !STOP_WORDS.has(word) && !/^\d+$/.test(word)))];
}
function objectOf(value: unknown): JsonObject { return value && typeof value === 'object' ? value as JsonObject : {}; }
function reviewOf(item: JsonObject): JsonObject { return objectOf(item.review || item); }
function noteSimilarity(left: NetworkNote, right: NetworkNote): number { const rightWords = new Set(right.words); const shared = left.words.filter((word) => rightWords.has(word)).length; const total = new Set([...left.words, ...right.words]).size; return total ? shared / total : 0; }

function Chart({ option, height = 560, onClick }: { option: EChartsCoreOption; height?: number; onClick?: (params: unknown) => void }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!ref.current) return; const chart: EChartsType = echarts.init(ref.current, undefined, { renderer: 'canvas' }); chart.setOption(option); if (onClick) chart.on('click', onClick); const observer = new ResizeObserver(() => chart.resize()); observer.observe(ref.current); return () => { observer.disconnect(); chart.dispose(); }; }, [onClick, option]);
  return <div ref={ref} className="w-full" style={{ height }} />;
}

export const WereadKnowledgeNetwork: React.FC<{ books: AnalyticsBook[]; theme: ThemePalette; onSelectBook: (bookId: string) => void }> = ({ books, theme, onSelectBook }) => {
  const [view, setView] = useState<'relations' | 'concepts' | 'authors' | 'wander'>('relations');
  const [graphMode, setGraphMode] = useState<'structure' | 'knowledge'>('structure');
  const [selectedNoteId, setSelectedNoteId] = useState('');
  const data = useMemo(() => {
    const notes: NetworkNote[] = [];
    for (const book of books) {
      book.highlights.forEach((item, index) => { const chapter = objectOf(item.chapter); const text = String(item.markText || '').trim(); if (text) notes.push({ id: String(item.bookmarkId || `h-${book.bookId}-${index}`), bookId: book.bookId, book: book.title, author: book.author || '未知作者', chapter: String(chapter.title || item.chapterTitle || '未分章节'), text, words: wordsOf(text) }); });
      book.reviews.forEach((item, index) => { const review = reviewOf(item); const text = String(review.content || '').trim(); if (text) notes.push({ id: String(review.reviewId || `r-${book.bookId}-${index}`), bookId: book.bookId, book: book.title, author: book.author || '未知作者', chapter: String(review.chapterName || '全书/未分章节'), text, words: wordsOf(`${String(review.abstract || '')} ${text}`) }); });
    }
    const wordCount = new Map<string, number>(); const wordBooks = new Map<string, Set<string>>(); const pairs = new Map<string, number>();
    for (const note of notes) { for (const word of note.words) { wordCount.set(word, (wordCount.get(word) || 0) + 1); const ids = wordBooks.get(word) || new Set<string>(); ids.add(note.bookId); wordBooks.set(word, ids); } for (let i = 0; i < Math.min(note.words.length, 15); i += 1) for (let j = i + 1; j < Math.min(note.words.length, 15); j += 1) { const key = [note.words[i], note.words[j]].sort().join('\u0000'); pairs.set(key, (pairs.get(key) || 0) + 1); } }
    const coreWords = [...wordCount.entries()].sort((a, b) => b[1] - a[1]).slice(0, 50).map(([word]) => word); const coreSet = new Set(coreWords);
    const pairLinks = [...pairs.entries()].filter(([key, count]) => count >= 2 && key.split('\u0000').every((word) => coreSet.has(word))).sort((a, b) => b[1] - a[1]).slice(0, 90);
    const adjacency = new Map(coreWords.map((word) => [word, new Set<string>()])); for (const [key] of pairLinks) { const [left, right] = key.split('\u0000'); adjacency.get(left)?.add(right); adjacency.get(right)?.add(left); }
    const visited = new Set<string>(); const communities: string[][] = [];
    for (const word of coreWords) { if (visited.has(word) || !adjacency.get(word)?.size) continue; const community: string[] = []; const queue = [word]; visited.add(word); while (queue.length) { const current = queue.shift(); if (!current) break; community.push(current); for (const next of adjacency.get(current) || []) if (!visited.has(next)) { visited.add(next); queue.push(next); } } communities.push(community); }
    communities.sort((a, b) => b.length - a.length); const communityByWord = new Map<string, number>(); communities.forEach((items, index) => items.forEach((word) => communityByWord.set(word, index)));
    const crossBook = [...wordBooks.entries()].filter(([, ids]) => ids.size >= 2).map(([word, ids]) => ({ word, books: ids.size, count: wordCount.get(word) || 0 })).sort((a, b) => b.books - a.books || b.count - a.count).slice(0, 20);
    const isolated = [...wordBooks.entries()].filter(([word, ids]) => ids.size === 1 && (adjacency.get(word)?.size || 0) === 0).sort((a, b) => (wordCount.get(b[0]) || 0) - (wordCount.get(a[0]) || 0)).slice(0, 20).map(([word]) => word);
    const coreConcepts = coreWords.map((word) => ({ word, degree: adjacency.get(word)?.size || 0, count: wordCount.get(word) || 0 })).sort((a, b) => b.degree - a.degree || b.count - a.count).slice(0, 15);
    const authors = [...new Set(books.map((book) => book.author || '未知作者'))].slice(0, 12); const vocab = coreWords.slice(0, 40);
    const authorVectors = new Map(authors.map((author) => { const authorNotes = notes.filter((note) => note.author === author); const counts = new Map<string, number>(); authorNotes.forEach((note) => note.words.forEach((word) => counts.set(word, (counts.get(word) || 0) + 1))); return [author, vocab.map((word) => counts.get(word) || 0)]; }));
    const cosine = (left: number[], right: number[]) => { const dot = left.reduce((sum, value, index) => sum + value * right[index], 0); const magnitude = (values: number[]) => Math.sqrt(values.reduce((sum, value) => sum + value * value, 0)); return dot ? Math.round(dot / (magnitude(left) * magnitude(right)) * 100) : 0; };
    const authorMatrix = authors.flatMap((left, y) => authors.map((right, x) => [x, y, left === right ? 100 : cosine(authorVectors.get(left) || [], authorVectors.get(right) || [])]));
    const topBooks = [...books].sort((a, b) => b.noteCount + b.reviewCount - a.noteCount - a.reviewCount).slice(0, 8); const structureNodes: Array<{ name: string; category: number; symbolSize: number }> = []; const structureLinks: Array<{ source: string; target: string; value: number }> = [];
    for (const book of topBooks) { const bookNode = `书籍：${book.title}`; structureNodes.push({ name: bookNode, category: 0, symbolSize: 26 }); const chapterNotes = new Map<string, NetworkNote[]>(); notes.filter((note) => note.bookId === book.bookId).forEach((note) => chapterNotes.set(note.chapter, [...(chapterNotes.get(note.chapter) || []), note])); for (const [chapter, items] of [...chapterNotes.entries()].sort((a, b) => b[1].length - a[1].length).slice(0, 5)) { const chapterNode = `${book.title}｜${chapter}`; structureNodes.push({ name: chapterNode, category: 1, symbolSize: 17 }); structureLinks.push({ source: bookNode, target: chapterNode, value: items.length }); const counts = new Map<string, number>(); items.forEach((note) => note.words.forEach((word) => counts.set(word, (counts.get(word) || 0) + 1))); for (const [word, count] of [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3)) { const keywordNode = `关键词：${word}`; if (!structureNodes.some((node) => node.name === keywordNode)) structureNodes.push({ name: keywordNode, category: 2, symbolSize: 12 + Math.sqrt(wordCount.get(word) || 1) }); structureLinks.push({ source: chapterNode, target: keywordNode, value: count }); } } }
    const knowledgeNodes = [{ name: '我的阅读知识', category: 0, symbolSize: 38 }]; const knowledgeLinks: Array<{ source: string; target: string; value: number }> = [];
    for (const book of topBooks) { const author = `作者：${book.author || '未知作者'}`; const bookNode = `书籍：${book.title}`; if (!knowledgeNodes.some((node) => node.name === author)) { knowledgeNodes.push({ name: author, category: 1, symbolSize: 24 }); knowledgeLinks.push({ source: '我的阅读知识', target: author, value: 1 }); } knowledgeNodes.push({ name: bookNode, category: 2, symbolSize: 20 }); knowledgeLinks.push({ source: author, target: bookNode, value: book.noteCount + book.reviewCount }); const counts = new Map<string, number>(); notes.filter((note) => note.bookId === book.bookId).forEach((note) => note.words.forEach((word) => counts.set(word, (counts.get(word) || 0) + 1))); for (const [word, count] of [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 4)) { const concept = `概念：${word}`; if (!knowledgeNodes.some((node) => node.name === concept)) knowledgeNodes.push({ name: concept, category: 3, symbolSize: 13 + Math.sqrt(wordCount.get(word) || 1) }); knowledgeLinks.push({ source: bookNode, target: concept, value: count }); } }
    return { notes, wordCount, pairLinks, adjacency, communities, communityByWord, crossBook, isolated, coreConcepts, authors, authorMatrix, structureNodes, structureLinks, knowledgeNodes, knowledgeLinks };
  }, [books]);
  useEffect(() => { if (!selectedNoteId && data.notes[0]) setSelectedNoteId(data.notes[0].id); }, [data.notes, selectedNoteId]);
  const selectedNote = data.notes.find((note) => note.id === selectedNoteId) || data.notes[0];
  const related = selectedNote ? data.notes.filter((note) => note.id !== selectedNote.id).map((note) => ({ note, score: noteSimilarity(selectedNote, note) })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 8) : [];
  const base = { color: theme.colors, textStyle: { color: theme.text } }; const axis = { axisLabel: { color: theme.muted }, axisLine: { lineStyle: { color: theme.border } }, splitLine: { lineStyle: { color: theme.border } } };
  const graphData = graphMode === 'structure' ? data.structureNodes : data.knowledgeNodes; const graphLinks = graphMode === 'structure' ? data.structureLinks : data.knowledgeLinks;
  const graphOption: EChartsCoreOption = { ...base, tooltip: { trigger: 'item' }, legend: [{ bottom: 0, textStyle: { color: theme.muted }, data: graphMode === 'structure' ? ['书籍', '章节', '关键词'] : ['知识库', '作者', '书籍', '概念'] }], series: [{ type: 'graph', layout: 'force', roam: true, draggable: true, data: graphData, links: graphLinks, categories: (graphMode === 'structure' ? ['书籍', '章节', '关键词'] : ['知识库', '作者', '书籍', '概念']).map((name) => ({ name })), label: { show: true, color: theme.text, fontSize: 10 }, lineStyle: { color: 'source', opacity: 0.4, curveness: 0.06 }, emphasis: { focus: 'adjacency' }, force: { repulsion: 210, edgeLength: [65, 150], gravity: 0.07 } }] };
  const communityOption: EChartsCoreOption = { ...base, tooltip: { trigger: 'item' }, legend: { bottom: 0, textStyle: { color: theme.muted }, data: data.communities.slice(0, 6).map((_, index) => `社区 ${index + 1}`) }, series: [{ type: 'graph', layout: 'force', roam: true, data: [...data.communityByWord.entries()].map(([word, category]) => ({ name: word, category: Math.min(category, 5), symbolSize: 11 + Math.sqrt(data.wordCount.get(word) || 1) * 2 })), links: data.pairLinks.map(([key, value]) => { const [source, target] = key.split('\u0000'); return { source, target, value }; }), categories: data.communities.slice(0, 6).map((_, index) => ({ name: `社区 ${index + 1}` })), label: { show: true, color: theme.text }, lineStyle: { color: 'source', opacity: 0.35 }, emphasis: { focus: 'adjacency' }, force: { repulsion: 150, edgeLength: [55, 130] } }] };
  const crossOption: EChartsCoreOption = { ...base, tooltip: { trigger: 'axis' }, grid: { left: 85, right: 25, top: 15, bottom: 30 }, yAxis: { ...axis, type: 'category', inverse: true, data: data.crossBook.map((item) => item.word) }, xAxis: { ...axis, type: 'value', minInterval: 1, name: '涉及书籍数', nameTextStyle: { color: theme.muted } }, series: [{ type: 'bar', data: data.crossBook.map((item) => item.books), itemStyle: { color: theme.colors[0], borderRadius: [0, 4, 4, 0] } }] };
  const authorOption: EChartsCoreOption = { ...base, tooltip: { formatter: (params: unknown) => { const value = (params as { value?: [number, number, number] }).value; return value ? `${data.authors[value[1]]} × ${data.authors[value[0]]}<br/>主题相似度 ${value[2]}%` : ''; } }, grid: { left: 105, right: 25, top: 20, bottom: 100 }, xAxis: { ...axis, type: 'category', data: data.authors, axisLabel: { color: theme.muted, rotate: 35 } }, yAxis: { ...axis, type: 'category', data: data.authors }, visualMap: { min: 0, max: 100, orient: 'horizontal', left: 'center', bottom: 5, textStyle: { color: theme.muted }, inRange: { color: [theme.primaryLight, theme.colors[0], theme.primaryStrong] } }, series: [{ type: 'heatmap', data: data.authorMatrix, label: { show: true, color: theme.text } }] };
  const tabs = [['relations', '关系图谱'], ['concepts', '概念社区'], ['authors', '作者相似度'], ['wander', '笔记漫游']] as const;

  return <div className="space-y-4"><div className="flex items-center gap-2"><div className="mr-auto"><h2 className="text-lg font-semibold">知识网络</h2><p className="mt-1 text-sm text-muted-foreground">从书籍、章节、作者、概念和笔记之间建立可探索关系。</p></div>{tabs.map(([id, label]) => <button key={id} onClick={() => setView(id)} className={`rounded px-3 py-1.5 text-sm ${view === id ? 'bg-primary text-primary-foreground' : 'border hover:bg-accent'}`}>{label}</button>)}</div>
    {view === 'relations' && <><section className="rounded-lg border bg-card p-3"><div className="flex items-center justify-between px-2"><h3 className="text-sm font-medium">{graphMode === 'structure' ? '书籍—章节—关键词关系图' : '阅读知识图谱'}</h3><div className="flex gap-1"><button onClick={() => setGraphMode('structure')} className={`rounded px-2 py-1 text-xs ${graphMode === 'structure' ? 'bg-primary text-primary-foreground' : 'border'}`}>章节结构</button><button onClick={() => setGraphMode('knowledge')} className={`rounded px-2 py-1 text-xs ${graphMode === 'knowledge' ? 'bg-primary text-primary-foreground' : 'border'}`}>完整知识图谱</button></div></div><Chart option={graphOption} height={650} /></section></>}
    {view === 'concepts' && <><div className="grid gap-4 xl:grid-cols-2"><section className="rounded-lg border bg-card p-3"><h3 className="px-2 text-sm font-medium">跨书共同概念</h3><Chart option={crossOption} height={470} /></section><section className="rounded-lg border bg-card p-4"><h3 className="text-sm font-medium">核心概念及邻接概念</h3><div className="mt-3 space-y-2">{data.coreConcepts.slice(0, 10).map((item) => <div key={item.word} className="rounded border bg-background p-2"><span className="font-medium text-primary">{item.word}</span><span className="ml-2 text-xs text-muted-foreground">{item.degree} 个邻接概念 · 出现 {item.count} 次</span><p className="mt-1 truncate text-xs text-muted-foreground">{[...(data.adjacency.get(item.word) || [])].slice(0, 8).join('、') || '暂无稳定邻接概念'}</p></div>)}</div></section></div><section className="rounded-lg border bg-card p-3"><h3 className="px-2 text-sm font-medium">概念社区聚类</h3><Chart option={communityOption} height={600} /></section><section className="rounded-lg border bg-card p-4"><h3 className="text-sm font-medium">孤立主题和知识盲区</h3><p className="mt-1 text-xs text-muted-foreground">只在一本书出现、且尚未形成稳定共现关系的主题。</p><div className="mt-3 flex flex-wrap gap-2">{data.isolated.map((word) => <span key={word} className="rounded-full border bg-background px-2.5 py-1 text-xs">{word}</span>)}{!data.isolated.length && <span className="text-sm text-muted-foreground">暂无明显孤立主题</span>}</div></section></>}
    {view === 'authors' && <section className="rounded-lg border bg-card p-3"><h3 className="px-2 text-sm font-medium">作者之间的主题相似度</h3><p className="px-2 pt-1 text-xs text-muted-foreground">根据作者相关书籍中的概念向量计算。</p><Chart option={authorOption} height={620} /></section>}
    {view === 'wander' && <section className="rounded-lg border bg-card p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-medium">从一条笔记向相关笔记漫游</h3><p className="mt-1 text-xs text-muted-foreground">使用概念集合的 Jaccard 相似度在不同书籍之间发现关联。</p></div><button onClick={() => setSelectedNoteId(data.notes[Math.floor(Math.random() * Math.max(1, data.notes.length))]?.id || '')} className="rounded border px-3 py-1.5 text-sm hover:bg-accent">随机漫游</button></div>{selectedNote && <div className="mt-4 rounded-lg border-l-4 border-primary bg-primary/5 p-4"><p className="text-xs text-muted-foreground">{selectedNote.book} · {selectedNote.chapter}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{selectedNote.text}</p><button onClick={() => onSelectBook(selectedNote.bookId)} className="mt-2 text-xs text-primary hover:underline">打开本书笔记</button></div>}<div className="mt-4 grid gap-2 md:grid-cols-2">{related.map(({ note, score }) => <button key={note.id} onClick={() => setSelectedNoteId(note.id)} className="rounded-md border bg-background p-3 text-left hover:bg-accent"><div className="flex justify-between gap-2"><p className="truncate text-sm font-medium">{note.book}</p><span className="shrink-0 text-xs text-primary">相似 {Math.round(score * 100)}%</span></div><p className="mt-1 line-clamp-3 text-xs leading-5 text-muted-foreground">{note.text}</p></button>)}{!related.length && <p className="col-span-full py-10 text-center text-sm text-muted-foreground">没有找到包含共同概念的相关笔记</p>}</div></section>}
  </div>;
};
