import React from "react";
import { checkQuoteAgainstSource, type SourceLevel, type SupportStrength } from "../../core/editorial-analysis";

interface ClaimRecord { id: string; text: string; evidenceIds: string[]; evidenceStrengths?: Record<string, SupportStrength> }
interface EvidenceRecord { id: string; title: string; url: string; source: string; chapter: string; status: "clue" | "verified" | "disputed"; notes: string; sourceLevel?: SourceLevel; sourceExcerpt?: string; bibliographic?: string; accessedAt?: number; anchor?: { quote: string }; createdAt: number }

export interface EvidenceAuditViewProps {
  claims: ClaimRecord[];
  evidenceRecords: EvidenceRecord[];
  setEvidenceRecords: React.Dispatch<React.SetStateAction<EvidenceRecord[]>>;
  updateClaimStrengths: (id: string, strengths: Record<string, SupportStrength>) => void;
}

export function EvidenceAuditView(p: EvidenceAuditViewProps) {
  const updateEvidence = (id: string, patch: Partial<EvidenceRecord>) => p.setEvidenceRecords((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item));
  return <>
    <div className="mx-auto mb-4 max-w-6xl rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">主张支持强度</h3><p className="text-xs text-muted-foreground">逐条判断来源是直接、间接、背景支持，还是不足或相反。</p><div className="mt-3 max-h-72 space-y-2 overflow-auto">{p.claims.flatMap((claim) => claim.evidenceIds.map((evidenceId) => { const evidence = p.evidenceRecords.find((item) => item.id === evidenceId); return <div key={`${claim.id}-${evidenceId}`} className="grid gap-2 rounded border border-border p-2 md:grid-cols-[1fr_220px]"><div className="min-w-0 text-xs"><div className="truncate font-medium">{claim.text}</div><div className="truncate text-muted-foreground">{evidence?.title ?? "证据已删除"}</div></div><select value={claim.evidenceStrengths?.[evidenceId] ?? "indirect"} onChange={(event) => p.updateClaimStrengths(claim.id, { ...(claim.evidenceStrengths ?? {}), [evidenceId]: event.target.value as SupportStrength })} className="rounded border border-input bg-background p-2 text-xs"><option value="direct">直接支持</option><option value="indirect">间接支持</option><option value="contextual">背景支持</option><option value="insufficient">支持不足</option><option value="contradictory">证据相反</option></select></div>; }))}</div></div>
    <div className="mx-auto mb-4 max-w-6xl space-y-3">{p.evidenceRecords.map((item) => { const result = item.anchor?.quote && item.sourceExcerpt ? checkQuoteAgainstSource(item.anchor.quote, item.sourceExcerpt) : null; return <section key={`source-${item.id}`} className="rounded-xl border border-border bg-card p-4"><div className="flex justify-between gap-3 text-sm font-medium"><span className="truncate">{item.title}</span><span className={result?.exact ? "text-emerald-600" : "text-amber-700"}>{result ? `${result.message} ${Math.round(result.similarity * 100)}%` : "待核对原文"}</span></div><div className="mt-3 grid gap-3 md:grid-cols-2"><select value={item.sourceLevel ?? "search-clue"} onChange={(event) => updateEvidence(item.id, { sourceLevel: event.target.value as SourceLevel })} className="rounded border border-input bg-background p-2 text-xs"><option value="primary">一手史料</option><option value="near-contemporary">近同时代材料</option><option value="later-history">后出史书</option><option value="archaeology">考古材料</option><option value="modern-research">现代研究</option><option value="search-clue">检索线索</option></select><input value={item.bibliographic ?? ""} onChange={(event) => updateEvidence(item.id, { bibliographic: event.target.value })} placeholder="作者、书名/篇名、版本、页码" className="rounded border border-input bg-background p-2 text-xs" /><textarea value={item.anchor?.quote ?? ""} onChange={(event) => updateEvidence(item.id, { anchor: { quote: event.target.value } })} placeholder="正文引文" className="min-h-16 rounded border border-input bg-background p-2 text-xs" /><textarea value={item.sourceExcerpt ?? ""} onChange={(event) => updateEvidence(item.id, { sourceExcerpt: event.target.value, accessedAt: Date.now() })} placeholder="来源原文摘录" className="min-h-16 rounded border border-input bg-background p-2 text-xs" /></div></section>; })}</div>
  </>;
}
