import React from "react";
export type EvidenceStatus = "clue" | "verified" | "disputed";
export interface EvidenceItemView { id: string; title: string; url: string; source: string; chapter: string; status: EvidenceStatus; notes: string; createdAt: number }
export interface EvidenceViewProps { entries: EvidenceItemView[]; setEntries(updater: (current: EvidenceItemView[]) => EvidenceItemView[]): void; openExternal(url: string): void }

export function EvidenceView(p: EvidenceViewProps) {
  const patch = (id: string, value: Partial<EvidenceItemView>) => p.setEntries((items) => items.map((item) => item.id === id ? { ...item, ...value } : item));
  return <div className="mx-auto max-w-6xl space-y-4"><div><h2 className="text-lg font-semibold">史料证据台账</h2><p className="text-sm text-muted-foreground">搜索结果先作为线索，核对原文后再标记为已核实。</p></div><div className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr><th className="px-4 py-2">来源</th><th className="px-4 py-2">关联章节</th><th className="px-4 py-2">状态</th><th className="px-4 py-2">备注</th><th /></tr></thead><tbody>{p.entries.map((item) => <tr key={item.id} className="border-t border-border"><td className="max-w-[360px] px-4 py-3"><button type="button" className="block max-w-full truncate text-primary hover:underline" title={item.title} onClick={() => p.openExternal(item.url)}>{item.title}</button><span className="text-xs text-muted-foreground">{item.source}</span></td><td className="max-w-[240px] truncate px-4 py-3" title={item.chapter}>{item.chapter.split("/").pop() || "未关联"}</td><td className="px-4 py-3"><select value={item.status} onChange={(event) => patch(item.id, { status: event.target.value as EvidenceStatus })} className="rounded border border-input bg-background px-2 py-1"><option value="clue">检索线索</option><option value="verified">已核实</option><option value="disputed">存在争议</option></select></td><td className="px-4 py-3"><input value={item.notes} onChange={(event) => patch(item.id, { notes: event.target.value })} className="w-full rounded border border-input bg-background px-2 py-1" /></td><td className="px-4 py-3"><button type="button" className="text-muted-foreground hover:text-destructive" onClick={() => p.setEntries((items) => items.filter((entry) => entry.id !== item.id))}>删除</button></td></tr>)}</tbody></table>{!p.entries.length && <div className="p-12 text-center text-muted-foreground">暂无证据记录，请从 AI 史料搜索中选择来源。</div>}</div></div>;
}
