import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Download, Loader2, Plus, Sparkles, Trash2 } from '@/components/icons';
import { Button } from '@/components/ui/button';
import { createOpenAIProvider, type ChatMessage } from '@/core/llm';
import { analyzeLines, detectRhyme } from './analysis';
import { LYRIC_SYSTEM_PROMPT } from './prompt';
import { analyzeAudioFile, exportLrc, exportMidi } from './music-tools';
import type { AudioAnalysis, HookCandidate, LrcLine, LyricProject, LyricSection, MelodyNote, ReviewIssue } from './types';

type ToolTab = 'hook' | 'review' | 'imagery' | 'rhyme' | 'rhythm' | 'audio' | 'lrc' | 'melody';
const TOOL_GROUPS: Array<[string, Array<[ToolTab, string]>]> = [
  ['创作', [['hook', 'Hook 候选'], ['imagery', '意象链']]],
  ['分析', [['review', '歌词审稿'], ['rhyme', '押韵热力图'], ['rhythm', '节奏网格']]],
  ['音乐', [['audio', '音频分析'], ['lrc', 'LRC 打轴'], ['melody', '旋律 / MIDI']]],
];
const TABS = TOOL_GROUPS.flatMap(([, tools]) => tools);
const RHYME_COLORS = ['bg-rose-500/15 text-rose-700', 'bg-blue-500/15 text-blue-700', 'bg-emerald-500/15 text-emerald-700', 'bg-amber-500/15 text-amber-700', 'bg-violet-500/15 text-violet-700'];

interface Props {
  project: LyricProject;
  aiApi: { apiKey: string; baseUrl: string; model: string };
  onPatchProject: (patch: Partial<LyricProject>) => void;
  onPatchSection: (id: string, patch: Partial<LyricSection>) => void;
  onClose: () => void;
}

function extractJson(raw: string): any { const clean = raw.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1] ?? raw; return JSON.parse(clean.slice(clean.indexOf('{'), clean.lastIndexOf('}') + 1)); }
async function askJson(aiApi: Props['aiApi'], system: string, user: string): Promise<any> {
  if (!aiApi.apiKey || !aiApi.baseUrl || !aiApi.model) throw new Error('请先在设置中配置 AI 服务');
  const provider = createOpenAIProvider({ apiKey: aiApi.apiKey, baseUrl: aiApi.baseUrl }); let raw = '';
  const messages: ChatMessage[] = [{ role: 'system', content: system }, { role: 'user', content: user }];
  for await (const chunk of provider.chat(messages, { model: aiApi.model, temperature: 0.75, maxTokens: 1800, stream: true })) raw += chunk.delta ?? '';
  return extractJson(raw);
}

export const LyricToolbox: React.FC<Props> = ({ project, aiApi, onPatchProject, onPatchSection, onClose }) => {
  const [tab, setTab] = useState<ToolTab>('hook'); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  const [hooks, setHooks] = useState<HookCandidate[]>([]); const [issues, setIssues] = useState<ReviewIssue[]>([]); const [imagery, setImagery] = useState(project.coreImages);
  const [audio, setAudio] = useState<AudioAnalysis | null>(null); const [audioUrl, setAudioUrl] = useState(''); const audioRef = useRef<HTMLAudioElement>(null);
  const [audioLoop, setAudioLoop] = useState(false);
  const [lrc, setLrc] = useState<LrcLine[]>([]); const [melody, setMelody] = useState<MelodyNote[]>([]);
  const allLines = useMemo(() => project.sections.flatMap((section) => section.lyrics.split(/\r?\n/).filter(Boolean).map((line) => ({ section, line, rhyme: detectRhyme(line) }))), [project.sections]);
  const rhymeColors = useMemo(() => { const map = new Map<string, string>(); allLines.forEach(({ rhyme }) => { if (!map.has(rhyme)) map.set(rhyme, RHYME_COLORS[map.size % RHYME_COLORS.length]); }); return map; }, [allLines]);
  useEffect(() => () => { if (audioUrl) URL.revokeObjectURL(audioUrl); }, [audioUrl]);

  const run = async (task: () => Promise<void>) => { setLoading(true); setMessage(''); try { await task(); } catch (error) { setMessage(error instanceof Error ? error.message : '操作失败'); } finally { setLoading(false); } };
  const generateHooks = () => run(async () => { const parsed = await askJson(aiApi, `${LYRIC_SYSTEM_PROMPT}\n只输出 {"hooks":[{"text":"两到四行","memorability":85,"singability":88,"imagery":80}]}，生成 5 个完全不同的副歌 Hook。`, `主题：${project.theme}\n故事：${project.story}\n意象：${project.coreImages.join('、')}\n情绪：${project.emotion}`); setHooks((parsed.hooks ?? []).slice(0, 5).map((item: any) => ({ id: crypto.randomUUID(), text: String(item.text || ''), memorability: Number(item.memorability || 0), singability: Number(item.singability || 0), imagery: Number(item.imagery || 0) }))); });
  const review = () => run(async () => { const parsed = await askJson(aiApi, '你是严格的华语歌词审稿编辑。只输出 {"issues":[{"sectionTitle":"","line":"","category":"陈词滥调/意象堆砌/人称/时间线/故事/押韵/可唱性/Hook/原创性","severity":"info|warning|critical","suggestion":""}]}。不要声称完成互联网查重。', project.sections.map((s) => `[${s.title}]\n${s.lyrics}`).join('\n\n')); setIssues((parsed.issues ?? []).map((item: any) => ({ ...item, id: crypto.randomUUID() }))); });
  const generateMelody = () => run(async () => { const chorus = project.sections.find((section) => section.kind === 'Chorus'); const parsed = await askJson(aiApi, '你是旋律写作助手。只输出 {"notes":[{"pitch":60,"beats":1,"lyric":"字或词"}]}。pitch 使用 MIDI 48-76，给出易唱的单声部旋律草案。', `BPM：${project.bpm}\n情绪：${project.emotion}\n歌词：\n${chorus?.lyrics || project.sections[0]?.lyrics}`); setMelody((parsed.notes ?? []).map((item: any) => ({ pitch: Number(item.pitch), beats: Number(item.beats), lyric: String(item.lyric || '') }))); });
  const insertHook = (hook: HookCandidate) => { const chorus = project.sections.find((section) => section.kind === 'Chorus'); if (chorus) onPatchSection(chorus.id, { lyrics: hook.text }); else setMessage('请先添加 Chorus 段落'); };
  const loadAudio = async (file?: File) => { if (!file) return; await run(async () => { const result = await analyzeAudioFile(file); if (audioUrl) URL.revokeObjectURL(audioUrl); setAudioUrl(URL.createObjectURL(file)); setAudio(result.analysis); onPatchProject({ bpm: result.analysis.bpm }); }); };
  const prepareLrc = () => setLrc(allLines.map(({ line }) => ({ id: crypto.randomUUID(), time: 0, text: line })));
  const tapLine = (index: number) => { const time = audioRef.current?.currentTime ?? 0; const beat = 60 / Math.max(40, project.bpm); const snapped = Math.round(time / beat) * beat; setLrc((current) => current.map((line, i) => i === index ? { ...line, time: snapped } : line)); };

  return <div className="absolute inset-0 z-[60] flex items-center justify-center bg-black/45 p-6" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div role="dialog" aria-modal="true" className="flex h-[88%] w-[92%] max-w-[1180px] flex-col overflow-hidden rounded-2xl border bg-background shadow-2xl"><header className="flex h-14 shrink-0 items-center border-b px-5"><div><h2 className="text-sm font-semibold">创作工具箱</h2><p className="text-[10px] text-muted-foreground">{project.title}</p></div><Button className="ml-auto" variant="outline" size="sm" onClick={onClose}>关闭</Button></header><div className="flex min-h-0 flex-1"><nav className="w-40 shrink-0 space-y-1 border-r bg-muted/20 p-2">{TABS.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`w-full rounded-md px-3 py-2 text-left text-xs ${tab === id ? 'bg-violet-500/15 text-violet-700' : 'hover:bg-accent'}`}>{label}</button>)}</nav><main className="min-h-0 flex-1 overflow-auto p-6">
    {message && <p className="mb-4 rounded-md border border-amber-500/30 bg-amber-500/10 p-2 text-xs text-amber-700">{message}</p>}
    {tab === 'hook' && <Tool title="Hook 工作台" action={<Button disabled={loading} onClick={() => void generateHooks()}>{loading ? <Loader2 className="mr-1" /> : <Sparkles className="mr-1" />}生成 5 个 Hook</Button>}>{hooks.length ? <div className="grid gap-3 md:grid-cols-2">{hooks.map((hook) => <article key={hook.id} className="rounded-xl border bg-card p-4"><pre className="whitespace-pre-wrap font-serif text-base leading-7">{hook.text}</pre><div className="my-3 flex gap-3 text-[10px] text-muted-foreground"><span>记忆 {hook.memorability}</span><span>可唱 {hook.singability}</span><span>画面 {hook.imagery}</span></div><Button size="sm" variant="outline" onClick={() => insertHook(hook)}>插入 Chorus</Button></article>)}</div> : <Empty text="生成多个副歌核心句并进行比较" />}</Tool>}
    {tab === 'review' && <Tool title="歌词审稿 Agent" action={<Button disabled={loading} onClick={() => void review()}>{loading ? <Loader2 className="mr-1" /> : <Sparkles className="mr-1" />}开始审稿</Button>}>{issues.length ? <div className="space-y-2">{issues.map((issue) => <article key={issue.id} className="rounded-lg border p-3"><div className="flex gap-2 text-xs font-medium"><span className={issue.severity === 'critical' ? 'text-red-600' : issue.severity === 'warning' ? 'text-amber-600' : 'text-blue-600'}>{issue.category}</span><span>{issue.sectionTitle}</span></div><p className="my-1 text-sm">{issue.line}</p><p className="text-xs text-muted-foreground">{issue.suggestion}</p></article>)}</div> : <Empty text="检查叙事、意象、押韵、可唱性和原创风险" />}</Tool>}
    {tab === 'imagery' && <Tool title="意象链编辑器" action={<Button onClick={() => { onPatchProject({ coreImages: imagery }); setMessage('意象链已写回创作规划卡'); }}>写回项目</Button>}><div className="flex flex-wrap items-center gap-2">{imagery.map((item, index) => <React.Fragment key={`${item}-${index}`}><div className="flex items-center rounded-full border bg-card"><input value={item} onChange={(event) => setImagery((current) => current.map((value, i) => i === index ? event.target.value : value))} className="w-28 bg-transparent px-3 py-2 text-xs outline-none" /><button onClick={() => setImagery((current) => current.filter((_, i) => i !== index))} className="pr-2 text-muted-foreground"><Trash2 className="h-3 w-3" /></button></div>{index < imagery.length - 1 && <span className="text-muted-foreground">→</span>}</React.Fragment>)}<button onClick={() => setImagery((current) => [...current, '新意象'])} className="rounded-full border p-2"><Plus className="h-3 w-3" /></button></div></Tool>}
    {tab === 'rhyme' && <Tool title="押韵热力图"><div className="space-y-4">{project.sections.map((section) => <section key={section.id}><h3 className="mb-2 text-xs font-semibold">{section.title}</h3><div className="space-y-1">{section.lyrics.split(/\r?\n/).filter(Boolean).map((line, index) => { const rhyme = detectRhyme(line); return <div key={`${line}-${index}`} className={`flex items-center rounded px-3 py-2 text-xs ${rhymeColors.get(rhyme)}`}><span className="w-7 opacity-60">{index + 1}</span><span className="flex-1">{line}</span><span className="font-mono">{rhyme}</span></div>; })}</div></section>)}</div></Tool>}
    {tab === 'rhythm' && <Tool title="专业节奏网格"><div className="space-y-5">{project.sections.map((section) => <section key={section.id}><h3 className="mb-2 text-xs font-semibold">{section.title}</h3>{analyzeLines(section.lyrics, project.bpm).map((line, index) => <div key={`${line.line}-${index}`} className="mb-1 grid grid-cols-[28px_1fr_60px_70px_120px] items-center rounded border px-3 py-2 text-xs"><span>{index + 1}</span><span>{line.line}</span><span>{line.hanCount} 字</span><span>{line.durationSeconds}s</span><span className="text-muted-foreground">{line.breathing}</span></div>)}</section>)}</div></Tool>}
    {tab === 'audio' && <Tool title="伴奏与音频分析"><input type="file" accept="audio/mp3,audio/wav,audio/mpeg,audio/x-wav" onChange={(event) => void loadAudio(event.target.files?.[0])} className="mb-4 block text-xs" />{audioUrl && <div className="flex items-center gap-3"><audio ref={audioRef} src={audioUrl} controls loop={audioLoop} className="flex-1" /><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={audioLoop} onChange={(event) => setAudioLoop(event.target.checked)} />循环</label></div>}{audio && <><div className="mt-4 flex h-28 items-center gap-px overflow-hidden rounded-lg border bg-muted/20 px-2">{audio.waveform.map((value, index) => <span key={index} className="min-w-px flex-1 rounded-full bg-violet-500/70" style={{ height: `${Math.max(2, value * 100)}%` }} />)}</div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{[['文件', audio.name], ['时长', `${audio.duration.toFixed(1)} 秒`], ['估算 BPM', audio.bpm], ['估算调性', audio.key], ['段落容量', `≈ ${Math.round(audio.duration / Math.max(1, project.sections.length) * project.bpm / 60 * 2)} 字/段`]].map(([label, value]) => <div key={label} className="rounded-lg border p-3"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 truncate text-sm font-medium">{value}</p></div>)}</div></>}</Tool>}
    {tab === 'lrc' && <Tool title="LRC 打轴" action={<div className="flex gap-2"><Button variant="outline" onClick={prepareLrc}>载入全部歌词</Button><Button disabled={!lrc.length} onClick={() => exportLrc(project.title, lrc)}><Download className="mr-1" />导出 LRC</Button></div>}>{audioUrl ? <audio ref={audioRef} src={audioUrl} controls className="mb-4 w-full" /> : <p className="mb-4 text-xs text-muted-foreground">请先在“音频分析”中载入伴奏。</p>}<div className="space-y-1">{lrc.map((line, index) => <button key={line.id} onClick={() => tapLine(index)} className="grid w-full grid-cols-[70px_1fr] rounded border px-3 py-2 text-left text-xs hover:bg-accent"><span className="font-mono">{line.time.toFixed(2)}s</span><span>{line.text}</span></button>)}</div></Tool>}
    {tab === 'melody' && <Tool title="旋律辅助与 MIDI" action={<div className="flex gap-2"><Button disabled={loading} onClick={() => void generateMelody()}><Sparkles className="mr-1" />生成旋律</Button><Button variant="outline" disabled={!melody.length} onClick={() => exportMidi(project.title, melody, project.bpm)}><Download className="mr-1" />导出 MIDI</Button></div>}><p className="mb-3 text-xs text-muted-foreground">建议和弦：{project.emotion.includes('遗憾') || project.emotion.includes('悲') ? 'Am – F – C – G' : 'C – G – Am – F'} · 建议音域 C3–C5</p>{melody.length ? <div className="flex min-h-44 items-end gap-1 rounded-xl border bg-card p-4">{melody.map((note, index) => <div key={index} className="flex min-w-8 flex-col items-center gap-1"><span className="text-[9px]">{note.pitch}</span><div className="w-full rounded-t bg-violet-500/70" style={{ height: `${Math.max(20, (note.pitch - 40) * 4)}px` }} /><span className="max-w-12 truncate text-[10px]">{note.lyric}</span></div>)}</div> : <Empty text="为副歌生成可编辑的单声部旋律草案" />}</Tool>}
  </main></div></div></div>;
};

const Tool: React.FC<{ title: string; action?: React.ReactNode; children: React.ReactNode }> = ({ title, action, children }) => <section><header className="mb-5 flex items-center"><h2 className="text-base font-semibold">{title}</h2><div className="ml-auto">{action}</div></header>{children}</section>;
const Empty: React.FC<{ text: string }> = ({ text }) => <div className="grid min-h-52 place-items-center rounded-xl border border-dashed text-sm text-muted-foreground">{text}</div>;
