/**
 * Application icon gateway.
 *
 * General-purpose UI icons come from Lucide so stroke, sizing, and optical
 * weight stay consistent. Components should import from this module instead
 * of reaching into an icon package directly.
 */

import type { ComponentProps } from 'react';
import {
  ArrowLeft,
  ArrowRight,
  Blocks,
  BookOpen,
  Bot,
  Calendar,
  Check,
  ChevronDown,
  CircleCheck,
  CircleX,
  Clipboard,
  Code,
  Copy,
  Database,
  Download,
  Edit3,
  Ellipsis,
  Eye,
  EyeOff,
  ExternalLink,
  FileChartColumn,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  GitBranch,
  Globe,
  History,
  Info,
  LoaderCircle,
  Maximize2,
  Menu,
  Minus,
  MessageSquare,
  Monitor,
  Moon,
  Network,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  Presentation,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShieldAlert,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Trash2,
  Upload,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

type LoaderProps = ComponentProps<typeof LoaderCircle>;

/** Loading indicators rotate by default throughout the application. */
function Loader2({ className, ...props }: LoaderProps) {
  return (
    <LoaderCircle
      aria-hidden="true"
      className={`animate-spin ${className ?? ''}`}
      {...props}
    />
  );
}

export {
  ArrowLeft,
  ArrowRight,
  Blocks,
  BookOpen,
  Bot,
  Calendar,
  Check,
  CircleCheck as CheckCircle,
  ChevronDown,
  Clipboard as StickyNote,
  Code,
  Copy,
  Database,
  Download,
  Edit3,
  Ellipsis,
  Eye,
  EyeOff,
  ExternalLink,
  FileChartColumn as Pdf,
  FileSpreadsheet as Excel,
  FileText,
  FileText as Word,
  FolderOpen,
  GitBranch,
  Globe,
  History,
  Info,
  Loader2,
  Maximize2,
  Menu,
  Minus,
  MessageSquare,
  Monitor,
  Moon,
  Network,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pencil as Draw,
  Pin,
  Plus,
  Presentation as Ppt,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShieldAlert,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Trash2,
  Upload,
  Wrench,
  X,
  CircleX as XCircle,
  ZoomIn,
  ZoomOut,
  Bot as Robot,
};
