import React, { cloneElement, useCallback, useEffect, useRef, useState } from 'react';
import { Camera, FileText, Mic, Paperclip, Phone, PhoneOff, Send, Users, Video, X } from '@/components/icons';
import type { PhoneCallKind, PhoneEvent, PhoneMessage, PhoneState } from './types';
import { mergeMessages } from './domain';

type CallState = 'idle' | 'inviting' | 'ringing' | 'connecting' | 'connected';

export function PhonePanel(): JSX.Element {
  const [state, setState] = useState<PhoneState>(); const [selectedId, setSelectedId] = useState<string>(); const [messages, setMessages] = useState<PhoneMessage[]>([]); const [text, setText] = useState(''); const [error, setError] = useState('');
  const [callState, setCallState] = useState<CallState>('idle'); const [callId, setCallId] = useState<string>(); const [callKind, setCallKind] = useState<PhoneCallKind>('audio'); const [incoming, setIncoming] = useState<{ callId: string; peerId: string; kind: PhoneCallKind }>(); const [muted, setMuted] = useState(false); const [cameraOff, setCameraOff] = useState(false);
  const pcRef = useRef<RTCPeerConnection>(); const localStreamRef = useRef<MediaStream>(); const remoteVideoRef = useRef<HTMLVideoElement>(null); const localVideoRef = useRef<HTMLVideoElement>(null); const pendingIce = useRef<RTCIceCandidateInit[]>([]); const selectedRef = useRef<string>();
  const peer = state?.peers.find((item) => item.id === selectedId); selectedRef.current = selectedId;

  const refresh = useCallback(async () => setState(await window.electronAPI.phone.start()), []);
  const loadMessages = useCallback(async (peerId: string) => { const items = await window.electronAPI.phone.listMessages(peerId); setMessages(items); const unread = items.filter((item) => item.recipientId === (state?.deviceId ?? '') && item.status !== 'read').map((item) => item.id); if (unread.length) await window.electronAPI.phone.markRead(peerId, unread); }, [state?.deviceId]);
  const endCall = useCallback((notify = true) => { if (notify && callId && selectedRef.current) void window.electronAPI.phone.sendSignal(selectedRef.current, { type: 'call.hangup', callId, peerId: selectedRef.current }); pcRef.current?.close(); pcRef.current = undefined; for (const track of localStreamRef.current?.getTracks() ?? []) track.stop(); localStreamRef.current = undefined; if (remoteVideoRef.current) remoteVideoRef.current.srcObject = null; if (localVideoRef.current) localVideoRef.current.srcObject = null; pendingIce.current = []; setCallState('idle'); setCallId(undefined); setIncoming(undefined); setMuted(false); setCameraOff(false); }, [callId]);

  const createPeerConnection = useCallback((peerId: string, activeCallId: string) => { const pc = new RTCPeerConnection({ iceServers: [] }); pc.onicecandidate = (event) => { if (event.candidate) void window.electronAPI.phone.sendSignal(peerId, { type: 'webrtc.ice', callId: activeCallId, peerId, candidate: event.candidate.toJSON() }); }; pc.ontrack = (event) => { if (remoteVideoRef.current) remoteVideoRef.current.srcObject = event.streams[0]; }; pc.onconnectionstatechange = () => { if (pc.connectionState === 'connected') setCallState('connected'); if (['failed','closed'].includes(pc.connectionState)) endCall(false); }; pcRef.current = pc; return pc; }, [endCall]);
  const acquireMedia = useCallback(async (kind: PhoneCallKind) => { const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: kind === 'video' }); localStreamRef.current = stream; if (localVideoRef.current) localVideoRef.current.srcObject = stream; return stream; }, []);
  const makeOffer = useCallback(async (peerId: string, activeCallId: string, kind: PhoneCallKind) => { const pc = createPeerConnection(peerId, activeCallId); const stream = await acquireMedia(kind); for (const track of stream.getTracks()) pc.addTrack(track, stream); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); await window.electronAPI.phone.sendSignal(peerId, { type: 'webrtc.offer', callId: activeCallId, peerId, sdp: offer.sdp ?? '' }); }, [acquireMedia, createPeerConnection]);

  useEffect(() => { void refresh().catch((e: Error) => setError(e.message)); return window.electronAPI.phone.onEvent((event: PhoneEvent) => {
    if (event.type === 'state') setState(event.state); else if (event.type === 'peer.updated') setState((value) => value ? { ...value, peers: [...value.peers.filter((item) => item.id !== event.peer.id), event.peer] } : value); else if (event.type === 'pair.request') { if (window.confirm(`${event.peer.name} 请求与本机配对，是否接受？\n指纹：${event.peer.fingerprint}`)) void window.electronAPI.phone.respondPairing(event.requestId, event.peer.id, true); else void window.electronAPI.phone.respondPairing(event.requestId, event.peer.id, false); } else if (event.type === 'pair.result') void refresh(); else if (event.type === 'message' && event.message.peerId === selectedRef.current) setMessages((items) => mergeMessages(items, [event.message])); else if (event.type === 'message.status') setMessages((items) => items.map((item) => item.id === event.messageId ? { ...item, status: event.status } : item)); else if (event.type === 'call.invite') { if (callState !== 'idle') void window.electronAPI.phone.sendSignal(event.peerId, { type: 'call.busy', callId: event.callId, peerId: event.peerId }); else { setSelectedId(event.peerId); setIncoming({ callId: event.callId, peerId: event.peerId, kind: event.kind }); setCallId(event.callId); setCallKind(event.kind); setCallState('ringing'); void window.electronAPI.phone.sendSignal(event.peerId, { type: 'call.ringing', callId: event.callId, peerId: event.peerId }); } } else if (event.type === 'call.accept') { setCallState('connecting'); void makeOffer(event.peerId, event.callId, callKind); } else if (['call.reject','call.cancel','call.busy','call.hangup'].includes(event.type)) endCall(false); else if (event.type === 'webrtc.offer') { void (async () => { const pc = pcRef.current ?? createPeerConnection(event.peerId, event.callId); if (!localStreamRef.current) { const stream = await acquireMedia(callKind); for (const track of stream.getTracks()) pc.addTrack(track, stream); } await pc.setRemoteDescription({ type: 'offer', sdp: event.sdp }); for (const candidate of pendingIce.current.splice(0)) await pc.addIceCandidate(candidate); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); await window.electronAPI.phone.sendSignal(event.peerId, { type: 'webrtc.answer', callId: event.callId, peerId: event.peerId, sdp: answer.sdp ?? '' }); })(); } else if (event.type === 'webrtc.answer') void (async () => { await pcRef.current?.setRemoteDescription({ type: 'answer', sdp: event.sdp }); for (const candidate of pendingIce.current.splice(0)) await pcRef.current?.addIceCandidate(candidate); })(); else if (event.type === 'webrtc.ice') { if (pcRef.current?.remoteDescription) void pcRef.current.addIceCandidate(event.candidate); else pendingIce.current.push(event.candidate); }
  }); }, [acquireMedia, callKind, callState, createPeerConnection, endCall, makeOffer, refresh]);
  useEffect(() => { if (selectedId) void loadMessages(selectedId); else setMessages([]); }, [loadMessages, selectedId]);

  const sendText = async () => { if (!peer) return; try { const message = await window.electronAPI.phone.sendText(peer.id, text); setMessages((items) => mergeMessages(items, [message])); setText(''); } catch (e) { setError((e as Error).message); } };
  const startCall = async (kind: PhoneCallKind) => { if (!peer?.trusted || peer.status !== 'online') return; const id = crypto.randomUUID(); setCallId(id); setCallKind(kind); setCallState('inviting'); await window.electronAPI.phone.sendSignal(peer.id, { type: 'call.invite', callId: id, peerId: peer.id, kind }); };
  const acceptCall = async () => { if (!incoming) return; setCallState('connecting'); await window.electronAPI.phone.sendSignal(incoming.peerId, { type: 'call.accept', callId: incoming.callId, peerId: incoming.peerId }); };

  return <div className="flex h-full min-h-0 bg-background text-foreground">
    <aside className="flex w-72 shrink-0 flex-col border-r border-border bg-card/60">
      <header className="border-b border-border p-4"><div className="flex items-center gap-2 text-base font-semibold"><Phone className="h-5 w-5 text-primary" />Phone</div><div className="mt-1 truncate text-xs text-muted-foreground">{state?.deviceName ?? '正在启动…'} · {state?.ready ? `端口 ${state.port}` : '离线'}</div></header>
      <div className="flex-1 overflow-auto p-2"><div className="px-2 py-2 text-[11px] font-semibold uppercase text-muted-foreground">局域网设备</div>{state?.peers.length ? state.peers.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl p-3 text-left transition ${selectedId === item.id ? 'bg-primary/10 text-primary' : 'hover:bg-accent'}`}><span className="relative grid h-9 w-9 place-items-center rounded-full bg-muted"><Users className="h-4 w-4" /><i className={`absolute bottom-0 right-0 h-2.5 w-2.5 rounded-full border-2 border-card ${item.status === 'online' ? 'bg-emerald-500' : 'bg-zinc-400'}`} /></span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{item.name}</b><small className="text-[11px] text-muted-foreground">{item.trusted ? (item.status === 'online' ? '在线' : '离线') : '等待配对'}</small></span></button>) : <div className="p-6 text-center text-sm text-muted-foreground">正在发现局域网中的 Phone…</div>}</div>
    </aside>
    <main className="flex min-w-0 flex-1 flex-col">{peer ? <><header className="flex h-16 items-center justify-between border-b border-border px-5"><div><div className="font-semibold">{peer.name}</div><div className="text-xs text-muted-foreground">{peer.host}:{peer.port} · {peer.trusted ? peer.status : '未配对'}</div></div><div className="flex gap-2">{!peer.trusted ? <button className="rounded-lg bg-primary px-3 py-2 text-xs text-primary-foreground" onClick={() => void window.electronAPI.phone.pair(peer.id)}>请求配对</button> : <><IconButton title="语音通话" onClick={() => void startCall('audio')}><Phone /></IconButton><IconButton title="视频通话" onClick={() => void startCall('video')}><Video /></IconButton></>}</div></header>
      <section className="flex-1 space-y-3 overflow-auto p-5">{messages.map((message) => { const mine = message.senderId === state?.deviceId; return <div key={message.id} className={`flex ${mine ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[72%] rounded-2xl px-3.5 py-2 text-sm ${mine ? 'bg-primary text-primary-foreground' : 'border border-border bg-card'}`}>{message.kind === 'text' ? <div className="whitespace-pre-wrap break-words">{message.text}</div> : <button className="flex items-center gap-2" onClick={() => void window.electronAPI.phone.openFile(message.id)}><FileText className="h-5 w-5" /><span className="text-left"><b className="block max-w-80 truncate">{message.file?.name}</b><small>{formatBytes(message.file?.size ?? 0)}</small></span></button>}<div className={`mt-1 text-right text-[10px] ${mine ? 'text-primary-foreground/65' : 'text-muted-foreground'}`}>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}{mine ? ` · ${message.status}` : ''}</div></div></div>; })}</section>
      <footer className="border-t border-border p-4"><div className="flex items-end gap-2"><IconButton title="发送文件" onClick={() => void window.electronAPI.phone.selectAndSendFiles(peer.id).then((items) => setMessages((current) => mergeMessages(current, items))).catch((e: Error) => setError(e.message))}><Paperclip /></IconButton><textarea value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void sendText(); } }} placeholder={peer.trusted ? '输入消息，Enter 发送' : '配对后即可聊天'} disabled={!peer.trusted} className="max-h-32 min-h-10 flex-1 resize-none rounded-xl border border-input bg-card px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary/20" /><IconButton title="发送" onClick={() => void sendText()}><Send /></IconButton></div>{error && <div className="mt-2 flex items-center justify-between rounded-lg bg-destructive/10 px-3 py-2 text-xs text-destructive">{error}<button onClick={() => setError('')}><X className="h-3.5 w-3.5" /></button></div>}</footer></> : <div className="grid h-full place-items-center text-center text-muted-foreground"><div><Phone className="mx-auto mb-3 h-12 w-12 opacity-20" /><p>选择一台局域网设备开始通信</p></div></div>}</main>
    {callState !== 'idle' && <div className="fixed inset-0 z-[1600] grid place-items-center bg-black/75 p-6"><div className="relative w-full max-w-4xl overflow-hidden rounded-2xl bg-zinc-950 text-white shadow-2xl"><video ref={remoteVideoRef} autoPlay playsInline className="aspect-video w-full object-cover" /><video ref={localVideoRef} autoPlay muted playsInline className="absolute right-4 top-4 aspect-video w-44 rounded-xl border border-white/20 bg-black object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 p-5 text-center"><div className="mb-4"><b>{peer?.name}</b><div className="text-xs text-white/60">{callState === 'ringing' ? '来电' : callState === 'inviting' ? '等待对方接听…' : callState === 'connecting' ? '正在连接…' : '通话中'}</div></div><div className="flex justify-center gap-3">{incoming && callState === 'ringing' ? <><CallButton green onClick={() => void acceptCall()}><Phone /></CallButton><CallButton onClick={() => { void window.electronAPI.phone.sendSignal(incoming.peerId, { type: 'call.reject', callId: incoming.callId, peerId: incoming.peerId }); endCall(false); }}><PhoneOff /></CallButton></> : <><CallButton active={muted} onClick={() => { const next = !muted; localStreamRef.current?.getAudioTracks().forEach((track) => { track.enabled = !next; }); setMuted(next); }}><Mic /></CallButton>{callKind === 'video' && <CallButton active={cameraOff} onClick={() => { const next = !cameraOff; localStreamRef.current?.getVideoTracks().forEach((track) => { track.enabled = !next; }); setCameraOff(next); }}><Camera /></CallButton>}<CallButton onClick={() => endCall()}><PhoneOff /></CallButton></>}</div></div></div></div>}
  </div>;
}

function IconButton({ title, onClick, children }: { title: string; onClick: () => void; children: React.ReactElement }) { return <button title={title} onClick={onClick} className="grid h-10 w-10 place-items-center rounded-xl border border-border bg-card transition hover:bg-accent">{cloneElement(children, { className: 'h-4 w-4' } as React.HTMLAttributes<HTMLElement>)}</button>; }
function CallButton({ onClick, children, green, active }: { onClick: () => void; children: React.ReactElement; green?: boolean; active?: boolean }) { return <button onClick={onClick} className={`grid h-12 w-12 place-items-center rounded-full ${green ? 'bg-emerald-500' : active ? 'bg-white text-black' : 'bg-red-500'}`}>{cloneElement(children, { className: 'h-5 w-5' } as React.HTMLAttributes<HTMLElement>)}</button>; }
function formatBytes(size: number): string { if (size < 1024) return `${size} B`; if (size < 1024 ** 2) return `${(size / 1024).toFixed(1)} KB`; if (size < 1024 ** 3) return `${(size / 1024 ** 2).toFixed(1)} MB`; return `${(size / 1024 ** 3).toFixed(1)} GB`; }
