import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { Check, ChevronDown, Info, LoaderCircle, Search as SearchIcon, X } from 'lucide-react';
import { cn } from '@/lib/utils';

type CommonProps = React.HTMLAttributes<HTMLElement> & { children?: React.ReactNode };

export function Button({ type = 'default', size = 'middle', block, loading, icon, className, children, ...props }: Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type'> & { type?: 'default' | 'primary' | 'text' | 'link'; size?: 'small' | 'middle' | 'large'; block?: boolean; loading?: boolean; icon?: React.ReactNode }) {
  return <button type="button" {...props} className={cn('inline-flex items-center justify-center gap-1.5 rounded-lg border font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/25 disabled:pointer-events-none disabled:opacity-50', type === 'primary' && 'border-primary bg-primary text-primary-foreground shadow-sm hover:bg-primary-hover', type === 'default' && 'border-border bg-card text-foreground hover:border-primary/30 hover:bg-accent', type === 'text' && 'border-transparent bg-transparent hover:bg-accent', type === 'link' && 'border-transparent bg-transparent p-0 text-primary hover:underline', size === 'small' ? 'h-7 px-2 text-xs' : size === 'large' ? 'h-11 px-4 text-sm' : 'h-9 px-3 text-sm', block && 'w-full', className)}>{loading ? <LoaderCircle className="h-4 w-4 animate-spin" /> : icon}{children}</button>;
}

type InputProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'> & { size?: 'small' | 'middle' | 'large' } & { prefix?: React.ReactNode; allowClear?: boolean; onPressEnter?: () => void };
export function Input({ prefix, allowClear, onPressEnter, className, value, onChange, size, ...props }: InputProps) {
  return <div className={cn('flex h-9 items-center gap-2 rounded-lg border border-input bg-card px-3 transition focus-within:border-primary/40 focus-within:ring-2 focus-within:ring-primary/10', size === 'large' && 'h-11', className)}>{prefix}<input {...props} value={value} onChange={onChange} onKeyDown={(e) => { props.onKeyDown?.(e); if (e.key === 'Enter') onPressEnter?.(); }} className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" />{allowClear && value ? <button type="button" onClick={() => onChange?.({ target: { value: '' } } as React.ChangeEvent<HTMLInputElement>)} className="text-muted-foreground hover:text-foreground"><X size={14} /></button> : null}</div>;
}
Input.TextArea = function TextArea({ className, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className={cn('w-full resize-y rounded-lg border border-input bg-card px-3 py-2 text-sm outline-none transition placeholder:text-muted-foreground focus:border-primary/40 focus:ring-2 focus:ring-primary/10', className)} />; };
Input.Search = function SearchInput({ onSearch, className, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { onSearch?: (value: string) => void }) { const [value, setValue] = useState(String(props.value ?? '')); return <div className={cn('flex gap-2', className)}><Input {...props} value={value} prefix={<SearchIcon size={14} />} onChange={(e) => { setValue(e.target.value); props.onChange?.(e); }} onPressEnter={() => onSearch?.(value)} /><Button icon={<SearchIcon size={14} />} onClick={() => onSearch?.(value)} /></div>; };

export function Space({ direction = 'horizontal', size = 'small', wrap, className, children, ...props }: CommonProps & { direction?: 'horizontal' | 'vertical'; size?: 'small' | 'middle' | 'large' | number; wrap?: boolean }) { const gap = typeof size === 'number' ? undefined : size === 'large' ? 'gap-4' : size === 'middle' ? 'gap-3' : 'gap-2'; return <div {...props as React.HTMLAttributes<HTMLDivElement>} style={{ ...props.style, gap: typeof size === 'number' ? size : undefined }} className={cn('flex', direction === 'vertical' ? 'flex-col' : 'items-center', wrap && 'flex-wrap', gap, className)}>{children}</div>; }
Space.Compact = function Compact({ children, className, ...props }: CommonProps) { return <div {...props as React.HTMLAttributes<HTMLDivElement>} className={cn('flex [&>*:not(:first-child)]:-ml-px [&>*:not(:first-child)]:rounded-l-none [&>*:not(:last-child)]:rounded-r-none', className)}>{children}</div>; };

export function Tooltip({ title, children }: { title?: React.ReactNode; children: React.ReactNode }) { return <span title={typeof title === 'string' ? title : undefined} className="inline-flex">{children}</span>; }
export function Tag({ color, children, className, ...props }: CommonProps & { color?: string; icon?: React.ReactNode }) { return <span {...props as React.HTMLAttributes<HTMLSpanElement>} className={cn('inline-flex items-center gap-1 rounded-full border border-border bg-muted px-2 py-0.5 text-[11px] text-muted-foreground', color === 'red' && 'border-red-200 bg-red-50 text-red-700', color === 'green' && 'border-emerald-200 bg-emerald-50 text-emerald-700', color === 'blue' && 'border-blue-200 bg-blue-50 text-blue-700', color === 'orange' && 'border-amber-200 bg-amber-50 text-amber-700', color === 'purple' && 'border-violet-200 bg-violet-50 text-violet-700', className)}>{props.icon}{children}</span>; }
Tag.CheckableTag = function CheckableTag({ checked, onChange, children }: { checked?: boolean; onChange?: (checked: boolean) => void; children?: React.ReactNode }) { return <button type="button" onClick={() => onChange?.(!checked)} className={cn('rounded-full border px-2 py-0.5 text-[11px] transition', checked ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-card hover:bg-accent')}>{children}</button>; };

function Text({ type, strong, ellipsis, className, children, ...props }: CommonProps & { type?: 'secondary' | 'danger'; strong?: boolean; ellipsis?: boolean | { rows: number } }) { return <span {...props as React.HTMLAttributes<HTMLSpanElement>} className={cn(type === 'secondary' && 'text-muted-foreground', type === 'danger' && 'text-destructive', strong && 'font-semibold', ellipsis && 'truncate', className)}>{children}</span>; }
function Paragraph({ type, ellipsis, className, children, ...props }: CommonProps & { type?: 'secondary'; ellipsis?: boolean | { rows: number } }) { const rows = typeof ellipsis === 'object' ? ellipsis.rows : undefined; return <p {...props as React.HTMLAttributes<HTMLParagraphElement>} className={cn(type === 'secondary' && 'text-muted-foreground', rows === 2 && 'line-clamp-2', ellipsis === true && 'truncate', className)}>{children}</p>; }
function Link({ children, strong, ...props }: React.AnchorHTMLAttributes<HTMLAnchorElement> & { strong?: boolean }) { return <a {...props} className={cn('cursor-pointer text-primary hover:underline', strong && 'font-semibold', props.className)}>{children}</a>; }
export const Typography = { Text, Paragraph, Link };

export function Empty({ description = '暂无内容', className, style }: { description?: React.ReactNode; image?: unknown; className?: string; style?: React.CSSProperties }) { return <div style={style} className={cn('flex min-h-36 flex-col items-center justify-center gap-3 px-6 text-center text-sm text-muted-foreground', className)}><div className="grid h-14 w-14 place-items-center rounded-2xl border border-dashed border-border bg-muted/60"><SearchIcon size={22} className="opacity-35" /></div><span>{description}</span></div>; }
Empty.PRESENTED_IMAGE_SIMPLE = 'simple';
export function Alert({ type = 'info', message, description, className, style }: { type?: 'info' | 'error' | 'warning' | 'success'; message?: React.ReactNode; description?: React.ReactNode; showIcon?: boolean; className?: string; style?: React.CSSProperties }) { return <div style={style} className={cn('flex gap-2 rounded-lg border border-blue-200 bg-blue-50/70 px-3 py-2 text-sm text-blue-900', type === 'error' && 'border-red-200 bg-red-50 text-red-800', type === 'warning' && 'border-amber-200 bg-amber-50 text-amber-900', type === 'success' && 'border-emerald-200 bg-emerald-50 text-emerald-900', className)}><Info size={15} className="mt-0.5 shrink-0" /><div><div className="font-medium">{message}</div>{description && <div className="mt-1 text-xs opacity-80">{description}</div>}</div></div>; }

export function Card({ title, extra, children, className, style, onClick }: CommonProps & { title?: React.ReactNode; extra?: React.ReactNode; hoverable?: boolean; size?: string; onClick?: () => void }) { return <section style={style} onClick={onClick} className={cn('rounded-xl border border-border bg-card p-3 shadow-sm', onClick && 'cursor-pointer transition hover:-translate-y-px hover:border-primary/25 hover:shadow-md', className)}>{(title || extra) && <header className="mb-3 flex items-center justify-between gap-2 font-semibold">{title}<span>{extra}</span></header>}{children}</section>; }

export function List<T>({ dataSource = [], renderItem, className }: { dataSource?: T[]; renderItem: (item: T, index: number) => React.ReactNode; size?: string; className?: string }) { return <div className={cn('divide-y divide-border', className)}>{dataSource.map(renderItem)}</div>; }
List.Item = function ListItem({ children, className, ...props }: CommonProps) { return <div {...props as React.HTMLAttributes<HTMLDivElement>} className={cn('px-3 py-2', className)}>{children}</div>; };

export function Tabs({ items = [], activeKey, onChange, className, style }: { items?: Array<{ key: string; label: React.ReactNode; children?: React.ReactNode }>; activeKey?: string; onChange?: (key: string) => void; size?: string; type?: string; tabBarStyle?: React.CSSProperties; className?: string; style?: React.CSSProperties }) { const [own, setOwn] = useState(items[0]?.key); const current = activeKey ?? own; return <div style={style} className={cn('flex min-h-0 flex-col', className)}><div className="flex shrink-0 gap-1 overflow-x-auto border-b border-border px-2 pt-1">{items.map((item) => <button type="button" key={item.key} onClick={() => { setOwn(item.key); onChange?.(item.key); }} className={cn('relative flex shrink-0 items-center gap-1.5 px-3 py-2 text-xs font-medium text-muted-foreground transition hover:text-foreground', current === item.key && 'text-primary after:absolute after:inset-x-2 after:bottom-0 after:h-0.5 after:rounded-full after:bg-primary')}>{item.label}</button>)}</div><div className="min-h-0 flex-1 overflow-auto">{items.find((item) => item.key === current)?.children}</div></div>; }

export function Segmented({ value, onChange, options, className }: { value?: string; onChange?: (value: string) => void; size?: string; options: Array<{ label: React.ReactNode; value: string }>; className?: string }) { return <div className={cn('inline-flex rounded-lg bg-muted p-1', className)}>{options.map((o) => <button type="button" key={o.value} onClick={() => onChange?.(o.value)} className={cn('rounded-md px-3 py-1 text-xs text-muted-foreground transition', value === o.value && 'bg-card text-foreground shadow-sm')}>{o.label}</button>)}</div>; }

export function Select({ value, defaultValue, onChange, options = [], className, style }: { value?: string | string[]; defaultValue?: string; onChange?: (value: any) => void; options?: Array<{ label: React.ReactNode; value: string }>; mode?: 'multiple'; size?: string; className?: string; style?: React.CSSProperties }) { return <div className="relative"><select multiple={Array.isArray(value)} value={value ?? defaultValue} onChange={(e) => onChange?.(e.target.multiple ? Array.from(e.target.selectedOptions).map((o) => o.value) : e.target.value)} style={style} className={cn('h-9 appearance-none rounded-lg border border-input bg-card px-3 pr-8 text-sm outline-none focus:border-primary/40', className)}>{options.map((o) => <option key={o.value} value={o.value}>{String(o.label)}</option>)}</select><ChevronDown size={13} className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground" /></div>; }

export function Spin({ tip, className, style }: { tip?: React.ReactNode; size?: string; className?: string; style?: React.CSSProperties }) { return <div style={style} className={cn('flex items-center justify-center gap-2 text-sm text-muted-foreground', className)}><LoaderCircle className="h-4 w-4 animate-spin" />{tip}</div>; }
export function Progress({ percent = 0 }: { percent?: number; size?: string; showInfo?: boolean; status?: string }) { return <div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.max(0, Math.min(100, percent))}%` }} /></div>; }

export function Drawer({ open, onClose, title, children, width = 480, extra }: { open?: boolean; onClose?: () => void; title?: React.ReactNode; children?: React.ReactNode; width?: number | string; extra?: React.ReactNode; destroyOnClose?: boolean }) { if (!open) return null; return <div className="fixed inset-0 z-[1200] bg-black/20 backdrop-blur-[1px]" onMouseDown={onClose}><aside style={{ width }} className="absolute inset-y-0 right-0 flex max-w-[92vw] flex-col border-l border-border bg-card shadow-2xl animate-slide-in-right" onMouseDown={(e) => e.stopPropagation()}><header className="flex h-14 shrink-0 items-center justify-between border-b border-border px-5 font-semibold">{title}<div className="flex items-center gap-2">{extra}<Button type="text" size="small" icon={<X size={16} />} onClick={onClose} /></div></header><div className="min-h-0 flex-1 overflow-auto p-5">{children}</div></aside></div>; }
export function Modal({ open, onCancel, onOk, title, children, okText = '确定', cancelText = '取消', confirmLoading, width = 520, footer }: { open?: boolean; onCancel?: () => void; onOk?: () => void; title?: React.ReactNode; children?: React.ReactNode; okText?: string; cancelText?: string; confirmLoading?: boolean; width?: number; footer?: React.ReactNode | null; destroyOnClose?: boolean }) { if (!open) return null; return <div className="fixed inset-0 z-[1300] grid place-items-center bg-black/30 p-4 backdrop-blur-sm" onMouseDown={onCancel}><section style={{ width }} className="max-h-[90vh] max-w-full overflow-hidden rounded-2xl border border-border bg-card shadow-2xl" onMouseDown={(e) => e.stopPropagation()}><header className="flex h-14 items-center justify-between border-b border-border px-5 font-semibold">{title}<Button type="text" size="small" icon={<X size={16} />} onClick={onCancel} /></header><div className="max-h-[calc(90vh-7rem)] overflow-auto p-5">{children}</div>{footer !== null && <footer className="flex justify-end gap-2 border-t border-border px-5 py-3">{footer ?? <><Button onClick={onCancel}>{cancelText}</Button><Button type="primary" loading={confirmLoading} onClick={onOk}>{okText}</Button></>}</footer>}</section></div>; }

export function Steps({ items = [], current = 0, direction = 'horizontal' }: { items?: Array<{ title?: React.ReactNode; description?: React.ReactNode; status?: string }>; current?: number; direction?: 'horizontal' | 'vertical'; size?: string }) { return <div className={cn('flex', direction === 'vertical' ? 'flex-col gap-3' : 'gap-2')}>{items.map((item, i) => <div key={i} className="flex min-w-0 flex-1 gap-2"><span className={cn('grid h-5 w-5 shrink-0 place-items-center rounded-full border text-[10px]', i < current ? 'border-primary bg-primary text-primary-foreground' : i === current ? 'border-primary text-primary' : 'border-border text-muted-foreground')}>{i < current ? <Check size={11} /> : i + 1}</span><div className="min-w-0"><div className="text-xs font-medium">{item.title}</div>{item.description && <div className="text-[11px] text-muted-foreground">{item.description}</div>}</div></div>)}</div>; }
export function Popconfirm({ title, onConfirm, children }: { title?: React.ReactNode; onConfirm?: () => void; children?: React.ReactNode; okText?: string; cancelText?: string }) { return <span onClick={(e) => { e.stopPropagation(); if (window.confirm(String(title ?? '确认操作？'))) onConfirm?.(); }}>{children}</span>; }
export function Checkbox({ checked, onChange, children }: { checked?: boolean; onChange?: (event: { target: { checked: boolean } }) => void; children?: React.ReactNode }) { return <label className="flex cursor-pointer items-center gap-2"><input type="checkbox" checked={checked} onChange={(e) => onChange?.({ target: { checked: e.target.checked } })} className="accent-primary" />{children}</label>; }

type FormStore = Record<string, unknown>;
const FormContext = createContext<{ values: FormStore; setValue: (name: string, value: unknown) => void } | null>(null);
export function Form({ form, initialValues = {}, children }: { form?: ReturnType<typeof Form.useForm>[0]; initialValues?: FormStore; layout?: string; children?: React.ReactNode }) { useEffect(() => { form?.setFieldsValue(initialValues); }, [form, initialValues]); return <FormContext.Provider value={{ values: form?.values ?? initialValues, setValue: (name, value) => form?.setField(name, value) }}><div className="space-y-4">{children}</div></FormContext.Provider>; }
Form.useForm = function useForm<T extends FormStore>() { const [values, setValues] = useState<T>({} as T); return [useMemo(() => ({ values, setField: (name: string, value: unknown) => setValues((v) => ({ ...v, [name]: value })), setFieldsValue: (next: Partial<T>) => setValues((v) => ({ ...v, ...next })), resetFields: () => setValues({} as T), validateFields: async () => values }), [values])] as const; };
Form.Item = function FormItem({ label, name, children }: { label?: React.ReactNode; name?: string; rules?: unknown[]; children?: React.ReactNode }) { const ctx = useContext(FormContext); const child = React.isValidElement(children) && name ? React.cloneElement(children as React.ReactElement<any>, { value: ctx?.values[name] ?? '', onChange: (arg: any) => ctx?.setValue(name, arg?.target ? arg.target.value : arg) }) : children; return <label className="block space-y-1.5"><span className="text-xs font-medium text-muted-foreground">{label}</span>{child}</label>; };

const notify = (kind: string, text: React.ReactNode) => window.dispatchEvent(new CustomEvent('work-browser:toast', { detail: { kind, text: String(text) } }));
export const message = { success: (text: React.ReactNode) => notify('success', text), error: (text: React.ReactNode) => notify('error', text), warning: (text: React.ReactNode) => notify('warning', text), info: (text: React.ReactNode) => notify('info', text) };
export function ToastHost() { const [toasts, setToasts] = useState<Array<{ id: number; kind: string; text: string }>>([]); useEffect(() => { const handler = (event: Event) => { const detail = (event as CustomEvent<{ kind: string; text: string }>).detail; const id = Date.now(); setToasts((v) => [...v, { id, ...detail }]); window.setTimeout(() => setToasts((v) => v.filter((t) => t.id !== id)), 2800); }; window.addEventListener('work-browser:toast', handler); return () => window.removeEventListener('work-browser:toast', handler); }, []); return <div className="fixed right-5 top-5 z-[2000] flex w-80 flex-col gap-2">{toasts.map((t) => <div key={t.id} className={cn('rounded-xl border bg-card px-4 py-3 text-sm shadow-xl', t.kind === 'error' && 'border-red-200 text-red-700', t.kind === 'success' && 'border-emerald-200 text-emerald-700')}>{t.text}</div>)}</div>; }

export const Layout = ({ children, className, style }: CommonProps) => <div className={cn('flex min-h-0', className)} style={style}>{children}</div>;
Layout.Sider = ({ children, width, className, style }: CommonProps & { width?: number }) => <aside className={className} style={{ width, ...style }}>{children}</aside>;
Layout.Content = ({ children, className, style }: CommonProps) => <main className={className} style={style}>{children}</main>;
