import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as echarts from 'echarts/core';
import { GraphChart } from 'echarts/charts';
import { LegendComponent, TooltipComponent } from 'echarts/components';
import { CanvasRenderer } from 'echarts/renderers';
import type { EChartsCoreOption, EChartsType } from 'echarts/core';
import { BookOpen, Languages, Loader2, Network, Search, Sparkles, Trash2 } from '@/components/icons';
import { Button } from '@/components/ui/button';
import { createOpenAIProvider } from '@/core/llm';
import { useStore } from '@/store/store';
import { addLookupHistory, BUILT_IN_WORD_BOOKS, buildVocabularyGraph, dueForReview, filterVocabulary, formatNextReview, importVocabularyJson, learningActivity, mergeEntry, mergeVocabulary, normalizeQuery, normalizeWord, parseLookupResponse, reviewEntry, updateEntryLabels, vocabularyStats, vocabularyToCsv } from './model';
import { loadLookupHistory, loadReviewLog, loadVocabulary, saveLookupHistory, saveReviewLog, saveVocabulary } from './storage';
import type { LookupHistoryItem, ReviewLogItem, WordEntry } from './types';
import { ArticleReader } from './ArticleReader';

echarts.use([GraphChart, LegendComponent, TooltipComponent, CanvasRenderer]);

const SYSTEM_PROMPT = `You are an expert English lexicographer and language tutor. Return one valid JSON object only, with no markdown. Schema:
{"word":"lowercase headword","phonetic":"IPA","partOfSpeech":"concise parts of speech","definitions":[{"partOfSpeech":"noun|verb|adjective|etc","meaning":"clear Chinese definition","example":"natural English example","translation":"Chinese translation"}],"forms":[{"label":"Chinese form label","value":"English form"}],"comparisons":[{"word":"confusable English word","difference":"concise Chinese usage difference","example":"English example"}],"suggestions":["spelling candidate"],"collocations":["common collocation"],"topics":["English topic"],"relations":[{"word":"English word","type":"synonym|antonym|related|word-family"}],"memoryTip":"concise Chinese learning tip"}.
Give 1-4 useful definitions grouped by part of speech, authentic examples, applicable inflected forms, 0-4 genuinely confusable words, 3-8 collocations, 1-4 topics and 4-12 meaningful relations. When the input appears misspelled, use the most likely correct headword and include other plausible spellings in suggestions; otherwise return an empty suggestions array. Never invent a word. If context and a target are supplied, explain that exact target in context. For an inflected form, use its dictionary headword and include the queried form in forms.`;

function Graph({ entries, onPick }: { entries: WordEntry[]; onPick: (word: string) => void }) {
  const ref = useRef<HTMLDivElement>(null);
  const [relations, setRelations] = useState(() => new Set(['synonym', 'antonym', 'related', 'word-family', 'topic'])); const [focus, setFocus] = useState(''); const [search, setSearch] = useState('');
  const graph = useMemo(() => buildVocabularyGraph(entries, relations, focus), [entries, focus, relations]);
  const option = useMemo<EChartsCoreOption>(() => ({
    tooltip: { formatter: (params: unknown) => { const item = params as { dataType?: string; data?: { name?: string; value?: string } }; return item.dataType === 'edge' ? item.data?.value : item.data?.name; } },
    legend: { bottom: 0, data: ['单词本', '关联词', '主题'] },
    series: [{ type: 'graph', layout: 'force', roam: true, draggable: true, categories: [{ name: '单词本' }, { name: '关联词' }, { name: '主题' }], data: graph.nodes.map((node) => ({ ...node, category: node.category, itemStyle: node.saved ? { borderWidth: 3, color: node.familiarity === 'mastered' ? '#22c55e' : node.familiarity === 'learning' ? '#f59e0b' : '#4f6ee8' } : undefined })), links: graph.links, edgeLabel: { show: graph.links.length <= 40, formatter: '{c}', fontSize: 9 }, label: { show: true, position: 'right' }, lineStyle: { curveness: 0.08, opacity: 0.65 }, emphasis: { focus: 'adjacency' }, force: { repulsion: 220, edgeLength: [80, 150], gravity: 0.08 } }],
  }), [graph]);
  useEffect(() => { if (!ref.current) return; const chart: EChartsType = echarts.init(ref.current); chart.setOption(option); chart.on('click', (params: unknown) => { const item = params as { dataType?: string; data?: { id?: string; category?: number } }; if (item.dataType === 'node' && item.data?.category !== 2 && item.data.id) onPick(item.data.id); }); const observer = new ResizeObserver(() => chart.resize()); observer.observe(ref.current); return () => { observer.disconnect(); chart.dispose(); }; }, [onPick, option]);
  const toggle = (value: string) => setRelations((current) => { const next = new Set(current); if (next.has(value)) next.delete(value); else next.add(value); return next; });
  return <div className="flex h-full min-h-[420px] w-full flex-col"><div className="flex flex-wrap items-center gap-2 border-b p-2"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜索图谱单词" className="h-8 min-w-40 flex-1 rounded-md border bg-background px-2 text-xs"/><Button size="sm" variant="outline" onClick={() => setFocus(normalizeWord(search))}>定位聚焦</Button><Button size="sm" variant="ghost" onClick={() => { setFocus(''); setSearch(''); }}>恢复全图</Button>{[['synonym','同义'],['antonym','反义'],['word-family','词族'],['related','相关'],['topic','主题']].map(([id,label]) => <button key={id} onClick={() => toggle(id)} className={`rounded-full border px-2 py-1 text-[10px] ${relations.has(id) ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}>{label}</button>)}</div>{graph.nodes.length ? <div ref={ref} className="min-h-0 flex-1" /> : <Empty text="没有符合当前筛选条件的关系。" />}</div>;
}

function Empty({ text }: { text: string }) { return <div className="flex min-h-64 flex-col items-center justify-center gap-3 text-sm text-muted-foreground"><Languages className="h-10 w-10 opacity-30"/><p>{text}</p></div>; }

export function EnglishLookupPanel() {
  const aiApi = useStore((state) => state.aiApi);
  const [query, setQuery] = useState('');
  const [result, setResult] = useState<WordEntry | null>(null);
  const [entries, setEntries] = useState<WordEntry[]>(loadVocabulary);
  const [history, setHistory] = useState<LookupHistoryItem[]>(loadLookupHistory);
  const [tab, setTab] = useState<'lookup' | 'article' | 'book' | 'review' | 'graph'>('lookup');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [bookSearch, setBookSearch] = useState('');
  const [targetWord, setTargetWord] = useState('');
  const [bookFilter, setBookFilter] = useState<'all' | 'new' | 'learning' | 'mastered'>('all');
  const [tagFilter, setTagFilter] = useState(''); const [bookGroup, setBookGroup] = useState(''); const [labelInput, setLabelInput] = useState('');
  const [reviewRevealed, setReviewRevealed] = useState(false);
  const [voiceLocale, setVoiceLocale] = useState<'en-US' | 'en-GB'>('en-US');
  const [speechRate, setSpeechRate] = useState(0.9);
  const [selectedWords, setSelectedWords] = useState<Set<string>>(() => new Set());
  const [importMessage, setImportMessage] = useState('');
  const [reviewLog, setReviewLog] = useState<ReviewLogItem[]>(loadReviewLog);
  const [dailyGoal, setDailyGoal] = useState(() => Number(localStorage.getItem('nwd.english-lookup.daily-goal') || 10));
  const inputRef = useRef<HTMLInputElement>(null);
  const importRef = useRef<HTMLInputElement>(null);
  const abortRef = useRef<AbortController | null>(null);
  useEffect(() => saveVocabulary(entries), [entries]);
  useEffect(() => saveLookupHistory(history), [history]);
  useEffect(() => saveReviewLog(reviewLog), [reviewLog]);
  useEffect(() => localStorage.setItem('nwd.english-lookup.daily-goal', String(dailyGoal)), [dailyGoal]);
  useEffect(() => () => abortRef.current?.abort(), []);
  useEffect(() => { const openSearch = () => { setTab('lookup'); requestAnimationFrame(() => inputRef.current?.focus()); }; window.addEventListener('english-lookup:search', openSearch); return () => window.removeEventListener('english-lookup:search', openSearch); }, []);

  const lookup = useCallback(async (input = query) => {
    const normalizedQuery = normalizeQuery(input); const word = normalizeWord(normalizedQuery); setError('');
    if (!word) { setError('请输入有效的英文单词、短语或例句'); return; }
    const requestedTarget = normalizeWord(targetWord);
    const cached = entries.find((item) => (item.query?.toLocaleLowerCase('en-US') === normalizedQuery.toLocaleLowerCase('en-US') && (item.targetWord ?? '') === requestedTarget) || (!requestedTarget && item.word === word));
    if (cached) { setResult(cached); setQuery(normalizedQuery); setHistory((current) => addLookupHistory(current, { query: normalizedQuery, word: cached.word, lookedUpAt: Date.now() })); return; }
    if (!aiApi.apiKey?.trim() || !aiApi.baseUrl?.trim() || !aiApi.model?.trim()) { setError('请先在设置中配置 AI API Key、Base URL 和模型'); return; }
    setLoading(true);
    const controller = new AbortController(); abortRef.current = controller;
    try {
      const provider = createOpenAIProvider({ apiKey: aiApi.apiKey, baseUrl: aiApi.baseUrl, chatProxy: aiApi.provider === 'qwen' ? window.electronAPI.llmChat : undefined });
      const chunks: string[] = [];
      const normalizedTarget = normalizeWord(targetWord);
      for await (const chunk of provider.chat([{ role: 'system', content: SYSTEM_PROMPT }, { role: 'user', content: normalizedTarget ? `Context: ${normalizedQuery}\nExact target to explain: ${normalizedTarget}` : `Look up this English input and preserve its context: ${normalizedQuery}` }], { model: aiApi.model, temperature: 0.2, maxTokens: 2200, stream: true, signal: controller.signal })) if (chunk.delta) chunks.push(chunk.delta);
      const next = { ...parseLookupResponse(chunks.join(''), normalizedTarget || word), query: normalizedQuery, context: normalizedQuery.includes(' ') ? normalizedQuery : undefined, targetWord: normalizedTarget || undefined };
      setResult(next); setQuery(normalizedQuery); setHistory((current) => addLookupHistory(current, { query: normalizedQuery, word: next.word, lookedUpAt: Date.now() })); setTab('lookup');
    } catch (reason) { setError(reason instanceof DOMException && reason.name === 'AbortError' ? '查询已取消' : reason instanceof Error ? reason.message : '查询失败，请稍后重试'); } finally { if (abortRef.current === controller) abortRef.current = null; setLoading(false); }
  }, [aiApi, entries, query, targetWord]);

  const save = () => { if (!result) return; setEntries((current) => [mergeEntry(current.find((item) => item.word === result.word), result), ...current.filter((item) => item.word !== result.word)]); };
  const selectWord = useCallback((word: string) => { const saved = entries.find((item) => item.word === word); if (saved) { setResult(saved); setQuery(saved.word); setTab('lookup'); } else { setQuery(word); void lookup(word); } }, [entries, lookup]);
  const saved = result ? entries.some((item) => item.word === result.word) : false;
  const dueEntries = useMemo(() => dueForReview(entries), [entries]);
  const allTags = useMemo(() => [...new Set(entries.flatMap((entry) => entry.tags ?? []))].sort(), [entries]);
  const filteredEntries = useMemo(() => filterVocabulary(entries, tagFilter, bookGroup, bookFilter).filter((entry) => !bookSearch.trim() || `${entry.word} ${entry.definitions.map((item) => item.meaning).join(' ')}`.toLocaleLowerCase().includes(bookSearch.trim().toLocaleLowerCase())), [bookFilter, bookGroup, bookSearch, entries, tagFilter]);
  const stats = useMemo(() => vocabularyStats(entries), [entries]);
  const activity = useMemo(() => learningActivity(reviewLog), [reviewLog]);
  const rateReview = (entry: WordEntry, rating: 'forgot' | 'hard' | 'known') => { const reviewedAt = Date.now(); setEntries((current) => current.map((item) => item.id === entry.id ? reviewEntry(item, rating, reviewedAt) : item)); setReviewLog((current) => [...current, { word: entry.word, rating, reviewedAt }]); setReviewRevealed(false); };
  const speak = useCallback((text: string) => { if (!text.trim() || !('speechSynthesis' in window)) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = voiceLocale; utterance.rate = speechRate; const voice = window.speechSynthesis.getVoices().find((item) => item.lang === voiceLocale); if (voice) utterance.voice = voice; window.speechSynthesis.speak(utterance); }, [speechRate, voiceLocale]);
  const download = (content: string, filename: string, type: string) => { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); };
  const importJson = async (file?: File) => { if (!file) return; try { const incoming = importVocabularyJson(await file.text()); setEntries((current) => mergeVocabulary(current, incoming)); setImportMessage(`已导入并合并 ${incoming.length} 个单词`); } catch (reason) { setImportMessage(reason instanceof Error ? reason.message : '导入失败'); } finally { if (importRef.current) importRef.current.value = ''; } };
  const toggleSelected = (word: string) => setSelectedWords((current) => { const next = new Set(current); if (next.has(word)) next.delete(word); else next.add(word); return next; });
  const setSelectedFamiliarity = (familiarity: 'new' | 'learning' | 'mastered') => { setEntries((current) => current.map((entry) => selectedWords.has(entry.word) ? { ...entry, familiarity, updatedAt: Date.now() } : entry)); setSelectedWords(new Set()); };
  const labelSelected = (mode: 'addTag' | 'removeTag' | 'addBook' | 'removeBook') => { const value = labelInput.trim(); if (!value) return; setEntries((current) => current.map((entry) => selectedWords.has(entry.word) ? updateEntryLabels(entry, mode === 'addTag' ? { addTags: [value] } : mode === 'removeTag' ? { removeTags: [value] } : mode === 'addBook' ? { addBooks: [value as NonNullable<WordEntry['wordBooks']>[number]] } : { removeBooks: [value as NonNullable<WordEntry['wordBooks']>[number]] }) : entry)); setLabelInput(''); };

  return <div className="flex h-full min-h-0 w-full flex-col overflow-hidden bg-background">
    <header className="border-b px-6 py-5"><div className="mx-auto flex max-w-6xl items-center gap-3"><div className="rounded-xl bg-primary/10 p-2.5 text-primary"><Languages className="h-6 w-6"/></div><div><h1 className="text-lg font-semibold">AI 英语查询</h1><p className="text-xs text-muted-foreground">释义、语境、复习与词汇关系，一次查清</p></div><div className="ml-auto flex rounded-lg border bg-muted/30 p-1">{([['lookup','查询',Search],['book',`单词本 ${entries.length}`,BookOpen],['review',`复习 ${dueEntries.length}`,Sparkles],['graph','知识图谱',Network]] as const).map(([id,label,Icon]) => <button key={id} onClick={() => setTab(id)} className={`flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs ${tab === id ? 'bg-background font-medium shadow-sm' : 'text-muted-foreground'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div></div></header>
    <main className={`min-h-0 flex-1 ${tab === 'graph' ? 'overflow-hidden p-2 sm:p-3' : 'overflow-auto p-3 sm:p-6'}`}><div className={tab === 'graph' ? 'h-full w-full' : tab === 'book' ? 'mx-auto flex w-full max-w-[1600px] flex-col [&>div:nth-child(1)]:order-2 [&>div:nth-child(2)]:order-3 [&>div:nth-child(2)]:grid-cols-[repeat(auto-fit,minmax(280px,1fr))] [&>div:nth-child(3)]:order-1' : 'mx-auto max-w-6xl'}>
      {tab === 'lookup' && history.length > 0 && <div className="mx-auto mb-3 flex max-w-3xl flex-wrap items-center gap-2"><span className="text-xs text-muted-foreground">最近查询：</span>{history.slice(0, 6).map((item) => <button key={item.query} onClick={() => { setQuery(item.query); void lookup(item.query); }} className="max-w-48 truncate rounded-full border px-2.5 py-1 text-xs hover:bg-accent">{item.query}</button>)}<button onClick={() => setHistory([])} className="text-xs text-muted-foreground hover:text-foreground">清空</button></div>}
      {tab === 'lookup' && <div className="mx-auto mb-4 flex max-w-3xl justify-end"><Button size="sm" variant="outline" onClick={() => setTab('article')}>文章翻译与阅读</Button></div>}
      {tab === 'article' && <><div className="mx-auto mb-3 flex max-w-[1500px] justify-end"><Button size="sm" variant="outline" onClick={() => setTab('lookup')}>返回单词查询</Button></div><ArticleReader speak={speak} onLookup={(word, context) => { setQuery(context); setTargetWord(word); setTab('lookup'); }}/></>}
      {tab === 'lookup' && loading && <div className="mx-auto mb-2 max-w-3xl text-right"><button type="button" onClick={() => abortRef.current?.abort()} className="text-xs text-muted-foreground hover:text-foreground">取消查询</button></div>}
      {tab === 'lookup' && <div className="mx-auto mb-2 flex max-w-3xl items-center gap-2"><span className="text-xs text-muted-foreground">目标词（可选）</span><input value={targetWord} onChange={(event) => setTargetWord(event.target.value)} placeholder="查询句子时指定，例如 run into" className="h-8 flex-1 rounded-md border bg-card px-2 text-xs outline-none focus:ring-2 focus:ring-primary/30"/></div>}
      {tab === 'lookup' && <div className="mx-auto mb-3 flex max-w-3xl justify-end gap-2"><select aria-label="发音口音" value={voiceLocale} onChange={(event) => setVoiceLocale(event.target.value as typeof voiceLocale)} className="h-8 rounded-md border bg-card px-2 text-xs"><option value="en-US">美音</option><option value="en-GB">英音</option></select><select aria-label="朗读语速" value={speechRate} onChange={(event) => setSpeechRate(Number(event.target.value))} className="h-8 rounded-md border bg-card px-2 text-xs"><option value="0.75">0.75×</option><option value="0.9">0.9×</option><option value="1">1×</option><option value="1.25">1.25×</option></select></div>}
      {tab === 'lookup' && <><form onSubmit={(event) => { event.preventDefault(); void lookup(); }} className="mx-auto flex max-w-3xl gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input ref={inputRef} autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="输入英文单词或短语，例如 serendipity" className="h-10 w-full rounded-lg border bg-card pl-10 pr-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/></div><Button disabled={loading} type="submit">{loading ? <Loader2 className="mr-2 h-4 w-4"/> : <Sparkles className="mr-2 h-4 w-4"/>}AI 查询</Button></form>{error && <p role="alert" className="mx-auto mt-3 max-w-3xl rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}{result ? <article className="mx-auto mt-6 max-w-3xl space-y-4"><section className="rounded-xl border bg-card p-6 shadow-sm"><div className="flex items-start"><div><h2 className="text-3xl font-semibold tracking-tight">{result.word}</h2><p className="mt-1 text-sm text-muted-foreground">{result.phonetic} {result.partOfSpeech && `· ${result.partOfSpeech}`}</p></div><Button className="ml-auto" variant={saved ? 'outline' : 'default'} onClick={save}><BookOpen className="mr-2 h-4 w-4"/>{saved ? '更新单词本' : '存入单词本'}</Button></div><div className="mt-6 space-y-5">{result.definitions.map((item,index) => <div key={`${item.meaning}-${index}`}><p className="font-medium"><span className="mr-2 text-primary">{index + 1}.</span>{item.meaning}</p>{item.example && <p className="mt-2 border-l-2 border-primary/30 pl-3 text-sm italic">{item.example}</p>}{item.translation && <p className="mt-1 pl-3 text-xs text-muted-foreground">{item.translation}</p>}</div>)}</div></section><div className="grid gap-4 md:grid-cols-2"><section className="rounded-xl border bg-card p-5"><h3 className="text-sm font-semibold">常用搭配</h3><div className="mt-3 flex flex-wrap gap-2">{result.collocations.map((item) => <span key={item} className="rounded-full bg-primary/10 px-2.5 py-1 text-xs text-primary">{item}</span>)}</div></section><section className="rounded-xl border bg-card p-5"><h3 className="text-sm font-semibold">关联词汇</h3><div className="mt-3 flex flex-wrap gap-2">{result.relations.map((item) => <button key={`${item.type}-${item.word}`} onClick={() => selectWord(item.word)} className="rounded-md border px-2.5 py-1 text-left text-xs hover:bg-accent"><b>{item.word}</b><span className="ml-1 text-muted-foreground">{item.type}</span></button>)}</div></section></div>{result.memoryTip && <section className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4 text-sm"><b>记忆提示：</b>{result.memoryTip}</section>}</article> : !loading && <Empty text="输入一个单词，让 AI 为你生成结构化词典卡片。"/>}</>}
      {tab === 'book' && <><div className="mb-5 flex gap-2"><input value={bookSearch} onChange={(event) => setBookSearch(event.target.value)} placeholder="搜索单词或释义" className="h-10 flex-1 rounded-lg border bg-card px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/><select value={bookFilter} onChange={(event) => setBookFilter(event.target.value as typeof bookFilter)} className="h-10 rounded-lg border bg-card px-3 text-sm"><option value="all">全部状态</option><option value="new">生词</option><option value="learning">学习中</option><option value="mastered">已掌握</option></select></div>{filteredEntries.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filteredEntries.map((entry) => <article key={entry.id} className="rounded-xl border bg-card p-4"><div className="flex items-start"><button onClick={() => selectWord(entry.word)} className="min-w-0 flex-1 text-left"><h2 className="text-xl font-semibold">{entry.word}</h2><p className="mt-1 text-xs text-muted-foreground">{entry.phonetic} · {entry.partOfSpeech}</p></button><Button size="sm" variant="ghost" onClick={() => speak(entry.word)}>朗读</Button></div><p className="mt-3 line-clamp-2 text-sm">{entry.definitions[0]?.meaning}</p><div className="mt-4 flex items-center border-t pt-3"><span className="rounded-full bg-muted px-2 py-0.5 text-[10px]">{{ new: '生词', learning: '学习中', mastered: '已掌握' }[entry.familiarity ?? 'new']}</span><button aria-label={`删除 ${entry.word}`} onClick={() => setEntries((current) => current.filter((item) => item.id !== entry.id))} className="ml-auto rounded p-1.5 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="h-4 w-4"/></button></div></article>)}</div> : <Empty text={entries.length ? '没有符合筛选条件的单词。' : '单词本还是空的，先查询并收藏一个单词吧。'}/>}</>}
      {tab === 'review' && (dueEntries.length ? <div className="mx-auto max-w-2xl"><article className="rounded-xl border bg-card p-8 text-center"><p className="text-xs text-muted-foreground">今日待复习 {dueEntries.length} 个</p><h2 className="mt-5 text-4xl font-semibold">{dueEntries[0].word}</h2><div className="mt-3 flex justify-center gap-2"><Button size="sm" variant="ghost" onClick={() => speak(dueEntries[0].word)}>朗读</Button>{dueEntries[0].definitions[0]?.example && <Button size="sm" variant="ghost" onClick={() => speak(dueEntries[0].definitions[0].example)}>朗读例句</Button>}</div>{reviewRevealed ? <div className="mt-7 border-t pt-6"><p className="text-lg">{dueEntries[0].definitions[0]?.meaning}</p><p className="mt-3 text-sm italic">{dueEntries[0].definitions[0]?.example}</p><div className="mt-7 flex justify-center gap-2"><Button variant="outline" onClick={() => rateReview(dueEntries[0], 'forgot')}>忘记了</Button><Button variant="outline" onClick={() => rateReview(dueEntries[0], 'hard')}>有点模糊</Button><Button onClick={() => rateReview(dueEntries[0], 'known')}>认识</Button></div></div> : <Button className="mt-8" onClick={() => setReviewRevealed(true)}>显示答案</Button>}</article></div> : <Empty text="今天没有待复习单词。"/>)}
      {tab === 'lookup' && result?.forms && result.forms.length > 0 && <section className="mx-auto mt-4 max-w-3xl rounded-xl border bg-card p-4"><h3 className="text-sm font-semibold">词形变化</h3><div className="mt-3 flex flex-wrap gap-2">{result.forms.map((form) => <span key={`${form.label}-${form.value}`} className="rounded-md bg-muted px-2.5 py-1 text-xs"><span className="text-muted-foreground">{form.label}</span> · {form.value}</span>)}</div></section>}
      {tab === 'lookup' && result?.suggestions && result.suggestions.length > 0 && <section className="mx-auto mt-4 max-w-3xl rounded-xl border border-amber-500/30 bg-amber-500/5 p-4"><h3 className="text-sm font-semibold">你是否想查询</h3><div className="mt-3 flex flex-wrap gap-2">{result.suggestions.map((word) => <button key={word} onClick={() => { setTargetWord(''); setQuery(word); void lookup(word); }} className="rounded-full border bg-background px-3 py-1 text-xs hover:bg-accent">{word}</button>)}</div></section>}
      {tab === 'lookup' && result?.comparisons && result.comparisons.length > 0 && <section className="mx-auto mt-4 max-w-3xl rounded-xl border bg-card p-4"><h3 className="text-sm font-semibold">易混词对比</h3><div className="mt-3 space-y-3">{result.comparisons.map((item) => <div key={item.word} className="rounded-lg border p-3 text-sm"><button className="font-semibold text-primary hover:underline" onClick={() => selectWord(item.word)}>{item.word}</button><span className="ml-2">{item.difference}</span>{item.example && <p className="mt-1 text-xs italic text-muted-foreground">{item.example}</p>}</div>)}</div></section>}
      {tab === 'book' && <div className="order-2 mb-3 flex flex-wrap items-center gap-2 rounded-lg border bg-card p-2"><input ref={importRef} type="file" accept="application/json,.json" className="hidden" onChange={(event) => void importJson(event.target.files?.[0])}/><Button size="sm" variant="outline" onClick={() => importRef.current?.click()}>导入 JSON</Button><Button size="sm" variant="ghost" onClick={() => setSelectedWords(new Set(filteredEntries.map((entry) => entry.word)))}>全选当前结果</Button>{selectedWords.size > 0 && <><span className="text-xs text-muted-foreground">已选 {selectedWords.size}</span><Button size="sm" variant="outline" onClick={() => setSelectedFamiliarity('learning')}>设为学习中</Button><Button size="sm" variant="outline" onClick={() => setSelectedFamiliarity('mastered')}>设为已掌握</Button><Button size="sm" variant="destructive" onClick={() => { setEntries((current) => current.filter((entry) => !selectedWords.has(entry.word))); setSelectedWords(new Set()); }}>删除所选</Button></>}{importMessage && <span className="ml-auto text-xs text-muted-foreground">{importMessage}</span>}</div>}
      {tab === 'book' && <div className="order-2 mb-3 flex flex-wrap items-center gap-2 rounded-lg border bg-card p-2"><select value={tagFilter} onChange={(event) => setTagFilter(event.target.value)} className="h-8 rounded-md border bg-background px-2 text-xs"><option value="">全部标签</option>{allTags.map((tag) => <option key={tag}>{tag}</option>)}</select><select value={bookGroup} onChange={(event) => setBookGroup(event.target.value)} className="h-8 rounded-md border bg-background px-2 text-xs"><option value="">全部词书</option>{BUILT_IN_WORD_BOOKS.map((book) => <option key={book}>{book}</option>)}</select>{selectedWords.size > 0 && <><input value={labelInput} onChange={(event) => setLabelInput(event.target.value)} placeholder="标签或选择词书" list="english-word-books" className="h-8 min-w-36 rounded-md border bg-background px-2 text-xs"/><datalist id="english-word-books">{BUILT_IN_WORD_BOOKS.map((book) => <option key={book} value={book}/>)}</datalist><Button size="sm" variant="outline" onClick={() => labelSelected('addTag')}>添加标签</Button><Button size="sm" variant="ghost" onClick={() => labelSelected('removeTag')}>移除标签</Button><Button size="sm" variant="outline" onClick={() => labelSelected('addBook')}>加入词书</Button><Button size="sm" variant="ghost" onClick={() => labelSelected('removeBook')}>移出词书</Button></>}</div>}
      {tab === 'book' && selectedWords.size > 0 && <div className="order-3 mb-3 grid grid-cols-[repeat(auto-fit,minmax(140px,1fr))] gap-2">{filteredEntries.filter((entry) => selectedWords.has(entry.word)).map((entry) => <button key={entry.word} onClick={() => toggleSelected(entry.word)} className="rounded-md border border-primary/40 bg-primary/5 px-3 py-2 text-left text-xs"><b>{entry.word}</b><span className="ml-2 text-muted-foreground">{formatNextReview(entry.nextReviewAt)}</span></button>)}</div>}
      {tab === 'review' && <section className="mx-auto mb-4 max-w-2xl rounded-xl border bg-card p-4"><div className="flex flex-wrap items-center gap-3"><div><p className="text-xs text-muted-foreground">今日进度</p><p className="text-xl font-semibold">{activity.today} / {dailyGoal}</p></div><div><p className="text-xs text-muted-foreground">连续学习</p><p className="text-xl font-semibold">{activity.streak} 天</p></div><label className="ml-auto flex items-center gap-2 text-xs text-muted-foreground">每日目标<input type="number" min="1" max="200" value={dailyGoal} onChange={(event) => setDailyGoal(Math.min(200, Math.max(1, Number(event.target.value) || 1)))} className="h-8 w-16 rounded-md border bg-background px-2 text-foreground"/></label></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.min(100, activity.today / dailyGoal * 100)}%` }}/></div><div className="mt-4 flex h-20 items-end gap-2">{activity.days.map((day) => { const max = Math.max(1, ...activity.days.map((item) => item.count)); return <div key={day.date} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-1"><span className="text-[10px] text-muted-foreground">{day.count || ''}</span><div className="w-full max-w-8 rounded-t bg-primary/70" style={{ height: `${Math.max(4, day.count / max * 48)}px` }}/><span className="text-[9px] text-muted-foreground">{day.date.slice(5)}</span></div>; })}</div></section>}
      {tab === 'book' && <div className="mb-4"><div className="grid grid-cols-2 gap-2 md:grid-cols-5">{[['总词数',stats.total],['生词',stats.newCount],['学习中',stats.learning],['已掌握',stats.mastered],['掌握率',`${stats.masteryRate}%`]].map(([label,value]) => <div key={label} className="rounded-lg border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div><div className="mt-3 flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => download(vocabularyToCsv(entries), 'english-vocabulary.csv', 'text/csv;charset=utf-8')}>导出 CSV</Button><Button size="sm" variant="outline" onClick={() => download(JSON.stringify(entries, null, 2), 'english-vocabulary.json', 'application/json;charset=utf-8')}>导出 JSON</Button></div></div>}
      {tab === 'graph' && <section className="h-full min-h-0 w-full overflow-hidden rounded-xl border bg-card"><Graph entries={entries} onPick={selectWord}/></section>}
    </div></main>
  </div>;
}
