import { describe, expect, it } from 'vitest';
import { addLookupHistory, buildVocabularyGraph, dueForReview, filterVocabulary, formatNextReview, importVocabularyJson, learningActivity, mergeEntry, mergeVocabulary, normalizeQuery, normalizeWord, parseLookupResponse, reviewEntry, updateEntryLabels, vocabularyStats, vocabularyToCsv } from '../src/plugins/english-lookup/model';

const response = JSON.stringify({ word: 'Serendipity', phonetic: '/ˌserənˈdɪpəti/', partOfSpeech: 'noun', definitions: [{ meaning: '意外发现美好事物的幸运', example: 'We met by serendipity.', translation: '我们因缘际会。' }], collocations: ['pure serendipity'], topics: ['discovery'], relations: [{ word: 'chance', type: 'synonym' }, { word: 'planned', type: 'antonym' }], memoryTip: '把它想成一次幸运偶遇。' });

describe('english lookup model', () => {
  it('normalizes safe English queries', () => expect(normalizeWord("  Mother's   Day! ")).toBe("mother's day"));
  it('parses structured AI output including fenced JSON', () => { const entry = parseLookupResponse(`\`\`\`json\n${response}\n\`\`\``, 'serendipity', 10); expect(entry.word).toBe('serendipity'); expect(entry.relations).toHaveLength(2); expect(entry.createdAt).toBe(10); });
  it('preserves the original creation time when updating', () => { const old = parseLookupResponse(response, 'serendipity', 10); const next = parseLookupResponse(response, 'serendipity', 20); expect(mergeEntry(old, next)).toMatchObject({ createdAt: 10, updatedAt: 20 }); });
  it('builds deduplicated word and topic relationships', () => { const entry = parseLookupResponse(response, 'serendipity'); const graph = buildVocabularyGraph([entry]); expect(graph.nodes.map((node) => node.id)).toContain('topic:discovery'); expect(graph.links.some((link) => link.value === 'synonym')).toBe(true); });
  it('rejects a response without definitions', () => expect(() => parseLookupResponse('{"word":"test"}', 'test')).toThrow(/缺少释义/));
  it('keeps sentence context while normalizing whitespace', () => expect(normalizeQuery('  I  ran into it.  ')).toBe('I ran into it.'));
  it('deduplicates recent history case-insensitively', () => expect(addLookupHistory([{ query: 'Test', word: 'test', lookedUpAt: 1 }], { query: 'test', word: 'test', lookedUpAt: 2 })).toEqual([{ query: 'test', word: 'test', lookedUpAt: 2 }]));
  it('schedules reviews from learner feedback', () => { const entry = parseLookupResponse(response, 'serendipity', 10); const reviewed = reviewEntry(entry, 'known', 100); expect(reviewed.familiarity).toBe('mastered'); expect(reviewed.nextReviewAt).toBeGreaterThan(100); expect(dueForReview([reviewed], 101)).toHaveLength(0); });
  it('parses word forms, definition parts of speech and comparisons', () => { const entry = parseLookupResponse(JSON.stringify({ word: 'run', definitions: [{ partOfSpeech: 'verb', meaning: '跑' }], forms: [{ label: '过去式', value: 'ran' }], comparisons: [{ word: 'jog', difference: '速度较慢' }] }), 'run'); expect(entry.definitions[0].partOfSpeech).toBe('verb'); expect(entry.forms).toEqual([{ label: '过去式', value: 'ran' }]); expect(entry.comparisons?.[0].word).toBe('jog'); });
  it('summarizes learning progress and exports escaped CSV', () => { const entry = { ...parseLookupResponse(response, 'serendipity'), familiarity: 'mastered' as const, reviewCount: 3 }; expect(vocabularyStats([entry])).toMatchObject({ total: 1, mastered: 1, reviews: 3, masteryRate: 100 }); expect(vocabularyToCsv([entry])).toContain('"serendipity"'); });
  it('normalizes spelling suggestions and formats review dates', () => { const entry = parseLookupResponse(JSON.stringify({ word: 'receive', definitions: [{ meaning: '收到' }], suggestions: [' Receive ', 'receipt'] }), 'recieve'); expect(entry.suggestions).toEqual(['receipt']); expect(formatNextReview(86_400_001, 1)).toBe('明日复习'); });
  it('validates and merges imported vocabulary', () => { const imported = importVocabularyJson('[{"word":"Test","definitions":[{"meaning":"测试"}]}]', 20); expect(imported[0].word).toBe('test'); expect(mergeVocabulary([], imported)).toHaveLength(1); expect(() => importVocabularyJson('{}')).toThrow(/单词数组/); });
  it('calculates daily activity and streaks', () => { const now = new Date(2026, 7, 13, 12).getTime(); const yesterday = new Date(2026, 7, 12, 12).getTime(); const activity = learningActivity([{ word: 'a', rating: 'known', reviewedAt: now }, { word: 'b', rating: 'hard', reviewedAt: yesterday }], now); expect(activity.today).toBe(1); expect(activity.streak).toBe(2); expect(activity.days).toHaveLength(7); });
  it('updates and filters tags and word books', () => { const entry = updateEntryLabels(parseLookupResponse(response, 'serendipity'), { addTags: ['重点'], addBooks: ['IELTS'] }); expect(filterVocabulary([entry], '重点', 'IELTS')).toHaveLength(1); expect(updateEntryLabels(entry, { removeTags: ['重点'] }).tags).toEqual([]); });
  it('filters graph relations and focuses one-hop neighbors', () => { const entry = parseLookupResponse(response, 'serendipity'); const graph = buildVocabularyGraph([entry], new Set(['synonym']), 'serendipity'); expect(graph.links.every((link) => link.value === 'synonym')).toBe(true); expect(graph.nodes.map((node) => node.name)).not.toContain('planned'); });
});
