import { useEffect, useMemo, useRef, useState } from 'react';
import { Download, FileSearch, LockKeyhole, RotateCcw, ShieldCheck, Upload } from 'lucide-react';
import { analyzeContract, buildMarkdownReport, type ContractAnalysis, type PartyRole, type Severity } from './core';
import { parseContractFile } from './parser';
import './styles.css';

const roles: PartyRole[] = ['甲方', '乙方', '买方', '卖方', '服务商', '客户'];
const labels: Record<Severity, string> = { high: '高风险', medium: '中风险', low: '低风险' };
function download(name: string, content: string, type: string) { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([content], { type })); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 500); }

export function ContractGuardPanel() {
  const picker = useRef<HTMLInputElement>(null); const [role, setRole] = useState<PartyRole>('乙方');
  const [result, setResult] = useState<ContractAnalysis>(); const [selected, setSelected] = useState<string>();
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const risk = result?.risks.find(item => item.id === selected) ?? result?.risks[0];
  const clause = result?.clauses.find(item => item.id === risk?.clauseId);
  const counts = useMemo(() => ({ high: result?.risks.filter(r => r.severity === 'high').length ?? 0, medium: result?.risks.filter(r => r.severity === 'medium').length ?? 0, low: result?.risks.filter(r => r.severity === 'low').length ?? 0 }), [result]);
  async function importFile(file?: File) { if (!file) return; setBusy(true); setError(''); try { const text = await parseContractFile(file); const next = analyzeContract(file.name, text, role); setResult(next); setSelected(next.risks[0]?.id); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  useEffect(() => { const open = () => picker.current?.click(); window.addEventListener('contract-guard:import', open); return () => window.removeEventListener('contract-guard:import', open); }, []);
  if (!result) return <main className="cg cg-home"><section className="cg-hero"><div className="cg-brand"><ShieldCheck /> ContractGuard</div><h1>AI 合同风险分析</h1><p>从条款到风险、证据与修改建议，一次完成可追溯审查。</p><label>我的立场<select value={role} onChange={e => setRole(e.target.value as PartyRole)}>{roles.map(item => <option key={item}>{item}</option>)}</select></label><button className="cg-primary" onClick={() => picker.current?.click()} disabled={busy}><Upload size={18}/>{busy ? '正在解析…' : '导入合同'}</button><input ref={picker} hidden type="file" accept=".pdf,.docx,.txt,.md" onChange={e => void importFile(e.target.files?.[0])}/><small>支持 PDF / DOCX / TXT · 文件默认仅在本机处理</small>{error && <div className="cg-error">{error}</div>}</section><section className="cg-privacy"><LockKeyhole/><div><strong>隐私保护</strong><p>规则分析不会上传合同；扫描 PDF 需先 OCR。结果仅保留在当前会话，可导出为 Markdown 或 JSON。</p></div></section></main>;
  return <main className="cg"><header className="cg-header"><div><strong>{result.name}</strong><span>{result.role}视角 · {result.clauses.length} 个条款</span></div><div><button onClick={() => download(`${result.name}-风险报告.md`, buildMarkdownReport(result), 'text/markdown;charset=utf-8')}><Download size={15}/> Markdown</button><button onClick={() => download(`${result.name}-风险数据.json`, JSON.stringify(result, null, 2), 'application/json')}><Download size={15}/> JSON</button><button onClick={() => setResult(undefined)}><RotateCcw size={15}/> 新审查</button></div></header><section className="cg-summary"><div className="cg-score"><b>{result.healthScore}</b><span>/ 100 合同健康度</span></div>{(['high','medium','low'] as Severity[]).map(level => <div className={`cg-count ${level}`} key={level}><b>{counts[level]}</b><span>{labels[level]}</span></div>)}</section><section className="cg-workspace"><aside><h2>风险列表 <em>{result.risks.length}</em></h2>{result.risks.length ? result.risks.map(item => <button key={item.id} className={item.id === risk?.id ? 'active' : ''} onClick={() => setSelected(item.id)}><i className={item.severity}/><span><b>{item.title}</b><small>{result.clauses.find(c => c.id === item.clauseId)?.section}</small></span></button>) : <div className="cg-empty">规则库未发现明确风险，仍建议人工复核。</div>}</aside><article><h2><FileSearch size={17}/> 合同原文</h2>{result.clauses.map(item => <section key={item.id} className={item.id === clause?.id ? 'highlight' : ''}><b>{item.section} {item.title}</b><p>{item.content}</p></section>)}</article><aside className="cg-detail"><h2>审查意见</h2>{risk ? <><span className={`cg-badge ${risk.severity}`}>{labels[risk.severity]} · {risk.score}</span><h3>{risk.title}</h3><h4>证据</h4><blockquote>{risk.evidence}</blockquote><h4>为什么有风险</h4><p>{risk.reason}</p><h4>可能影响</h4><p>{risk.impact}</p><h4>修改建议</h4><p>{risk.recommendation}</p><div className="cg-suggestion">{risk.suggestedText}</div><small>置信度 {Math.round(risk.confidence * 100)}% · 结果不构成法律意见</small></> : <div className="cg-empty">请选择一项风险。</div>}</aside></section></main>;
}
