import { useMemo, useState } from 'react';
import { ArrowRight, BookOpen, CheckCircle, Search } from '@/components/icons';
import { CALCPATH_SYLLABUS, syllabusStats } from './syllabus';

export function CourseCatalog({ onOpen }: { onOpen: (id: string) => void }) {
  const [query, setQuery] = useState('');
  const chapters = useMemo(() => CALCPATH_SYLLABUS.filter(chapter => `${chapter.title} ${chapter.sections.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase())), [query]);
  return <div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-5"><div><div className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-700">CalcPath 完整课程</div><h1 className="mt-2 text-3xl font-semibold">从预备知识到向量微积分</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">参考经典大学微积分的主题骨架，加入高中先修诊断、交互图形与 AI 引导。共 {syllabusStats.chapters} 章、{syllabusStats.sections} 节。</p></div><label className="flex w-72 items-center gap-2 rounded-xl border bg-white px-3 dark:bg-slate-900"><Search className="h-4 w-4 text-slate-400"/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索知识点" className="h-10 min-w-0 flex-1 bg-transparent text-sm outline-none"/></label></header>
    <div className="mt-7 space-y-8">{(['单变量基础','单变量进阶','多变量与向量','微分方程'] as const).map(phase => { const items=chapters.filter(item=>item.phase===phase); if (!items.length) return null; return <section key={phase}><div className="mb-3 flex items-center gap-2"><BookOpen className="h-4 w-4 text-emerald-700"/><h2 className="font-semibold">{phase}</h2><span className="text-xs text-slate-400">{items.length} 章</span></div><div className="grid gap-4 md:grid-cols-2">{items.map((chapter,index)=><article key={chapter.id} className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><div className="flex items-start justify-between gap-4"><div><div className="text-xs text-slate-400">第 {CALCPATH_SYLLABUS.indexOf(chapter)+1} 章</div><h3 className="mt-1 text-lg font-semibold">{chapter.title}</h3></div>{['functions','limits','derivatives','integrals'].includes(chapter.id) && <button onClick={()=>onOpen(chapter.id)} className="flex shrink-0 items-center gap-1 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-800 dark:bg-emerald-950">进入课程<ArrowRight className="h-3 w-3"/></button>}</div>{chapter.bridge&&<p className="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800 dark:bg-amber-950">高中桥梁：{chapter.bridge}</p>}<ul className="mt-4 grid gap-2 sm:grid-cols-2">{chapter.sections.map(section=><li key={section} className="flex gap-2 text-xs leading-5 text-slate-500"><CheckCircle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-500"/>{section}</li>)}</ul></article>)}</div></section>})}</div>
  </div>;
}
