import { ArrowRight, BookOpen, CheckCircle, Info } from '@/components/icons';
import { LESSONS } from './lessons';
import { AITutor } from './AITutor';
import type { CalcPathState, Problem } from './types';

export function KnowledgeStudio({ nodeId, state, problem, onBack, onPractice }: { nodeId: string; state: CalcPathState; problem?: Problem; onBack: () => void; onPractice: (problem?: Problem) => void }) {
  const lesson = LESSONS[nodeId];
  if (!lesson) return <div className="p-8">课程内容正在建设中。</div>;
  const mastery = problem ? state.skillStates[problem.skillId]?.mastery ?? 0 : 0;
  return <div className="mx-auto max-w-6xl">
    <button onClick={onBack} className="text-sm text-slate-500 hover:text-slate-800">← 返回能力地图</button>
    <header className="mt-5 overflow-hidden rounded-[30px] bg-[#123b38] p-7 text-white md:p-9"><div className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-200/70">{lesson.stage}</div><div className="mt-4 grid gap-7 md:grid-cols-[1fr_260px]"><div><h1 className="text-4xl font-semibold tracking-tight">{lesson.title}</h1><p className="mt-3 text-xl text-emerald-50/90">{lesson.question}</p><p className="mt-5 max-w-2xl text-sm leading-7 text-emerald-50/70">{lesson.insight}</p></div><div className="rounded-2xl bg-white/10 p-5"><div className="text-xs text-emerald-100/60">当前掌握</div><div className="mt-1 text-3xl font-semibold">{Math.round(mastery * 100)}%</div><div className="mt-3 h-1.5 rounded bg-white/10"><div className="h-full rounded bg-amber-400" style={{ width: `${mastery * 100}%` }} /></div><button onClick={() => onPractice(problem)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-[#123b38]">开始练习 <ArrowRight className="h-4 w-4" /></button></div></div></header>
    <div className="mt-6 grid gap-6 lg:grid-cols-[220px_1fr]">
      <aside className="h-fit rounded-2xl border bg-white p-5 dark:bg-slate-900"><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">需要先会</div><div className="mt-4 space-y-3">{lesson.prerequisites.map(item => <div key={item} className="flex items-center gap-2 text-sm"><CheckCircle className="h-4 w-4 text-emerald-600" />{item}</div>)}</div><div className="mt-6 border-t pt-5"><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">学完去哪里</div><div className="mt-3 flex flex-wrap gap-2">{lesson.next.map(item => <span key={item} className="rounded-full bg-violet-50 px-3 py-1 text-xs text-violet-700 dark:bg-violet-950">{item}</span>)}</div></div></aside>
      <div className="space-y-6"><section className="rounded-2xl border bg-white p-6 dark:bg-slate-900"><div className="flex items-center gap-2 text-sm font-semibold text-emerald-700"><BookOpen className="h-4 w-4" />核心概念</div><div className="mt-5 grid gap-4 md:grid-cols-2">{lesson.concepts.map(concept => <article key={concept.title} className="rounded-2xl bg-slate-50 p-5 dark:bg-slate-950"><h2 className="font-semibold">{concept.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{concept.body}</p>{concept.formula && <div className="mt-4 rounded-xl bg-white px-4 py-3 text-center font-serif text-lg dark:bg-slate-900">{concept.formula}</div>}</article>)}</div></section>
      <section className="rounded-2xl border bg-white p-6 dark:bg-slate-900"><div className="flex items-center gap-2 text-sm font-semibold text-amber-700"><Info className="h-4 w-4" />跟着例题建立连接</div><h2 className="mt-4 text-xl font-semibold">{lesson.example.question}</h2><div className="mt-5 space-y-3">{lesson.example.steps.map((step, index) => <div key={step} className="flex gap-3"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-amber-100 text-xs font-semibold text-amber-800">{index + 1}</span><span className="text-sm leading-6 text-slate-600 dark:text-slate-300">{step}</span></div>)}</div><div className="mt-5 rounded-xl bg-emerald-50 p-4 font-medium text-emerald-900 dark:bg-emerald-950 dark:text-emerald-100">结论：{lesson.example.answer}</div></section><AITutor lesson={lesson} mastery={mastery} /></div>
    </div>
  </div>;
}
