import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowRight, BookOpen, CheckCircle, Sparkles } from '@/components/icons';
import { LESSONS } from './lessons';
import { AITutor } from './AITutor';
import { MathVisualLab } from './MathVisualLab';
import type { CalcPathState, Problem } from './types';

const STEPS = ['先想一想', '动手观察', '形成概念', '跟随推导', '问问导师', '理解检查'] as const;

export function KnowledgeStudio({ nodeId, state, problem, onBack, onPractice }: { nodeId: string; state: CalcPathState; problem?: Problem; onBack: () => void; onPractice: (problem?: Problem) => void }) {
  const lesson = LESSONS[nodeId];
  const [step, setStep] = useState(0);
  const [prediction, setPrediction] = useState<string>();
  useEffect(() => { setStep(0); setPrediction(undefined); }, [nodeId]);
  if (!lesson) return <div className="p-8">课程内容正在建设中。</div>;
  const mastery = problem ? state.skillStates[problem.skillId]?.mastery ?? 0 : 0;
  const exposition = lesson.exposition ?? lesson.concepts.map((item, index) => ({ heading: `${index + 1}. ${item.title}`, paragraphs: [item.body], definition: undefined, formula: item.formula, caution: undefined }));
  const next = () => setStep(value => Math.min(STEPS.length - 1, value + 1));
  return <div className="mx-auto max-w-6xl">
    <button onClick={onBack} className="text-sm text-slate-500 hover:text-slate-800">← 返回能力地图</button>
    <header className="mt-5 overflow-hidden rounded-[30px] bg-[#123b38] p-7 text-white md:p-9"><div className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-200/70">{lesson.stage} · 引导课</div><div className="mt-4 flex flex-wrap items-end justify-between gap-6"><div><h1 className="text-4xl font-semibold tracking-tight">{lesson.title}</h1><p className="mt-3 text-xl text-emerald-50/90">{lesson.question}</p></div><div className="min-w-52 rounded-2xl bg-white/10 p-4"><div className="flex justify-between text-xs text-emerald-100/70"><span>本课进度</span><span>{step + 1}/{STEPS.length}</span></div><div className="mt-3 h-1.5 rounded bg-white/10"><div className="h-full rounded bg-amber-400 transition-all" style={{ width: `${(step + 1) / STEPS.length * 100}%` }} /></div></div></div></header>
    <nav className="mt-5 grid grid-cols-3 gap-2 md:grid-cols-6">{STEPS.map((item, index) => <button key={item} onClick={() => index <= step && setStep(index)} className={`rounded-xl border px-2 py-3 text-xs transition ${index === step ? 'border-emerald-700 bg-emerald-50 font-semibold text-emerald-800 dark:bg-emerald-950' : index < step ? 'border-emerald-200 bg-white text-emerald-700 dark:bg-slate-900' : 'cursor-default border-slate-200 text-slate-400 dark:border-slate-800'}`}><span className="mr-1">{index < step ? '✓' : index + 1}.</span>{item}</button>)}</nav>
    <div className="mt-6 grid gap-6 lg:grid-cols-[220px_1fr]">
      <aside className="h-fit rounded-2xl border bg-white p-5 dark:bg-slate-900"><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">这节课不是背公式</div><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{lesson.insight}</p>{lesson.sections && <div className="mt-6 border-t pt-5"><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">本章知识点</div><ol className="mt-3 max-h-52 space-y-2 overflow-auto pr-1">{lesson.sections.map((item,index)=><li key={item} className="flex gap-2 text-xs leading-5 text-slate-500"><span className="text-emerald-600">{index+1}.</span>{item}</li>)}</ol></div>}<div className="mt-6 border-t pt-5"><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">会用到</div><div className="mt-3 space-y-2">{lesson.prerequisites.map(item => <div key={item} className="flex items-center gap-2 text-sm"><CheckCircle className="h-4 w-4 text-emerald-600" />{item}</div>)}</div></div><div className="mt-6 border-t pt-5"><div className="text-xs text-slate-400">当前掌握</div><div className="mt-1 text-2xl font-semibold">{Math.round(mastery * 100)}%</div></div></aside>
      <div>
        {step === 0 && <LessonCard eyebrow="从一个困惑开始" title={lesson.question}><p className="max-w-2xl text-base leading-8 text-slate-600 dark:text-slate-300">先不要寻找公式。根据你已有的高中知识，猜一猜下面哪种说法更接近你的直觉？</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{['它只是另一套计算规则', '它是在描述变化发生的过程'].map(item => <button key={item} onClick={() => setPrediction(item)} className={`rounded-2xl border p-5 text-left text-sm ${prediction === item ? 'border-amber-500 bg-amber-50 dark:bg-amber-950' : 'bg-white hover:border-slate-400 dark:bg-slate-950'}`}>{item}</button>)}</div>{prediction && <div className="mt-5 rounded-2xl bg-blue-50 p-5 text-sm leading-7 text-blue-900 dark:bg-blue-950 dark:text-blue-100">先保留这个预测。下一步不要急着判断对错，我们用图形观察它。</div>}<Continue disabled={!prediction} onClick={next}>带着预测去观察</Continue></LessonCard>}
        {step === 1 && <LessonCard eyebrow="可操作的数学实验" title="拖动参数，寻找不变的规律"><p className="mb-6 text-sm leading-7 text-slate-500">先多拖动几次。关注哪些量在变化、哪些关系始终没有改变，然后用自己的话描述。</p><MathVisualLab nodeId={nodeId} /><Continue onClick={next}>我观察到了，继续</Continue></LessonCard>}
        {step === 2 && <LessonCard eyebrow="教材讲解" title={`${lesson.title}：定义、性质与意义`}><div className="mb-7 rounded-2xl border bg-slate-50 p-5 dark:bg-slate-950"><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">本节目录</div><ol className="mt-3 grid gap-2 md:grid-cols-2">{exposition.map(section => <li key={section.heading} className="text-sm text-slate-600 dark:text-slate-300">{section.heading}</li>)}</ol></div><div className="space-y-9">{exposition.map(section => <article key={section.heading} className="border-b border-slate-100 pb-8 last:border-0 dark:border-slate-800"><h3 className="text-xl font-semibold">{section.heading}</h3>{section.paragraphs.map(paragraph => <p key={paragraph} className="mt-4 text-[15px] leading-8 text-slate-600 dark:text-slate-300">{paragraph}</p>)}{section.definition && <div className="mt-5 rounded-2xl border-l-4 border-emerald-600 bg-emerald-50 p-5 dark:bg-emerald-950/50"><div className="text-xs font-semibold uppercase tracking-wider text-emerald-700 dark:text-emerald-300">定义</div><p className="mt-2 text-sm leading-7 text-emerald-950 dark:text-emerald-100">{section.definition}</p></div>}{section.formula && <div className="mt-5 rounded-2xl bg-slate-950 px-5 py-5 text-center font-serif text-xl text-white">{section.formula}</div>}{section.caution && <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-7 text-amber-950 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-100"><strong>注意：</strong>{section.caution}</div>}</article>)}</div><div className="mt-5 rounded-2xl border-l-4 border-amber-500 bg-amber-50 p-5 text-sm leading-7 text-amber-950 dark:bg-amber-950 dark:text-amber-100">公式是现象与逻辑的压缩表达。先理解对象、条件与结论，再使用计算规则。</div><Continue onClick={next}>进入完整例题</Continue></LessonCard>}
        {step === 3 && <LessonCard eyebrow="把每一步都连起来" title={lesson.example.question}><div className="mt-2 space-y-4">{lesson.example.steps.map((item, index) => <div key={item} className="flex gap-4 rounded-2xl bg-slate-50 p-5 dark:bg-slate-950"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-amber-100 text-sm font-semibold text-amber-800">{index + 1}</span><div><div className="text-xs text-slate-400">{index === 0 ? '调用已有知识' : index === lesson.example.steps.length - 1 ? '完成概念跨越' : '保持等价关系'}</div><p className="mt-1 text-sm leading-6">{item}</p></div></div>)}</div><div className="mt-5 rounded-xl bg-emerald-50 p-5 font-medium text-emerald-900 dark:bg-emerald-950 dark:text-emerald-100">所以得到：{lesson.example.answer}</div><Continue onClick={next}>有不明白的，问导师</Continue></LessonCard>}
        {step === 4 && <div><AITutor lesson={lesson} mastery={mastery} /><Continue onClick={next}>我准备好检查理解了</Continue></div>}
        {step === 5 && <LessonCard eyebrow="不是考试，只是确认理解" title="用一个小问题把知识说出来"><div className="rounded-2xl bg-emerald-50 p-6 dark:bg-emerald-950/40"><div className="flex items-center gap-2 font-semibold text-emerald-800 dark:text-emerald-200"><Sparkles className="h-4 w-4" />先尝试不用公式解释</div><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">如果向一位高中同学解释“{lesson.title}”，你会怎样描述它解决的问题？想清楚后，再用一道短题确认。</p></div><button onClick={() => onPractice(problem)} disabled={!problem} className="mt-6 flex items-center gap-2 rounded-xl bg-[#123b38] px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">做 1 道理解检查 <ArrowRight className="h-4 w-4" /></button>{!problem && <p className="mt-3 text-xs text-slate-400">这个未来方向目前只有导览内容，练习将在课程展开后开放。</p>}</LessonCard>}
      </div>
    </div>
  </div>;
}

function LessonCard({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) { return <section className="rounded-3xl border bg-white p-7 shadow-sm dark:bg-slate-900 md:p-9"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-emerald-700"><BookOpen className="h-4 w-4" />{eyebrow}</div><h2 className="mt-4 text-2xl font-semibold">{title}</h2><div className="mt-6">{children}</div></section>; }
function Continue({ children, onClick, disabled = false }: { children: ReactNode; onClick: () => void; disabled?: boolean }) { return <div className="mt-7 flex justify-end"><button disabled={disabled} onClick={onClick} className="flex items-center gap-2 rounded-xl bg-[#d08332] px-5 py-3 text-sm font-semibold text-white disabled:opacity-35">{children}<ArrowRight className="h-4 w-4" /></button></div>; }
