export interface LessonContent {
  id: string; title: string; stage: string; question: string; insight: string; prerequisites: string[];
  concepts: { title: string; body: string; formula?: string }[];
  example: { question: string; steps: string[]; answer: string };
  next: string[];
}

export const LESSONS: Record<string, LessonContent> = {
  algebra: { id: 'algebra', title: '代数运算', stage: '高中数学地基', question: '为什么极限题经常先考你的代数？', insight: '极限中的 0/0 通常不是答案，而是提醒你：表达式需要先变形。', prerequisites: ['数与式', '乘法公式'], concepts: [{ title: '平方差', body: '两个平方相减可以拆成一对共轭因式。', formula: 'a² − b² = (a − b)(a + b)' }, { title: '等价变形', body: '在允许的定义域内改变形式，但不改变表达式的值。' }], example: { question: '化简 (x²−4)/(x−2)，x≠2', steps: ['识别 x²−4 是平方差', '分解为 (x−2)(x+2)', '约去公共因子 x−2'], answer: 'x + 2' }, next: ['无限趋近', '极限与连续'] },
  functions: { id: 'functions', title: '函数语言', stage: '高中数学地基', question: '微积分究竟在研究什么？', insight: '函数不是一个算式，而是一台描述“一个量如何随另一个量变化”的机器。', prerequisites: ['集合与对应', '坐标系'], concepts: [{ title: '输入与输出', body: '定义域规定允许输入什么，函数值描述对应的输出。', formula: 'x ↦ f(x)' }, { title: '复合函数', body: '一个变化过程的输出，可以成为另一个过程的输入。', formula: '(f∘g)(x)=f(g(x))' }], example: { question: 'f(x)=2x+3，输入 4 时发生了什么？', steps: ['把 4 送入函数机器', '先乘 2 得到 8', '再加 3'], answer: 'f(4)=11' }, next: ['无限趋近', '变化率', '导数'] },
  graphs: { id: 'graphs', title: '图像直觉', stage: '高中数学地基', question: '一张图像能告诉我们哪些变化？', insight: '图像把函数的整体趋势、局部陡峭程度和趋近行为同时呈现出来。', prerequisites: ['坐标系', '函数语言'], concepts: [{ title: '平移与伸缩', body: '参数变化会以可预测的方式移动或拉伸图像。' }, { title: '局部观察', body: '不断放大一条光滑曲线，它在局部会越来越像直线。' }], example: { question: '比较 y=x² 在 x=1 与 x=3 附近的陡峭程度', steps: ['观察相同水平步长', '比较对应的竖直变化', 'x=3 附近变化更快'], answer: 'x=3 附近更陡' }, next: ['变化率', '极限与连续'] },
  trig: { id: 'trig', title: '三角 · 指对数', stage: '高中数学地基', question: '为什么大学微积分总离不开这些函数？', insight: '周期变化、指数增长和对数尺度是自然与工程问题最常见的三类模型。', prerequisites: ['函数语言', '单位圆'], concepts: [{ title: '周期变化', body: 'sin 与 cos 描述重复出现的变化。' }, { title: '增长与反函数', body: '指数描述按比例增长，对数回答增长了多少个数量级。' }], example: { question: '人口每期增长 5%，适合哪类函数？', steps: ['每期乘以固定比例 1.05', '连续相乘形成指数结构'], answer: '指数函数' }, next: ['变化率', '导数', '微分方程'] },
  approach: { id: 'approach', title: '无限趋近', stage: '思维桥梁', question: '不能直接到达，也能确定结果吗？', insight: '极限关心的是靠近某点时的稳定趋势，而不一定是那个点本身的取值。', prerequisites: ['函数语言', '图像直觉', '代数运算'], concepts: [{ title: '趋近过程', body: '从左右两侧不断缩短距离，观察输出是否靠近同一个数。' }, { title: '可去间断点', body: '点上没有定义，并不妨碍附近存在稳定趋势。' }], example: { question: 'x 趋近 2 时，(x²−4)/(x−2) 趋近多少？', steps: ['先化简为 x+2', '让 x 越来越接近 2', '输出越来越接近 4'], answer: '4' }, next: ['极限与连续'] },
  rate: { id: 'rate', title: '变化率', stage: '思维桥梁', question: '平均速度如何变成某一瞬间的速度？', insight: '不断缩短时间区间，平均变化率会逼近瞬时变化率。', prerequisites: ['函数语言', '斜率', '无限趋近'], concepts: [{ title: '平均变化率', body: '用一段区间的输出变化除以输入变化。', formula: 'Δy / Δx' }, { title: '瞬时变化率', body: '让区间长度趋近于零，得到某一点的局部变化。' }], example: { question: '位置 s(t)=t²，从 t=2 到 t=2+h 的平均速度', steps: ['计算 [s(2+h)−s(2)]/h', '展开并化简为 4+h', '令 h 趋近 0'], answer: '瞬时速度为 4' }, next: ['极限与连续', '导数'] },
  limits: { id: 'limits', title: '极限与连续', stage: '微积分核心', question: '如何严格描述“越来越接近”？', insight: '极限为瞬时变化和无限累积提供共同语言，是微积分的逻辑入口。', prerequisites: ['无限趋近', '函数语言', '代数运算'], concepts: [{ title: '函数极限', body: '输入靠近目标时，输出可以稳定靠近某个值。', formula: 'limₓ→ₐ f(x)=L' }, { title: '连续', body: '极限存在、函数值存在，并且二者相等。' }], example: { question: '判断 f(x)=x² 在 x=2 是否连续', steps: ['函数在 2 有定义', '极限为 4', '函数值 f(2)=4'], answer: '连续' }, next: ['导数', '级数与 Taylor'] },
  derivatives: { id: 'derivatives', title: '导数', stage: '微积分核心', question: '如何测量一个瞬间的变化？', insight: '导数统一了切线斜率、瞬时速度、边际成本和优化条件。', prerequisites: ['极限与连续', '变化率', '函数图像'], concepts: [{ title: '导数定义', body: '差商在区间长度趋近零时的极限。', formula: "f′(x)=limₕ→₀ [f(x+h)−f(x)]/h" }, { title: '局部线性', body: '光滑函数在足够小的范围内可以用切线近似。' }], example: { question: '用幂法则求 f(x)=x³ 的导数', steps: ['指数 3 移到系数', '原指数减 1'], answer: 'f′(x)=3x²' }, next: ['积分', '多元微积分', '微分方程'] },
  integrals: { id: 'integrals', title: '积分', stage: '微积分核心', question: '无数个微小量如何组成一个整体？', insight: '积分把连续累积转化为可计算的极限，并通过基本定理与导数互相连接。', prerequisites: ['导数', '面积', '求和'], concepts: [{ title: '黎曼和', body: '把区域切成许多窄条，面积和在宽度趋近零时形成积分。' }, { title: '微积分基本定理', body: '求导与积分在适当条件下互为逆运算。', formula: '∫ₐᵇ f(x)dx = F(b)−F(a)' }], example: { question: '求 ∫2x dx', steps: ['寻找导数等于 2x 的函数', 'x² 的导数是 2x', '补上积分常数'], answer: 'x²+C' }, next: ['微分方程', '概率', '多元积分'] },
};

const future = (id: string, title: string, question: string, prerequisites: string[]) => ({ id, title, stage: '大学数学方向', question, insight: '这里是当前微积分路径继续生长的方向。完成前置能力后，CalcPath 会展开为可学习的完整课程。', prerequisites, concepts: [{ title: '学习目标', body: question }, { title: '前置路线', body: prerequisites.join(' → ') }], example: { question: '当前阶段', steps: ['建立高中数学地基', '跨过极限与变化率桥梁', '掌握导数与积分'], answer: '完成前置路径后解锁' }, next: [] });
LESSONS.multivariable = future('multivariable', '多元微积分', '当输出同时受多个变量影响时，如何描述变化？', ['导数', '向量']);
LESSONS.diffeq = future('diffeq', '微分方程', '已知变化规律，如何反推出系统随时间的状态？', ['导数', '积分']);
LESSONS.series = future('series', '级数与 Taylor', '如何用无限多项式逼近复杂函数？', ['极限', '高阶导数']);
LESSONS.linear = future('linear', '线代 · 概率', '微积分如何进入高维空间和随机世界？', ['积分', '向量与矩阵']);
