import React, { Children, useCallback, useEffect, useMemo, useState } from 'react';
import { Button, Empty, Input, Modal, Select, Spin, Tag, message } from 'antd';
import MonacoEditor, { type OnMount } from '@monaco-editor/react';
import { ChevronDown, Code, Database, ExternalLink, FolderOpen, History, Network, RefreshCw, Rows3, Search, XCircle } from '@/components/icons';
import { buildQualityGate, gitImpactMarkdown, type AnalysisNode, type ApiEndpoint, type CodeVisualizerProjectHistory, type CodeVisualizerScanSnapshot, type CodeVisualizerSnapshotDiff, type RepositoryAnalysis } from '../../core/code-visualizer';
import { RelationshipGraph } from './RelationshipGraph';
import { ErDiagram } from './ErDiagram';
import { configureMonaco } from '@/lib/monaco-setup';

configureMonaco();

const METHOD_COLOR: Record<string, string> = { GET: 'green', POST: 'blue', PUT: 'orange', PATCH: 'gold', DELETE: 'red' };
const KIND_LABEL: Record<AnalysisNode['kind'], string> = { frontend: 'Vue', endpoint: '接口', controller: 'Controller', service: 'Service', repository: 'Repository', model: 'Model', database: '数据库' };
type SourceTab = { path: string; content: string; line: number; endLine: number; label: string; kind: AnalysisNode['kind'] };

export function CodeVisualizerPanel(): JSX.Element {
  const [result, setResult] = useState<RepositoryAnalysis | null>(null);
  const [selected, setSelected] = useState<ApiEndpoint | null>(null);
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState<CodeVisualizerProjectHistory[]>([]);
  const [snapshots, setSnapshots] = useState<CodeVisualizerScanSnapshot[]>([]);
  const [collapsedGroups, setCollapsedGroups] = useState<Set<string>>(() => new Set());
  const [architectureOpen, setArchitectureOpen] = useState(false);
  const [diffOpen, setDiffOpen] = useState(false);
  const [diffFrom, setDiffFrom] = useState<string>();
  const [diffTo, setDiffTo] = useState<string>();
  const [snapshotDiff, setSnapshotDiff] = useState<CodeVisualizerSnapshotDiff | null>(null);
  const [sourceTabs, setSourceTabs] = useState<SourceTab[]>([]);
  const [activeSourcePath, setActiveSourcePath] = useState<string | null>(null);
  const [gitBase, setGitBase] = useState('HEAD~1');
  const source = sourceTabs.find((tab) => tab.path === activeSourcePath) ?? null;
  const endpoints = useMemo(() => result?.endpoints.filter((item) => `${item.method} ${item.path} ${item.handler}`.toLowerCase().includes(query.toLowerCase())) ?? [], [query, result]);
  const endpointGroups = useMemo(() => {
    const groups = new Map<string, ApiEndpoint[]>();
    for (const endpoint of endpoints) { const category = endpointCategory(endpoint.path); groups.set(category, [...(groups.get(category) ?? []), endpoint]); }
    return [...groups.entries()].sort(([left], [right]) => left.localeCompare(right));
  }, [endpoints]);
  const globalGraph = useMemo(() => result ? buildGlobalGraph(result) : null, [result]);

  const loadHistory = useCallback(() => {
    void window.electronAPI.codeVisualizer.history.list().then(setHistory).catch(() => setHistory([]));
  }, []);
  useEffect(loadHistory, [loadHistory]);

  const chooseAndScan = async (): Promise<void> => {
    try {
      const chosen = await window.electronAPI.codeVisualizer.repository.select();
      if (!chosen.ok || !chosen.rootPath) return;
      await scan(chosen.rootPath);
    } catch (error) { message.error(error instanceof Error ? error.message : String(error)); }
  };
  const scan = async (rootPath: string): Promise<void> => {
    setLoading(true); setSelected(null); setSourceTabs([]); setActiveSourcePath(null);
    try { const next = await window.electronAPI.codeVisualizer.repository.scan(rootPath); next.qualityGate = buildQualityGate(next); setResult(next); if (next.endpoints[0]) setSelected(next.endpoints[0]); setSnapshots(await window.electronAPI.codeVisualizer.snapshot.list(rootPath)); loadHistory(); }
    catch (error) { message.error(`扫描失败：${error instanceof Error ? error.message : String(error)}`); }
    finally { setLoading(false); }
  };
  const openSource = useCallback(async (node: AnalysisNode): Promise<void> => {
    if (!result || !node.location) return;
    try { const file = await window.electronAPI.codeVisualizer.source.read(result.rootPath, node.location.file); const line = node.location?.line ?? 1; setSourceTabs((tabs) => [...tabs.filter((tab) => tab.path !== file.path), { ...file, line, endLine: Math.max(line, node.location?.endLine ?? line), label: node.label, kind: node.kind }]); setActiveSourcePath(file.path); }
    catch (error) { message.error(error instanceof Error ? error.message : String(error)); }
  }, [result]);
  const importRuntime = useCallback(async (): Promise<void> => {
    if (!result) return;
    try {
      const imported = await window.electronAPI.codeVisualizer.runtime.import(result.rootPath);
      if (!imported.ok) return;
      const next = { ...result, runtimeMetrics: imported.metrics };
      setResult(next);
      setSelected((current) => current ? next.endpoints.find((item) => item.id === current.id) ?? current : null);
      message.success(`已导入 ${imported.metrics.length} 条接口运行指标`);
    } catch (error) { message.error(error instanceof Error ? error.message : String(error)); }
  }, [result]);
  const importOpenApi = useCallback(async (): Promise<void> => {
    if (!result) return;
    const imported = await window.electronAPI.codeVisualizer.openApi.import(result.rootPath, result);
    if (imported.ok && imported.report) { const next = { ...result, openApi: imported.report }; next.qualityGate = buildQualityGate(next, next.coverage); setResult(next); message.success('OpenAPI 契约对比完成'); }
  }, [result]);
  const analyzeGitImpact = useCallback(async (): Promise<void> => {
    if (!result) return;
    try { const report = await window.electronAPI.codeVisualizer.git.impact(result.rootPath, gitBase, result); setResult({ ...result, gitImpact: report }); message.success(`发现 ${report.endpoints.length} 个受影响接口`); }
    catch (error) { message.error(error instanceof Error ? error.message : String(error)); }
  }, [gitBase, result]);
  const importCoverage = useCallback(async (): Promise<void> => {
    if (!result) return;
    const imported = await window.electronAPI.codeVisualizer.coverage.import(result.rootPath);
    if (imported.ok && imported.report) { const next = { ...result, coverage: imported.report }; next.qualityGate = buildQualityGate(next, imported.report); setResult(next); message.success(`覆盖率 ${(imported.report.lineRate * 100).toFixed(1)}%`); }
  }, [result]);
  const runTests = useCallback(async (): Promise<void> => {
    if (!result) return;
    const files = [...new Set(result.endpoints.flatMap((endpoint) => endpoint.tests.map((test) => test.file)))];
    try { const run = await window.electronAPI.codeVisualizer.test.run(result.rootPath, files); Modal.info({ title: run.ok ? '测试通过' : '测试失败', width: 800, content: <pre className="mt-3 max-h-[60vh] overflow-auto whitespace-pre-wrap text-xs">{run.output || `${run.command} · ${run.durationMs} ms`}</pre> }); }
    catch (error) { message.error(error instanceof Error ? error.message : String(error)); }
  }, [result]);

  if (!result && !loading) return <div className="h-full overflow-auto bg-background px-6 py-12 text-foreground"><div className="mx-auto max-w-3xl text-center"><div className="mx-auto mb-5 grid h-20 w-20 place-items-center rounded-3xl border bg-card text-primary shadow-sm"><Code className="h-10 w-10"/></div><h1 className="mb-2 text-2xl font-semibold">代码接口地图</h1><p className="mx-auto mb-6 max-w-lg text-sm leading-6 text-muted-foreground">扫描本地 Python + Vue 仓库，汇总全部 HTTP 接口，并追踪前端请求、后端调用和数据库线索。</p><Button type="primary" size="large" icon={<FolderOpen className="h-4 w-4"/>} onClick={() => void chooseAndScan()}>选择本地仓库</Button>{history.length > 0 && <section className="mt-12 text-left"><div className="mb-3 flex items-center gap-2"><History className="h-4 w-4 text-primary"/><h2 className="text-sm font-semibold">最近项目</h2><span className="text-xs text-muted-foreground">自动保存在本机</span></div><div className="grid gap-3 sm:grid-cols-2">{history.map((entry) => <div key={entry.rootPath} className={`group rounded-xl border bg-card p-4 shadow-sm transition ${entry.available ? 'hover:border-primary/40 hover:shadow-md' : 'opacity-60'}`}><div className="flex items-start gap-3"><button type="button" disabled={!entry.available} onClick={() => void window.electronAPI.codeVisualizer.history.open(entry.rootPath).then((opened) => scan(opened.rootPath)).catch((error: unknown) => message.error(error instanceof Error ? error.message : String(error)))} className="min-w-0 flex-1 text-left disabled:cursor-not-allowed"><div className="truncate text-sm font-semibold">{entry.name}</div><div className="mt-1 truncate text-xs text-muted-foreground" title={entry.rootPath}>{entry.rootPath}</div><div className="mt-3 flex flex-wrap gap-3 text-[11px] text-muted-foreground"><span>{entry.endpointCount} 个接口</span><span>{entry.pythonFiles} Python</span><span>{entry.vueFiles} Vue/TS</span><span>{formatHistoryTime(entry.lastScannedAt)}</span></div>{!entry.available && <div className="mt-2 text-xs text-destructive">目录已移动或删除</div>}</button><button type="button" title="从历史中移除" onClick={() => void window.electronAPI.codeVisualizer.history.remove(entry.rootPath).then(loadHistory)} className="rounded-md p-1 text-muted-foreground opacity-0 transition hover:bg-destructive/10 hover:text-destructive group-hover:opacity-100"><XCircle className="h-4 w-4"/></button></div></div>)}</div></section>}</div></div>;
  if (loading) return <div className="flex h-full items-center justify-center bg-background"><Spin size="large" tip="正在分析接口与调用关系…"/></div>;

  return <div className="flex h-full min-h-0 bg-background text-foreground">
    <aside className="flex w-[350px] shrink-0 flex-col border-r border-sidebar-border bg-sidebar">
      <div className="border-b border-sidebar-border p-4"><div className="mb-3 flex items-center justify-between"><div><div className="font-semibold">接口列表</div><div className="mt-1 max-w-[240px] truncate text-xs text-muted-foreground" title={result?.rootPath}>{result?.rootPath}</div></div><Button type="text" title="重新扫描" icon={<RefreshCw className="h-4 w-4"/>} onClick={() => result && void scan(result.rootPath)}/></div><Input allowClear prefix={<Search className="h-4 w-4"/>} placeholder="搜索 URL、方法、处理函数" value={query} onChange={(event) => setQuery(event.target.value)}/><div className="mt-3 flex gap-3 text-xs text-muted-foreground"><span>{result?.endpoints.length} 个接口</span><span>{result?.pythonFiles} Python</span><span>{result?.vueFiles} Vue/TS</span></div></div>
      <div className="min-h-0 flex-1 overflow-auto p-2">{endpointGroups.length ? endpointGroups.map(([category, items]) => <section key={category} className="mb-2"><button type="button" onClick={() => setCollapsedGroups((current) => { const next = new Set(current); if (next.has(category)) next.delete(category); else next.add(category); return next; })} className="sticky top-0 z-10 flex w-full items-center gap-2 rounded-md bg-sidebar px-2 py-2 text-left text-xs font-semibold text-sidebar-foreground hover:bg-sidebar-hover"><ChevronDown className={`h-3.5 w-3.5 transition ${collapsedGroups.has(category) ? '-rotate-90' : ''}`}/><span className="min-w-0 flex-1 truncate">{category}</span><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground">{items.length}</span></button>{!collapsedGroups.has(category) && <div className="mt-1">{items.map((endpoint) => <button key={endpoint.id + endpoint.location.file} type="button" onClick={() => setSelected(endpoint)} className={`mb-1 w-full rounded-lg border p-3 text-left transition ${selected === endpoint ? 'border-primary/50 bg-sidebar-active text-sidebar-active-foreground' : 'border-transparent hover:bg-sidebar-hover'}`}><div className="flex items-center gap-2"><Tag color={METHOD_COLOR[endpoint.method]}>{endpoint.method}</Tag><span className="truncate text-sm font-medium">{endpoint.path}</span></div><div className="mt-2 truncate text-xs text-muted-foreground">{endpoint.framework} · {endpoint.handler} · 前端 {endpoint.frontendCalls.length}</div></button>)}</div>}</section>) : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="没有匹配的接口"/>}</div>
      <div className="grid grid-cols-2 gap-2 border-t border-sidebar-border p-3"><Input className="col-span-2" size="small" value={gitBase} onChange={(event) => setGitBase(event.target.value)} placeholder="Git 基线，如 main 或 WORKTREE"/><Button size="small" onClick={() => void importOpenApi()}>OpenAPI</Button><Button size="small" onClick={() => void analyzeGitImpact()}>Git 影响</Button><Button size="small" onClick={() => void importCoverage()}>覆盖率</Button><Button size="small" onClick={() => void runTests()}>运行测试</Button>{result?.gitImpact && <Button className="col-span-2" size="small" onClick={() => void navigator.clipboard.writeText(gitImpactMarkdown(result.gitImpact)).then(() => message.success('PR 摘要已复制'))}>复制 PR 摘要</Button>}<Button className="col-span-2" size="small" onClick={() => void importRuntime()}>运行时日志</Button><Button className="col-span-2" icon={<FolderOpen className="h-4 w-4"/>} onClick={() => void chooseAndScan()}>更换仓库</Button></div>
    </aside>
    <main className="min-w-0 flex-1 overflow-auto p-5"><div className="mx-auto mb-4 flex max-w-5xl flex-wrap items-center justify-between gap-2 rounded-lg border bg-card px-3 py-2 text-xs text-muted-foreground"><div className="flex flex-wrap gap-4"><span>{result?.scan?.mode === 'incremental' ? '增量扫描' : '完整扫描'}</span><span>变化 {result?.scan?.changedFiles ?? result?.filesScanned} 文件</span><span>复用 {result?.scan?.reusedFiles ?? 0}</span><span>{result?.scan?.durationMs ?? 0} ms</span><span className={(result?.diagnostics?.filter((item) => item.severity === 'error').length ?? 0) ? 'text-destructive' : ''}>{result?.diagnostics?.length ?? 0} 个诊断</span></div><div className="flex items-center gap-2"><Button size="small" icon={<Network className="h-3.5 w-3.5"/>} onClick={() => setArchitectureOpen(true)}>全局架构</Button><Button size="small" disabled={snapshots.length < 2} onClick={() => setDiffOpen(true)}>快照对比</Button><Select size="small" className="w-52" placeholder="扫描快照" value={result?.scan?.snapshotId} options={snapshots.map((snapshot) => ({ value: snapshot.id, label: `${new Date(snapshot.scannedAt).toLocaleString('zh-CN')} · ${snapshot.endpointCount} 接口` }))} onChange={(id) => result && void window.electronAPI.codeVisualizer.snapshot.load(result.rootPath, id).then((snapshot) => { setResult(snapshot); setSelected(snapshot.endpoints[0] ?? null); setSourceTabs([]); setActiveSourcePath(null); })}/></div></div>{selected && result ? <EndpointDetail endpoint={selected} result={result} onOpenSource={openSource}/> : <Empty description="选择一个接口开始分析"/>}</main>
    <Modal open={architectureOpen} onCancel={() => setArchitectureOpen(false)} footer={null} width="92vw" title={`全局架构图 · ${result?.endpoints.length ?? 0} 个接口`} destroyOnClose>{globalGraph?.nodes.length ? <RelationshipGraph graph={globalGraph} onOpenSource={openSource}/> : <Empty description="当前项目没有可展示的调用关系"/>}</Modal>
    <Modal open={diffOpen} onCancel={() => setDiffOpen(false)} footer={null} width={900} title="扫描快照对比"><div className="mb-4 flex items-center gap-2"><Select className="min-w-72 flex-1" placeholder="基准快照" value={diffFrom} onChange={setDiffFrom} options={snapshots.slice(1).map((snapshot) => ({ value: snapshot.id, label: new Date(snapshot.scannedAt).toLocaleString('zh-CN') }))}/><span>→</span><Select className="min-w-72 flex-1" placeholder="目标快照" value={diffTo} onChange={setDiffTo} options={snapshots.map((snapshot) => ({ value: snapshot.id, label: new Date(snapshot.scannedAt).toLocaleString('zh-CN') }))}/><Button type="primary" disabled={!diffFrom || !diffTo || diffFrom === diffTo} onClick={() => diffFrom && diffTo && result && void window.electronAPI.codeVisualizer.snapshot.diff(result.rootPath, diffFrom, diffTo).then(setSnapshotDiff)}>对比</Button></div>{snapshotDiff ? <div className="grid gap-3 sm:grid-cols-2"><DiffSection title="新增接口" values={snapshotDiff.addedEndpoints} tone="success"/><DiffSection title="删除接口" values={snapshotDiff.removedEndpoints} tone="danger"/><DiffSection title="契约变化" values={snapshotDiff.changedContracts}/><DiffSection title="新增字段" values={snapshotDiff.addedFields} tone="success"/><DiffSection title="删除字段" values={snapshotDiff.removedFields} tone="danger"/><DiffSection title="数据表变化" values={[...snapshotDiff.addedTables.map((item) => `+ ${item}`), ...snapshotDiff.removedTables.map((item) => `- ${item}`)]}/></div> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="选择两个快照开始对比"/>}</Modal>
    {source && result && <SourcePanel rootPath={result.rootPath} tabs={sourceTabs} active={source} onActivate={setActiveSourcePath} onClose={(path) => { const remaining = sourceTabs.filter((tab) => tab.path !== path); setSourceTabs(remaining); if (activeSourcePath === path) setActiveSourcePath(remaining.at(-1)?.path ?? null); }}/>} 
  </div>;
}

type DetailTab = 'overview' | 'governance' | 'relations' | 'parameters' | 'frontend' | 'database' | 'er' | 'dataflow' | 'tests' | 'performance' | 'diagnostics' | 'impact';
const DETAIL_TABS: Array<{ id: DetailTab; label: string }> = [{ id: 'overview', label: '概览' }, { id: 'governance', label: '治理中心' }, { id: 'relations', label: '关系图' }, { id: 'parameters', label: '参数与响应' }, { id: 'frontend', label: '前端调用' }, { id: 'database', label: '数据库' }, { id: 'er', label: 'ER 图' }, { id: 'dataflow', label: '数据流' }, { id: 'tests', label: '测试覆盖' }, { id: 'performance', label: '性能风险' }, { id: 'diagnostics', label: '问题诊断' }, { id: 'impact', label: '影响分析' }];

function EndpointDetail({ endpoint, result, onOpenSource }: { endpoint: ApiEndpoint; result: RepositoryAnalysis; onOpenSource: (node: AnalysisNode) => void }): JSX.Element {
  const [tab, setTab] = useState<DetailTab>('overview');
  const [impactNode, setImpactNode] = useState<AnalysisNode>(() => endpoint.nodes.find((node) => node.kind === 'controller') ?? endpoint.nodes[0]);
  useEffect(() => { setImpactNode(endpoint.nodes.find((node) => node.kind === 'controller') ?? endpoint.nodes[0]); setTab('overview'); }, [endpoint]);
  const impact = useMemo(() => calculateImpact(result, impactNode?.id), [impactNode?.id, result]);
  const diagnostics = result.diagnostics ?? [];
  const runtime = result.runtimeMetrics?.find((item) => item.method === endpoint.method && item.normalizedPath === endpoint.normalizedPath);
  return <div className="mx-auto max-w-5xl"><div className="mb-4 flex items-start justify-between"><div><div className="flex items-center gap-3"><Tag color={METHOD_COLOR[endpoint.method]}>{endpoint.method}</Tag><h2 className="text-xl font-semibold">{endpoint.path}</h2></div><div className="mt-2 text-sm text-muted-foreground">{endpoint.framework} · {endpoint.location.file}:{endpoint.location.line}</div></div><div className="flex gap-2">{endpoint.tables.map((table) => <Tag key={table} icon={<Database className="h-3 w-3"/>}>{table}</Tag>)}</div></div>
    <nav className="mb-4 flex overflow-x-auto border-b">{DETAIL_TABS.map((item) => <button key={item.id} type="button" onClick={() => setTab(item.id)} className={`shrink-0 border-b-2 px-4 py-2 text-xs transition ${tab === item.id ? 'border-primary font-medium text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}`}>{item.label}{item.id === 'diagnostics' && diagnostics.length > 0 ? ` (${diagnostics.length})` : ''}</button>)}</nav>
    {tab === 'overview' && <div className="grid gap-4 md:grid-cols-3"><Metric label="处理函数" value={endpoint.handler}/><Metric label="前端调用" value={String(endpoint.frontendCalls.length)}/><Metric label="关系节点" value={String(endpoint.nodes.length)}/>{result.git?.available && <section className="rounded-xl border bg-card p-4 md:col-span-3"><div className="text-xs text-muted-foreground">Git</div><div className="mt-2 text-sm">{result.git.branch} · {result.git.commit}{result.git.dirty ? ` · ${result.git.changedFiles.length} 个未提交文件` : ' · 工作区干净'}</div></section>}{runtime && <section className="rounded-xl border bg-card p-4 md:col-span-3"><h3 className="mb-3 text-sm font-semibold">运行时指标</h3><div className="grid gap-3 text-sm sm:grid-cols-4"><Info label="请求数" value={String(runtime.requests)}/><Info label="错误率" value={`${(runtime.errorRate * 100).toFixed(1)}%`}/><Info label="P50" value={runtime.p50Ms === undefined ? '—' : `${runtime.p50Ms.toFixed(1)} ms`}/><Info label="P95" value={runtime.p95Ms === undefined ? '—' : `${runtime.p95Ms.toFixed(1)} ms`}/></div></section>}<section className="rounded-xl border bg-card p-4 md:col-span-3"><h3 className="mb-3 text-sm font-semibold">接口契约</h3><div className="grid gap-3 text-sm sm:grid-cols-3"><Info label="请求模型" value={endpoint.contract.requestModel ?? '—'}/><Info label="响应模型" value={endpoint.contract.responseModel ?? '—'}/><Info label="状态码" value={endpoint.contract.statusCodes.join(', ')}/></div></section></div>}
    {tab === 'overview' && (result.openApi || result.gitImpact || result.coverage) && <section className="mt-4 grid gap-3 md:grid-cols-3">{result.openApi && <div className="rounded-xl border bg-card p-4"><div className="text-xs text-muted-foreground">OpenAPI 治理</div><div className="mt-2 text-lg font-semibold">{result.openApi.contractMismatches.length} 个契约差异</div><div className="mt-1 text-xs text-muted-foreground">未文档化 {result.openApi.undocumentedCode.length} · 未实现 {result.openApi.missingImplementation.length}</div></div>}{result.gitImpact && <div className="rounded-xl border bg-card p-4"><div className="text-xs text-muted-foreground">Git 影响 · {result.gitImpact.base}</div><div className="mt-2 text-lg font-semibold">{result.gitImpact.endpoints.length} 个接口</div><div className="mt-1 text-xs text-muted-foreground">{result.gitImpact.changedFiles.length} 文件 · {result.gitImpact.tables.length} 数据表</div></div>}{result.coverage && <div className="rounded-xl border bg-card p-4"><div className="text-xs text-muted-foreground">代码覆盖率</div><div className="mt-2 text-lg font-semibold">{(result.coverage.lineRate * 100).toFixed(1)}%</div><div className="mt-1 text-xs text-muted-foreground">{result.coverage.linesHit}/{result.coverage.linesFound} 行</div></div>}</section>}
    {tab === 'governance' && <section className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Metric label="质量分" value={String(result.qualityGate?.score ?? '—')}/><Metric label="门禁结果" value={result.qualityGate ? result.qualityGate.passed ? '通过' : '未通过' : '待分析'}/><Metric label="接口覆盖率" value={result.qualityGate ? `${result.qualityGate.endpointCoverage.filter((item) => item.covered).length}/${result.endpoints.length}` : '—'}/></div><CardList empty="尚未发现治理问题">{result.qualityGate?.failures.map((failure, index) => <div key={`${failure.rule}:${failure.endpoint}:${index}`} className="rounded-lg border border-warning/30 bg-warning/5 p-3"><div className="flex items-center gap-2"><Tag color={failure.rule === 'breaking-contract' ? 'red' : 'orange'}>{failure.rule}</Tag><span className="text-sm font-medium">{failure.endpoint}</span></div><div className="mt-2 text-xs text-muted-foreground">{failure.message}</div></div>)}</CardList>{result.openApi && <CardList empty="OpenAPI 契约一致">{result.openApi.contractMismatches.map((item) => <div key={item.endpoint} className="rounded-lg border bg-card p-3"><div className="font-medium">{item.endpoint}{item.breaking && <Tag className="ml-2" color="red">breaking</Tag>}</div><div className="mt-2 text-xs text-muted-foreground">{item.changes.join('；')}</div></div>)}</CardList>}</section>}
    {tab === 'relations' && <RelationshipGraph endpoint={endpoint} onOpenSource={onOpenSource} onSelectNode={(node) => setImpactNode(node)}/>} 
    {tab === 'parameters' && <section className="overflow-hidden rounded-xl border bg-card"><div className="grid grid-cols-[1fr_100px_1fr_90px] border-b bg-muted/40 px-4 py-2 text-xs font-medium text-muted-foreground"><span>名称</span><span>来源</span><span>类型/默认值</span><span>必填</span></div>{endpoint.contract.parameters.length ? endpoint.contract.parameters.map((parameter) => <div key={`${parameter.source}:${parameter.name}`} className="grid grid-cols-[1fr_100px_1fr_90px] border-b px-4 py-3 text-sm last:border-0"><code>{parameter.name}</code><Tag>{parameter.source}</Tag><span>{parameter.type}{parameter.defaultValue ? ` = ${parameter.defaultValue}` : ''}</span><span>{parameter.required ? '是' : '否'}</span></div>) : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="未解析到显式参数"/>}</section>}
    {tab === 'frontend' && <CardList empty="未找到匹配的前端调用">{endpoint.frontendCalls.map((call) => <button key={call.id} type="button" onClick={() => onOpenSource({ id: call.id, kind: 'frontend', label: call.path, location: call.location })} className="w-full rounded-lg border bg-background p-3 text-left hover:border-primary/40"><div className="flex gap-2"><Tag color={METHOD_COLOR[call.method]}>{call.method}</Tag><code className="text-sm">{call.path}</code></div><div className="mt-2 text-xs text-muted-foreground">{call.location.file}:{call.location.line}</div></button>)}</CardList>}
    {tab === 'database' && <CardList empty="该调用链没有识别到数据库表">{endpoint.databaseTables.map((table) => <div key={table.name} className="overflow-hidden rounded-xl border bg-background"><button type="button" disabled={!table.location} onClick={() => table.location && onOpenSource({ id: `model:${table.name}`, kind: 'model', label: table.model ?? table.name, location: table.location })} className="flex w-full items-center gap-3 border-b bg-muted/30 px-4 py-3 text-left disabled:cursor-default"><Database className="h-5 w-5 text-primary"/><div className="min-w-0 flex-1"><div className="font-medium">{table.name}</div><div className="text-xs text-muted-foreground">{table.model ? `Model: ${table.model}` : '由 SQL 语句推断'} · {table.fields.length} 个字段</div></div>{table.location && <span className="text-xs text-muted-foreground">{table.location.file}:{table.location.line}</span>}</button>{table.fields.length ? <div className="overflow-x-auto"><div className="grid min-w-[680px] grid-cols-[1.2fr_1fr_70px_70px_1fr_1fr] border-b px-4 py-2 text-[11px] font-medium text-muted-foreground"><span>字段</span><span>类型</span><span>主键</span><span>可空</span><span>默认值</span><span>外键</span></div>{table.fields.map((field) => <button type="button" key={field.name} onClick={() => field.location && onOpenSource({ id: `field:${table.name}:${field.name}`, kind: 'model', label: `${table.name}.${field.name}`, location: field.location })} className="grid min-w-[680px] w-full grid-cols-[1.2fr_1fr_70px_70px_1fr_1fr] border-b px-4 py-2.5 text-left text-xs last:border-0 hover:bg-primary/5"><code className="font-medium text-primary">{field.name}</code><span className="truncate" title={field.type}>{field.type}</span><span>{field.primaryKey ? '是' : '—'}</span><span>{field.nullable ? '是' : '否'}</span><span className="truncate">{field.defaultValue ?? '—'}</span><span className="truncate" title={field.foreignKey}>{field.foreignKey ?? '—'}</span></button>)}</div> : <div className="px-4 py-3 text-xs text-muted-foreground">仅从 SQL 中识别到表名，未找到对应 ORM Model 字段定义。</div>}</div>)}</CardList>}
    {tab === 'er' && (endpoint.databaseTables?.length ? <ErDiagram tables={endpoint.databaseTables} relations={result.databaseRelations ?? []}/> : <Empty description="当前接口没有可绘制的数据表关系"/>)}
    {tab === 'dataflow' && <CardList empty="未解析到字段数据流">{endpoint.dataFlow?.map((step, index) => <React.Fragment key={step.id}>{index > 0 && <div className="ml-5 h-3 border-l border-dashed"/>}<button type="button" disabled={!step.location} onClick={() => step.location && onOpenSource({ id: step.id, kind: step.stage === 'frontend' ? 'frontend' : step.stage === 'field' || step.stage === 'model' ? 'model' : 'service', label: step.label, location: step.location })} className="flex w-full items-center gap-3 rounded-lg border bg-background px-4 py-3 text-left disabled:cursor-default"><Tag color={step.stage === 'field' ? 'purple' : step.stage === 'frontend' ? 'blue' : 'default'}>{step.stage}</Tag><span className="font-medium">{step.label}</span><span className="ml-auto text-xs text-muted-foreground">{step.detail}</span></button></React.Fragment>)}</CardList>}
    {tab === 'tests' && <CardList empty="未找到覆盖该接口的测试"><div className={`rounded-lg border p-3 text-sm ${endpoint.tests?.length ? 'border-success/30 bg-success/5 text-success' : 'border-warning/30 bg-warning/5 text-warning'}`}>{endpoint.tests?.length ? `找到 ${endpoint.tests.length} 个相关测试` : '该接口可能没有自动化测试覆盖'}</div>{endpoint.tests?.map((test) => <button key={`${test.file}:${test.line}`} type="button" onClick={() => onOpenSource({ id: `test:${test.file}:${test.line}`, kind: 'service', label: test.file, location: { file: test.file, line: test.line, snippet: test.evidence } })} className="w-full rounded-lg border bg-background p-3 text-left hover:border-primary/40"><div className="flex items-center gap-2"><Tag>{test.kind}</Tag><span className="text-sm font-medium">{test.file}:{test.line}</span></div><code className="mt-2 block truncate text-xs text-muted-foreground">{test.evidence}</code></button>)}</CardList>}
    {tab === 'performance' && <section className="space-y-3 rounded-xl border bg-card p-4">{endpoint.performanceRisks === undefined ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="该结果来自旧版扫描，请刷新分析以生成性能报告"/> : <><div className={`rounded-lg border p-3 ${endpoint.performanceRisks.length ? 'border-warning/30 bg-warning/5' : 'border-success/30 bg-success/5'}`}><div className="flex items-center justify-between"><span className="text-sm font-medium">{endpoint.performanceRisks.length ? `发现 ${endpoint.performanceRisks.length} 个静态性能风险` : '静态性能检查已完成，暂未发现风险'}</span><Tag color={endpoint.performanceRisks.length ? 'orange' : 'green'}>{endpoint.nodes.filter((node) => node.kind === 'controller' || node.kind === 'service' || node.kind === 'repository').length} 个函数</Tag></div><div className="mt-2 text-xs text-muted-foreground">已检查循环数据库/外部调用、无界查询、异步阻塞、重复读表和过深调用链。静态分析不等同于运行时性能测试。</div></div>{endpoint.performanceRisks.map((risk) => <button key={risk.id} type="button" onClick={() => onOpenSource({ id: risk.id, kind: 'service', label: risk.rule, location: risk.location })} className={`w-full rounded-lg border p-3 text-left ${risk.severity === 'error' ? 'border-destructive/30 bg-destructive/5' : 'border-warning/30 bg-warning/5'}`}><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">{risk.message}</span><Tag color={risk.severity === 'error' ? 'red' : 'orange'}>{risk.rule}</Tag></div><div className="mt-2 text-xs text-muted-foreground">{risk.location.file}:{risk.location.line} · 静态推断 · 点击查看源码</div></button>)}</>}</section>}
    {tab === 'diagnostics' && <CardList empty="当前仓库未发现前后端接口不一致">{diagnostics.map((diagnostic) => <div key={diagnostic.id} className={`rounded-lg border p-3 ${diagnostic.severity === 'error' ? 'border-destructive/30 bg-destructive/5' : 'bg-card'}`}><div className="flex items-center justify-between"><span className={diagnostic.severity === 'error' ? 'text-sm font-medium text-destructive' : 'text-sm font-medium'}>{diagnostic.message}</span><Tag color={diagnostic.severity === 'error' ? 'red' : 'default'}>{diagnostic.kind}</Tag></div><div className="mt-2 text-xs text-muted-foreground">{diagnostic.location.file}:{diagnostic.location.line}</div></div>)}</CardList>}
    {tab === 'impact' && <section className="space-y-4"><div className="rounded-xl border bg-card p-4"><label className="mb-2 block text-xs text-muted-foreground">分析节点</label><Select className="w-full" value={impactNode?.id} options={endpoint.nodes.map((node) => ({ value: node.id, label: `${KIND_LABEL[node.kind]} · ${node.label}` }))} onChange={(id) => { const node = endpoint.nodes.find((item) => item.id === id); if (node) setImpactNode(node); }}/></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="受影响接口" value={String(impact.endpoints.length)}/><Metric label="前端调用" value={String(impact.frontendCalls)}/><Metric label="数据库表" value={String(impact.tables.length)}/></div><CardList empty="没有发现跨接口影响">{impact.endpoints.map((item) => <div key={`${item.id}:${item.location.file}`} className="rounded-lg border bg-card p-3"><Tag color={METHOD_COLOR[item.method]}>{item.method}</Tag><span className="ml-2 text-sm font-medium">{item.path}</span></div>)}</CardList>{impact.tables.length > 0 && <div className="flex flex-wrap gap-2">{impact.tables.map((table) => <Tag key={table} icon={<Database className="h-3 w-3"/>}>{table}</Tag>)}</div>}</section>}
  </div>;
}

function Metric({ label, value }: { label: string; value: string }): JSX.Element { return <div className="rounded-xl border bg-card p-4 shadow-sm"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-2 truncate text-lg font-semibold">{value}</div></div>; }
function Info({ label, value }: { label: string; value: string }): JSX.Element { return <div><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 font-medium">{value}</div></div>; }
function CardList({ children, empty }: { children: React.ReactNode; empty: string }): JSX.Element { const items = Children.toArray(children); return <section className="space-y-2 rounded-xl border bg-card p-4">{items.length ? items : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={empty}/>}</section>; }
function DiffSection({ title, values, tone }: { title: string; values: string[]; tone?: 'success' | 'danger' }): JSX.Element { return <section className="min-h-28 rounded-xl border bg-card p-3"><div className={`mb-2 text-xs font-semibold ${tone === 'success' ? 'text-success' : tone === 'danger' ? 'text-destructive' : ''}`}>{title} ({values.length})</div>{values.length ? <div className="max-h-40 space-y-1 overflow-auto">{values.map((value) => <div key={value} className="truncate rounded bg-muted/50 px-2 py-1 text-xs" title={value}>{value}</div>)}</div> : <span className="text-xs text-muted-foreground">无变化</span>}</section>; }

function calculateImpact(result: RepositoryAnalysis, nodeId?: string): { endpoints: ApiEndpoint[]; frontendCalls: number; tables: string[] } {
  if (!nodeId) return { endpoints: [], frontendCalls: 0, tables: [] };
  const endpoints = result.endpoints.filter((endpoint) => endpoint.nodes.some((node) => node.id === nodeId));
  return { endpoints, frontendCalls: endpoints.reduce((total, endpoint) => total + endpoint.frontendCalls.length, 0), tables: [...new Set(endpoints.flatMap((endpoint) => endpoint.tables))] };
}

function buildGlobalGraph(result: RepositoryAnalysis): NonNullable<RepositoryAnalysis['globalGraph']> {
  if (result.globalGraph?.nodes.length) return result.globalGraph;
  const nodes = new Map<string, AnalysisNode>();
  const edges = new Map<string, ApiEndpoint['edges'][number]>();
  for (const endpoint of result.endpoints) {
    for (const node of endpoint.nodes) nodes.set(node.id, node);
    for (const edge of endpoint.edges) edges.set(`${edge.source}:${edge.kind}:${edge.target}`, edge);
  }
  return { nodes: [...nodes.values()], edges: [...edges.values()] };
}

export function LegacyEndpointDetail({ endpoint, onOpenSource }: { endpoint: ApiEndpoint; onOpenSource: (node: AnalysisNode) => void }): JSX.Element {
  const ordered = orderNodes(endpoint);
  const [view, setView] = useState<'graph' | 'chain'>('graph');
  return <div className="mx-auto max-w-5xl"><div className="mb-5 flex items-start justify-between"><div><div className="flex items-center gap-3"><Tag color={METHOD_COLOR[endpoint.method]}>{endpoint.method}</Tag><h2 className="text-xl font-semibold">{endpoint.path}</h2></div><div className="mt-2 text-sm text-muted-foreground">{endpoint.framework} · {endpoint.location.file}:{endpoint.location.line}</div></div><div className="flex gap-2">{endpoint.tables.map((table) => <Tag key={table} icon={<Database className="h-3 w-3"/>}>{table}</Tag>)}</div></div>
    <div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold">端到端调用关系</h3><div className="flex rounded-lg border bg-card p-1"><button type="button" className={`flex items-center gap-1.5 rounded-md px-3 py-1 text-xs ${view === 'graph' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-accent'}`} onClick={() => setView('graph')}><Network className="h-3.5 w-3.5"/>关系图</button><button type="button" className={`flex items-center gap-1.5 rounded-md px-3 py-1 text-xs ${view === 'chain' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-accent'}`} onClick={() => setView('chain')}><Rows3 className="h-3.5 w-3.5"/>链路</button></div></div>
    {view === 'graph' ? <RelationshipGraph endpoint={endpoint} onOpenSource={onOpenSource}/> : <section className="rounded-xl border bg-card p-4 shadow-sm"><div className="flex flex-col gap-2">{ordered.map((node, index) => <React.Fragment key={node.id}>{index > 0 && <div className="ml-6 h-4 border-l border-dashed"/>}<button type="button" disabled={!node.location} onClick={() => void onOpenSource(node)} className="flex w-full items-center gap-3 rounded-lg border bg-background px-4 py-3 text-left transition hover:border-primary/50 hover:bg-primary/5 disabled:cursor-default disabled:hover:border-border disabled:hover:bg-background"><span className="w-20 shrink-0 text-xs font-medium uppercase text-primary">{KIND_LABEL[node.kind]}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{node.label}</span>{node.detail && <span className="mt-1 block truncate text-xs text-muted-foreground">{node.detail}</span>}</span>{node.location && <span className="text-xs text-muted-foreground">{node.location.file}:{node.location.line}</span>}</button></React.Fragment>)}</div></section>}
    {endpoint.frontendCalls.length === 0 && <div className="mt-4 rounded-lg border border-warning/30 bg-warning/5 p-3 text-sm text-warning">未找到静态可匹配的 Vue 请求。动态拼接 URL 或封装较深的请求需要后续适配。</div>}
  </div>;
}

function SourcePanel({ rootPath, tabs, active, onActivate, onClose }: { rootPath: string; tabs: SourceTab[]; active: SourceTab; onActivate: (path: string) => void; onClose: (path: string) => void }): JSX.Element {
  const dark = document.documentElement.classList.contains('dark');
  const language = active.path.endsWith('.py') ? 'python' : active.path.endsWith('.vue') ? 'html' : active.path.endsWith('.ts') || active.path.endsWith('.tsx') ? 'typescript' : 'javascript';
  const handleMount: OnMount = (editor) => {
    const endLine = Math.min(active.endLine, editor.getModel()?.getLineCount() ?? active.endLine);
    editor.deltaDecorations([], [{ range: { startLineNumber: active.line, startColumn: 1, endLineNumber: endLine, endColumn: 1 }, options: { isWholeLine: true, className: 'code-visualizer-source-highlight', linesDecorationsClassName: 'code-visualizer-source-gutter', overviewRuler: { color: 'rgba(126, 52, 121, 0.75)', position: 7 } } }]);
    editor.revealLinesInCenter(active.line, endLine);
    editor.setPosition({ lineNumber: active.line, column: 1 });
    editor.focus();
  };
  return <aside className="relative flex w-[48%] min-w-[460px] flex-col border-l-2 border-l-primary/40 bg-card shadow-[-8px_0_24px_rgba(0,0,0,0.08)]"><div className="flex h-10 shrink-0 overflow-x-auto border-b bg-background">{tabs.map((tab) => <button key={tab.path} type="button" onClick={() => onActivate(tab.path)} className={`group flex max-w-56 shrink-0 items-center gap-2 border-r px-3 text-xs ${tab.path === active.path ? 'border-t-2 border-t-primary bg-card text-foreground' : 'text-muted-foreground hover:bg-accent'}`}><span className="truncate">{tab.path.split('/').at(-1)}</span><span role="button" tabIndex={0} aria-label={`关闭 ${tab.path}`} onClick={(event) => { event.stopPropagation(); onClose(tab.path); }} onKeyDown={(event) => { if (event.key === 'Enter') onClose(tab.path); }} className="rounded p-0.5 opacity-0 transition hover:bg-muted group-hover:opacity-100"><XCircle className="h-3 w-3"/></span></button>)}</div><div className="flex items-center gap-2 border-b bg-primary/5 px-3 py-2"><Tag color="purple">{KIND_LABEL[active.kind]}</Tag><strong className="truncate text-xs">{active.label}</strong><span className="ml-auto truncate text-[11px] text-muted-foreground" title={active.path}>{active.path} · {active.line}{active.endLine > active.line ? `–${active.endLine}` : ''} 行</span><Button type="text" size="small" title="在 VS Code 中打开" icon={<ExternalLink className="h-3.5 w-3.5"/>} onClick={() => void window.electronAPI.codeVisualizer.source.openExternal(rootPath, active.path, active.line)}/></div><div className="min-h-0 flex-1"><MonacoEditor key={`${active.path}:${active.line}:${active.endLine}`} value={active.content} language={language} theme={dark ? 'vs-dark' : 'light'} loading={<div className="grid h-full place-items-center text-xs text-muted-foreground">正在加载本地源码编辑器…</div>} onMount={handleMount} options={{ automaticLayout: true, readOnly: true, minimap: { enabled: true, showSlider: 'mouseover', size: 'fit' }, lineNumbersMinChars: 3, fontSize: 12, scrollBeyondLastLine: false, renderLineHighlight: 'all', wordWrap: 'off', overviewRulerBorder: false }}/></div></aside>;
}

function formatHistoryTime(timestamp: number): string {
  const elapsed = Date.now() - timestamp;
  if (elapsed < 60_000) return '刚刚';
  if (elapsed < 3_600_000) return `${Math.floor(elapsed / 60_000)} 分钟前`;
  if (elapsed < 86_400_000) return `${Math.floor(elapsed / 3_600_000)} 小时前`;
  return new Date(timestamp).toLocaleDateString('zh-CN');
}

function endpointCategory(routePath: string): string {
  const segments = routePath.split('/').filter((segment) => segment && !segment.startsWith('{') && !segment.startsWith(':'));
  if (segments[0] === 'api' && /^v\d+$/i.test(segments[1] ?? '')) return segments[2] ? `API / ${segments[2]}` : `API / ${segments[1]}`;
  if (segments[0] === 'backend' && segments[1]) return `Backend / ${segments[1]}`;
  return segments[0] ? segments[0][0].toUpperCase() + segments[0].slice(1) : '其他接口';
}

function orderNodes(endpoint: ApiEndpoint): AnalysisNode[] {
  const byId = new Map(endpoint.nodes.map((node) => [node.id, node]));
  const incoming = new Set(endpoint.edges.map((edge) => edge.target));
  const roots = endpoint.nodes.filter((node) => !incoming.has(node.id));
  const ordered: AnalysisNode[] = []; const seen = new Set<string>();
  const walk = (node: AnalysisNode): void => { if (seen.has(node.id)) return; seen.add(node.id); ordered.push(node); for (const edge of endpoint.edges.filter((item) => item.source === node.id)) { const child = byId.get(edge.target); if (child) walk(child); } };
  for (const root of roots) walk(root); for (const node of endpoint.nodes) walk(node); return ordered;
}
