import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

import 'device_profile.dart';
import 'qr_parser.dart';

/// Pairing result.
class PairingResult {
  const PairingResult({
    required this.sessionToken,
    required this.wsUrl,
    required this.httpBase,
    required this.qr,
  });

  final String sessionToken;
  final String wsUrl;
  final String httpBase;
  final PairingQr qr;
}

/// Errors emitted by the pairing flow.
class PairingError implements Exception {
  const PairingError(this.message, {this.statusCode});
  final String message;
  final int? statusCode;
  @override
  String toString() => 'PairingError($statusCode): $message';
}

/// Drives the desktop's `/api/pair/complete` endpoint and persists credentials.
class PairingService extends ChangeNotifier {
  PairingService(this._profile);

  final DeviceProfile _profile;
  http.Client _client = http.Client();

  PairingResult? _lastResult;
  PairingResult? get lastResult => _lastResult;

  String? _error;
  String? get error => _error;

  bool _busy = false;
  bool get busy => _busy;

  /// Exchange a 6-digit pair code for a session token. The QR was generated by
  /// the desktop (Rust sidecar) and encodes a `host`/`httpPort`/`wsPort`/`code`
  /// bundle; either the full URL form or just the 6 digits are accepted.
  Future<PairingResult> pair({required PairingQr qr, String? displayName}) async {
    _setBusy(true);
    _error = null;
    try {
      final deviceName = displayName ?? _profile.deviceName;
      final body = jsonEncode({
        'device_id': _profile.deviceId,
        'device_name': deviceName,
        'pairing_code': qr.pairCode,
      });
      final resp = await _client
          .post(
            Uri.parse('${qr.httpBase}/api/pair/complete'),
            headers: const {'Content-Type': 'application/json'},
            body: body,
          )
          .timeout(const Duration(seconds: 10));
      if (resp.statusCode != 200) {
        String message;
        try {
          final json = jsonDecode(resp.body) as Map<String, dynamic>;
          message = (json['error'] as String?) ?? ('HTTP ${resp.statusCode}');
        } catch (_) {
          message = 'HTTP ${resp.statusCode}';
        }
        _error = message;
        throw PairingError(message, statusCode: resp.statusCode);
      }
      final json = jsonDecode(resp.body) as Map<String, dynamic>;
      final token = json['session_token'] as String?;
      if (token == null || token.isEmpty) {
        throw const PairingError('服务端响应缺少 session_token');
      }
      final wsUrl = (json['ws_url'] as String?) ?? qr.wsUrl;
      final httpBase = (json['http_url'] as String?) ?? qr.httpBase;

      final result = PairingResult(
        sessionToken: token,
        wsUrl: wsUrl,
        httpBase: httpBase,
        qr: qr,
      );
      _lastResult = result;
      await _profile.rememberHost(
        host: qr.host,
        httpPort: qr.httpPort,
        wsPort: qr.wsPort,
        pairCode: qr.pairCode,
      );
      notifyListeners();
      return result;
    } on PairingError {
      notifyListeners();
      rethrow;
    } catch (e) {
      _error = e.toString();
      notifyListeners();
      throw PairingError(_error!);
    } finally {
      _setBusy(false);
    }
  }

  /// Revoke a previously issued session token (best-effort).
  Future<void> revoke(PairingResult result) async {
    // The current sidecar doesn't expose a /api/pair/revoke endpoint yet; the
    // server cleans up sessions on daemon restart. We just drop the local
    // cached credentials.
    if (identical(_lastResult, result)) {
      _lastResult = null;
      notifyListeners();
    }
  }

  void _setBusy(bool v) {
    _busy = v;
    notifyListeners();
  }

  @override
  void dispose() {
    _client.close();
    super.dispose();
  }
}
